MM-26944 Implement PlaybooksService
mattermost/mattermost-plugin-incident-collaboration pull request #290
Opened 2020-09-19 07:23 UTC by JeremyShih

#### Summary

Implement PlaybooksService

#### Ticket Link

mattermost-server#15412
JIRA: https://mattermost.atlassian.net/browse/MM-26944

I am not sure which fields are required and how to verify it so I decided to create the pull request with current progress.
Please help check with it and tell me what you think about the ticket.

2020-09-23 16:49 UTC, crspeller requested changes
Thanks for the contribution! 
For your question on validation, we generally leave that to the server, so I think it's fine as is.

2020-09-23 16:49 UTC, crspeller commented on client/playbooks.go
> +	u := playbooks
I usually try to avoid one letter variable names, except the go receivers by convention.

2020-09-23 16:49 UTC, crspeller commented on client/playbooks.go
> +const playbooks = "playbooks"
Might be more clear if it's just embedded into the fmt stuff? Rather than pulling out this constant.

2020-09-23 16:49 UTC, crspeller commented on client/playbooks.go
> +	resp.Body.Close()
the `Do` function closes the body so these are redundant.

2020-09-25 03:05 UTC, JeremyShih commented
I have updated according to comments but golangci-lint will complain about them.
![image](https://user-images.githubusercontent.com/7455516/94221987-d07a5000-ff1e-11ea-8744-9076e3b3d7f6.png)

2020-09-25 15:19 UTC, crspeller commented
@JeremyShih Sorry about that! We have been experimenting with some aggressive linting configuration. I made a PR to back off some of the more flaky ones: https://github.com/mattermost/mattermost-plugin-incident-response/pull/299

Once that's merged, you should be able to merge master and those will go away.

2020-09-25 16:32 UTC, crspeller commented
It's merged now. A merge from master should fix the errors.

2020-09-27 03:30 UTC, JeremyShih commented
@crspeller No worries. Just a little bit confused which coding style to follow.
Updated and merged from master.

2020-09-28 16:04 UTC, crspeller approved these changes
Looks good :+1:

2020-10-04 06:02 UTC, JeremyShih commented
Thanks @crspeller.
Is there any other action need from me?

2020-10-04 14:23 UTC, cpoile requested changes
Looks great @JeremyShih!

There's one aspect of the ticket that still needs some work, if you're willing to do that? It's this part:

> The existing API unit tests for the API manually construct the necessary HTTP requests to verify the current behaviour, e.g.: `testreq, err := http.NewRequest("GET", "/api/v1/playbooks/testplaybookid", nil)` 
Update these tests to use the Go client instead.

If you're not able to, we can work out something (maybe one of us can do it, or we can ask another community member to help).

Other than that, like I said, great work and thanks!

2020-10-06 15:37 UTC, JeremyShih commented
Sure I will work on that and push again in a few days.
I just saw the readme is just updated. `make test` should work and I could use it to try with the unit test.

2020-10-17 07:30 UTC, JeremyShih commented
Hi @cpoile,

I kept getting errors or build failed. Could you provide some help or examples?

Using a NewPlaybooksService function and golangci-lint failed
![image](https://user-images.githubusercontent.com/7455516/96331122-4c366b00-108d-11eb-9df5-579537f4bc63.png)

Declaring a PlaybookCreateOptions and got unknown field TeamID in struct literal
![image](https://user-images.githubusercontent.com/7455516/96331160-9ddef580-108d-11eb-867f-699e38a5fcd7.png)

2020-10-19 16:27 UTC, crspeller commented
@JeremyShih Sorry about the strange errors. We are experimenting with a go "submodule" for the client so we can version it separate. I think once https://github.com/mattermost/mattermost-plugin-incident-response/pull/349 is merged, you can merge that into this branch and it should fix the strange errors.

2020-10-19 17:14 UTC, cpoile commented
/update-branch

2020-10-19 17:19 UTC, cpoile commented
Thanks for your patience, @JeremyShih . It's compiling fine now. There's a linting error and a problem with one of the tests, but those should be fixable now. Thanks again!

2020-10-30 01:01 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich

2020-10-30 04:27 UTC, jasonblais commented
@cpoile what is the next step from here?

2020-10-31 07:20 UTC, JeremyShih commented
Just rebased the branch onto master and got other errors.
![image](https://user-images.githubusercontent.com/7455516/97773464-dcdf7180-1b8a-11eb-9040-6e9f6d1ac281.png)

Could you provide a basic example for the test using client package?
If you need to merge the feature soon, any of you could take over from me.

2020-11-03 15:55 UTC, jasonblais commented
@cpoile would you be open to helping with above question? (cc @prapti)

2020-11-04 15:45 UTC, cpoile commented
/update-branch

2020-11-04 18:01 UTC, cpoile commented
@JeremyShih Apologies for the trouble here -- we had to bump the versions and @lieut-data tagged the client, so now it's working. Apply this patch for the fix
[fix_client_versioning_issue.patch.zip](https://github.com/mattermost/mattermost-plugin-incident-management/files/5489667/fix_client_versioning_issue.patch.zip)

2020-11-08 14:19 UTC, JeremyShih commented
I have set ServiceSettings.EnableTesting and EnableDeveloper to true in `tests/test-config.json` and `config/config.json`.
Not sure if some other setup needed.
![image](https://user-images.githubusercontent.com/7455516/98467334-b2875700-220f-11eb-9f3b-2ae1c041e759.png)

Below is error in server
![image](https://user-images.githubusercontent.com/7455516/98467344-c337cd00-220f-11eb-82f1-83b375476a36.png)

2021-03-29 15:36 UTC, lieut-data commented
Thanks for the efforts here, @JeremyShih! We've changed a few things in our API since your help here, so it's going to be easier to start from scratch.

2021-03-29 15:36 UTC, closed without merging