MM-26942 Incidents Service
mattermost/mattermost-plugin-incident-collaboration pull request #357
Opened 2020-10-24 22:54 UTC by christian-lim

#### Summary
This pull requests implements the rest of the incidents service. I've been struggling finding some time to finish the test updates, but I wanted to get the PR going for the incidents service itself. Will be posting a question on an issue I've been having with replacing the HTTP calls in the tests.

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/15786

2020-10-24 22:54 UTC, mattermod commented
Hello @christian-lim,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-10-28 17:28 UTC, agarciamontoro commented
I'm gonna review this PR tomorrow! Sorry for the delay, @christian-lim :pray:

2020-11-10 01:01 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2020-11-10 04:33 UTC, christian-lim commented
Addressed PR comments. Thanks for the in-depth explanations!
Seems like the failing tests have something to do with playbooks, which I don't think my changes would've impacted.

2020-11-10 05:55 UTC, jasonblais commented
Thanks @christian-lim for the updates! @agarciamontoro FYI on above, ready for a review :)

2020-11-10 09:52 UTC, agarciamontoro commented
Thank you @christian-lim! I only see this one commit (https://github.com/mattermost/mattermost-plugin-incident-management/pull/357/commits/e9d575a8520dbf7a9d1835c45a7d4ed0e38bb22f). Is there maybe something else you did not push?

2020-11-27 02:46 UTC, christian-lim commented
Hello, thanks for being so patient! I apologize, I didn't actually push the changes. I just pushed the commit that addresses all the PR comments.

2020-12-02 12:17 UTC, agarciamontoro requested changes
Cool, this is looking much better now! :tada:

I noticed that there are still some unresolved comments. I re-wrote the comments with some more information below.

Thank you for your work on this, @christian-lim!

2020-12-02 12:17 UTC, agarciamontoro commented on client/incidents.go
> +	req, err := s.client.NewRequest(http.MethodPatch, incidentURL, incidentUpdateRequest)
We can directly pass the `opts` param as the last parameter in `NewRequest` (so we don't need to build an Incident with that info). We need to keep the pointers as received, even if they are nil.
```suggestion
	req, err := s.client.NewRequest(http.MethodPatch, incidentURL, opts)
```

2020-12-02 12:17 UTC, agarciamontoro commented on client/incidents.go
> +	req.Header.Add("Mattermost-User-ID", *opts.CommanderUserID)
We can remove this line
```suggestion
```

2020-12-02 12:17 UTC, agarciamontoro commented on client/incidents.go
>  func (s *IncidentsService) List(ctx context.Context, opts IncidentListOptions) (*IncidentList, error) {
The comment above still applies. We need to add the `url` tags to `incident.GetIncidentsResults` so the `addOptions` function works as expected: see [the comment in that function](https://github.com/mattermost/mattermost-plugin-incident-management/blob/master/client/client.go#L208-L228).

2020-12-02 12:17 UTC, agarciamontoro commented on server/incident/incident.go
> +	ActiveStage     *int    `json:"active_stage"`
We can revert this change, as [the current implementation](https://github.com/mattermost/mattermost-plugin-incident-management/blob/master/server/api/incidents.go#L140-L168) only changes the active stage.
```suggestion
	ActiveStage *int `json:"active_stage"`
```

2020-12-13 01:01 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2020-12-14 19:12 UTC, jfrerich commented
Thanks for the PR, @christian-lim!  Do you need any assistance or clarification from the PR reviews?

2020-12-20 17:17 UTC, christian-lim commented
> Thanks for the PR, @christian-lim! Do you need any assistance or clarification from the PR reviews?

Nope, addressed comments, but I do need to remove a gmail filter...

2020-12-21 14:52 UTC, agarciamontoro requested changes
Thank you for the changes, @christian-lim! :tada:

One last round of changes and I think we're ready to go!

2020-12-21 14:52 UTC, agarciamontoro commented on server/incident/incident.go
> +	URL        string     `json:"url"`
Sorry for the confusion in my previous comment. When I said "url tags" I meant adding tags to the existing fields in the struct using the `url` key. I also meant to do it in the `HeaderFilterOptions` struct (my bad!). We need that information in the struct because the `addOptions` function uses it to create the url with the specified query parameters in the struct (you can read more about this in https://pkg.go.dev/github.com/google/go-querystring/query#Values).

In short, we need to remove this new `URL` field from the `GetIncidentsResults` struct, and then change the `HeaderFilterOptions` struct ([in the incident/filter_options.go file](https://github.com/mattermost/mattermost-plugin-incident-management/blob/master/server/incident/filter_options.go#L26-L55)) into this:
```go
// HeaderFilterOptions specifies the optional parameters when getting headers.
type HeaderFilterOptions struct {
	// Gets all the headers with this TeamID.
	TeamID string `url:"team_id,omitempty"`

	// Pagination options.
	Page    int `url:"page,omitempty"`
	PerPage int `url:"per_page,omitempty"`

	// Sort sorts by this header field in json format (eg, "create_at", "end_at", "name", etc.);
	// defaults to "create_at".
	Sort string `url:"sort,omitempty"`

	// Direction orders by Asc (ascending), or Desc (descending); defaults to desc.
	Direction string `url:"direction,omitempty"`

	// Status filters by All, Ongoing, or Ended; defaults to All.
	Status Status `url:"status,omitempty"`

	// CommanderID filters by commander's Mattermost user ID. Defaults to blank (no filter).
	CommanderID string `url:"commander_user_id,omitempty"`

	// MemberID filters incidents that have this member. Defaults to blank (no filter).
	MemberID string `url:"member_id,omitempty"`

	// SearchTerm returns results of the search term and respecting the other header filter options.
	// The search term acts as a filter and respects the Sort and Direction fields (i.e., results are
	// not returned in relevance order).
	SearchTerm string `url:"search_term,omitempty"`
}
```

The values of the `url` tags come from the parameters retrieved in [this function](https://github.com/mattermost/mattermost-plugin-incident-management/blob/master/server/api/incidents.go#L948-L1005).

2020-12-21 15:37 UTC, christian-lim commented on server/incident/incident.go
> +	URL        string     `json:"url"`
Pushed, thanks for the docs!

2020-12-21 16:44 UTC, agarciamontoro reviewed
Great, thank you @christian-lim :rocket: 

I think the code looks good now! But we need to test it first, of course. I re-read your PR description and you said that you would "be posting a question on an issue with replacing the HTTP calls in the tests".

What was the issue? We can sort it out together!

2021-02-01 18:25 UTC, lieut-data commented
/update-branch

2021-02-12 21:17 UTC, lieut-data commented
@agarciamontoro & @crspeller, I've made some proposed changes to this PR that dramatically reworks the `client` package. A few highlights:
* To focus the effort, I'm removing all "unsupported" functionality from the `client` package: we'll add it back later.
* The client package no longer tests itself: instead, the `server/api` package tests /using/ the client.
* I'm /duplicating/ the model structures into the `client` package: this allows the use of same from a single package (vs. having to pull in a different package defining them), /and/ exposes them for documentation purposes, something our enterprise license restricts outside of the special `client` module.
* I've streamlined constructing the client on the assumption it's almost always going to be used with a `Client4` instance.

There are probably other improvements to make, but since we're `< 1.0` for this module, I'd like to get alignment on the proposed changes and then plow more changes into subsequent PRs.

2021-02-15 10:47 UTC, agarciamontoro requested changes
Nice! :tada: I really like how readable the tests are now :pray:

Apart from the individual comments below, I have a couple of general questions:

1. - `Incident.Update` is not yet implemented. Is that intended?
2. - I guess that the panic in the `to{API,Internal}Incident` functions is what makes the struct duplication safe, right?
3. - There are a couple of things here from other PRs, if I'm not mistaken. Namely, the removal of the subscriptions and the context stuff in the API. Is that intended?
4. - Not for this PR, but worth discussing: `assert.Equal(t, testIncident, toInternalIncident(*resultIncident))` will fail if we ever decide to make the two structs (the one in the API and the normal one) diverge. Any plans for that?

2021-02-15 10:47 UTC, agarciamontoro commented on server/api/api.go
> -
These changes were already done in another PR, right?

2021-02-15 10:47 UTC, agarciamontoro commented on server/api/api.yaml
> +            curl -X PATCH 'http://localhost:8065/plugins/com.mattermost.plugin-incident-management/api/v0/incidents/mx3xyzdojfgyfdx8sc8of1gdme' \
Good catches!

2021-02-15 10:47 UTC, agarciamontoro commented on client/unexport_test.go
> +var NewClient = newClient
What is this for?

2021-02-15 10:47 UTC, agarciamontoro commented on server/api/api_test.go
> +}
Why panic here (and in the following ones) instead of making this a `t.Helper()` and calling `require.NoError(t, err)`?

2021-02-15 10:47 UTC, agarciamontoro commented on server/api/incidents_test.go
> -	t.Run("create invalid incident - channel id already set", func(t *testing.T) {
Is this test gone?

2021-02-16 14:11 UTC, lieut-data commented on client/doc.go
> +// Package client provides an HTTP client for using the Incident Management API.
I /think/ `pkg.go.dev` will do this automatically for us, pulling up examples that aren't bound to a particular service directly into the root. (If it doesn't, I'm happy to revisit this!)

2021-02-16 14:12 UTC, lieut-data commented on client/error_response.go
> +	return fmt.Sprintf("%v %v [%d]: %v", r.Method, r.URL, r.StatusCode, r.Err)
Good question: fixed!

2021-02-16 14:17 UTC, lieut-data commented on client/go.mod
> +	github.com/mattermost/mattermost-server/v5 v5.31.0
Ah, good catch -- I think this got upgraded in one of my many attempts at consolidation, but I didn't think to revisit the requirement. (It doesn't strictly hurt: in particular, we're still backwards compatible with v5.28.0 at an API level, but I'm also not opposed to just leaving the existing version intact.)

2021-02-16 14:18 UTC, lieut-data commented on client/incidents.go
> +	req, err := s.client.newRequest(http.MethodPost, incidentURL, opts)
I'm inclined to keep the client as thin as possible so as to give the server the maximum flexibility on required options, etc.

2021-02-16 14:20 UTC, lieut-data commented on server/api/api.go
> -
Indeed, sorry for the distraction here: I tried to pull out some of the potentially contentious changes into discrete PRs, but didn't want to rebase this one.

2021-02-16 14:21 UTC, lieut-data commented on client/unexport_test.go
> +var NewClient = newClient
This is "Go magic" -- all `_test.go` files are unconditionally excluded from the exposed API, even if they otherwise define what would be public methods and such. But they *are* used when running tests. By exploiting this, and putting this particular file into the `client` package, I can access the internals that are `newClient` and `buildAPIURL` from the `client_test` package without exposing those to the rest of the world.

2021-02-16 14:23 UTC, lieut-data commented on server/api/api_test.go
> +}
Honestly, I wanted to just ignore the err altogether, given it's not strictly relevant to the scope of the tests. But the linter wouldn't let me, so I just panicked instead. I'd prefer not to have to also pass around `* testing.T`, but I'm only 0/5 here.

2021-02-16 14:25 UTC, lieut-data commented on server/api/incidents_test.go
> -	t.Run("create invalid incident - channel id already set", func(t *testing.T) {
It is: the payload no longer accepts a `ChannelID` (since we no longer accept a "raw" incident).

2021-02-16 14:30 UTC, lieut-data commented
>     1. `Incident.Update` is not yet implemented. Is that intended?

Yep: mostly wanted to align on the structure before I spent too much time fleshing out the specifics.

>     2. I guess that the panic in the `to{API,Internal}Incident` functions is what makes the struct duplication safe, right?

By "safe", I'm assuming you mean as a defence against diverging? Now that you mention it, I recall our explicitly discussing a mechanism to ensure this but I forgot altogether to add that here. I think it's still viable to do that explicitly, but it's possible this code also guards against that by luck. I'd love to make this explicit in a subsequent PR either way.

>     3. There are a couple of things here from other PRs, if I'm not mistaken. Namely, the removal of the subscriptions and the context stuff in the API. Is that intended?

Indeed, apologies for the distraction: I didn't want to rebase this particular PR, but did want to get the meat of the changes out for consideration early.

>     4. Not for this PR, but worth discussing: `assert.Equal(t, testIncident, toInternalIncident(*resultIncident))` will fail if we ever decide to make the two structs (the one in the API and the normal one) diverge. Any plans for that?

Good point. I can see how we might want to explicitly diverge the public definition of an incident from the private one. Ok to cross that bridge if/when we hit it?

2021-02-23 10:03 UTC, agarciamontoro commented on client/incidents.go
> +	req, err := s.client.newRequest(http.MethodPost, incidentURL, opts)
It makes sense!

2021-02-23 10:05 UTC, agarciamontoro commented on client/unexport_test.go
> +var NewClient = newClient
Oooh, I see, that's clever! Thanks for the clarification!

2021-02-23 10:08 UTC, agarciamontoro commented on server/api/api_test.go
> +}
I think not ignoring it is a good thing, as we would otherwise let potential syncing problems between the types slip through. And I think t]at passing `*testing.T` is not too bad if that let us mark this semantically as a helper.

2021-02-23 10:08 UTC, agarciamontoro commented on server/api/incidents_test.go
> -	t.Run("create invalid incident - channel id already set", func(t *testing.T) {
Oooh, I see, thanks for the clarification!

2021-02-23 10:14 UTC, agarciamontoro commented
> By "safe", I'm assuming you mean as a defence against diverging? Now that you mention it, I recall our explicitly discussing a mechanism to ensure this but I forgot altogether to add that here. I think it's still viable to do that explicitly, but it's possible this code also guards against that by luck. I'd love to make this explicit in a subsequent PR either way.

Yes, that's what I meant! I think the key for that is in the `to{API,Internal}Incident` functions, which will fail when marshalling and unmarshalling the type if they are not the same. That's the only comment I left unresolved, as I think we can convert them into `t.Helper()`s so we can fail with a good error message explaining what happened. 0/5 doing that here or in subsequent PRs.

> Good point. I can see how we might want to explicitly diverge the public definition of an incident from the private one. Ok to cross that bridge if/when we hit it?

Absolutely!

2021-02-23 10:15 UTC, agarciamontoro approved these changes
Yay, this looks amazing :tada:

The comment on converting the `to{API,Internal}Incident` functions to helpers is non-blocking, so approving now!

2021-02-23 22:50 UTC, crspeller approved these changes

2021-02-25 14:18 UTC, lieut-data commented
Prapti, the bulk of this PR affects not the core product, but the updated Go client interface to streamline using the REST API. I'm not expecting that to be qualified, per se -- it's still under development and will continue to be versioned as "unstable" separate from the core product. Also, the unit tests already cover much of the requisite functionality. Nevertheless, I'd love a quick smoketest before merging to master.

2021-03-02 04:05 UTC, prapti approved these changes
Thank you for the context @lieut-data! That helped with understanding the testing expectations.
Smoke tested and verified that the plugin still works as intended and didn't come across anything that is 'broken'. 🎉 
Thank you for your contribution and patience on this @christian-lim!
Approving for merge!

2021-03-02 14:34 UTC, merged

2021-03-02 14:34 UTC, lieut-data commented
Thanks again, @christian-lim!