MM-31940 - RHS Timeline with status
mattermost/mattermost-plugin-incident-collaboration pull request #432
Opened 2021-01-21 14:36 UTC by cpoile

#### Summary
- V0 of the timeline, only showing status for now
- Based on #429 

Looks like: 
![image](https://user-images.githubusercontent.com/1490756/105364678-725b3200-5bcb-11eb-852d-1dcdab7e5a2a.png)

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-31940

2021-01-21 20:58 UTC, crspeller commented on webapp/src/components/rhs/rhs_timeline.tsx
> +        Promise.all(props.incident.status_posts.map(async (p) => {
This might generate multiple requests per entry in the timeline correct? 
Maybe we should make an endpoint that returns the appropriate data for the timeline. Might be nice as we expand the timeline to include more data. The downside is that it would have to assume the client doesn't have anything it requires.

2021-01-22 11:07 UTC, agarciamontoro requested changes
This is neat, I really like it! :tada:

My comments below are not blocking, but I tested this locally and I saw a couple of weird behaviours:
- When a status message is deleted, the whole timeline disappears after a refresh (maybe we need to filter out the deleted status posts?)
- In the previous case, or if there are no status updates at all (as in a brand new incident), the timeline renders a tiny bar:
![image](https://user-images.githubusercontent.com/3924815/105482274-70b36c00-5ca8-11eb-862b-03e76eabce03.png)
A simple solution for this would be to always have a first event in the timeline: the incident creation.

Another comment, but maybe for v0.1: could we remove the bar below the last event? I mean converting this:
![image](https://user-images.githubusercontent.com/3924815/105483146-b1f84b80-5ca9-11eb-9148-c83e0e7f89f1.png)
into this:
![image](https://user-images.githubusercontent.com/3924815/105483339-013e7c00-5caa-11eb-844e-97c3382acc71.png)
(maybe this a question for @alexsiclari)

2021-01-22 15:34 UTC, cpoile commented on webapp/src/components/rhs/rhs_timeline.tsx
> +                events.map((event) => {
Yep, that's better.

2021-01-22 15:35 UTC, cpoile commented on webapp/src/components/rhs/rhs_timeline.tsx
> +        Promise.all(props.incident.status_posts.map(async (p) => {
I would worry about it, but we're not going to be using this code for v2 -- we're going to send over a pre-populated list of Events from the server, so no client-side fetching will be needed. All this code in the `useEffect` will go away.

2021-01-22 15:42 UTC, cpoile commented on webapp/src/components/rhs/rhs_timeline.tsx
> +                    return Promise.reject(new Error('no post'));
Yep, that's a good idea, done.

2021-01-22 15:45 UTC, cpoile commented
@agarciamontoro Nice catch on the line when there was no status posts -- I never even noticed it on the light theme. I changed around how the rendering works, and I'm putting in a `Created` event now, so that fixes that problem.

I'm also adding the event types, which are the same as the ones I have in the v2 branch. v2 will send the event list as an array in the incident, it will always be up to date in the store.

2021-01-22 15:52 UTC, crspeller commented on webapp/src/components/rhs/rhs_timeline.tsx
> +        Promise.all(props.incident.status_posts.map(async (p) => {
Ok. If it's going away that's fine :D

2021-01-22 15:54 UTC, crspeller commented
> (funny--we currently don't record who created the incident anywhere :))

Not yet, but soon: https://github.com/mattermost/mattermost-plugin-incident-management/pull/430

2021-01-22 15:55 UTC, crspeller approved these changes

2021-01-22 16:15 UTC, agarciamontoro approved these changes
Great job here :tada:

2021-01-22 16:15 UTC, agarciamontoro commented on webapp/src/components/rhs/rhs_timeline.tsx
> +            setEvents(eventArray.filter((e) => e) as TimelineEvent[]);
Hm, does this filter out the nulls? I don't understand how it works.

2021-01-22 21:13 UTC, cpoile commented on webapp/src/components/rhs/rhs_timeline.tsx
> +            setEvents(eventArray.filter((e) => e) as TimelineEvent[]);
Yep, it filters everything that isn't null/undefined `(e) => e`

2021-01-25 16:14 UTC, agarciamontoro commented on webapp/src/components/rhs/rhs_timeline.tsx
> +            setEvents(eventArray.filter((e) => e) as TimelineEvent[]);
Oh god, it's crystal clear now... Friday evening is not a good time to review a PR.

2021-02-03 18:38 UTC, cpoile commented
/update-branch

2021-02-09 06:39 UTC, prapti approved these changes
Working great!
I've added and tested some 20 test cases relevant to the RHS Timeline in the Incident Collaboration test plan including tests for timeline event logs for incident creation, status update, change of commander, events as links to update-messages, event logging for reopened incidents and timestamp & duration verification, and all of them passed! 🎉  Couldn't break anything this time around.
The only thing I noticed that's worth mentioning is that when clicking on the timeline events to "jump" to the status update message, it takes noticeably longer for the page to load as opposed to clicking on permalinks. Is this a known issue?
Otherwise the rest looks great.

2021-02-09 14:51 UTC, cpoile commented
Thank you for the thorough review!

> The only thing I noticed that's worth mentioning is that when clicking on the timeline events to "jump" to the status update message, it takes noticeably longer for the page to load as opposed to clicking on permalinks. Is this a known issue?

@prapti Can you tell a difference in the time it takes to click on a timeline event and the time it takes to click on a status update timestamp (in the Summary tab)? It should be the same, since it's the same code. And the comparison is with a permalink to the same message in the same channel? (Just so I can try to repro)

2021-02-09 19:35 UTC, prapti commented
@cpoile I think the lag might be a server thing. It's not doing it on my local nor on cloud. I'll just keep an eye out to see if I see it again.

2021-02-09 21:07 UTC, cpoile commented
@prapti Awesome, please let me know if you see it again!

2021-02-09 21:07 UTC, merged