16401 archived immutable
mattermost/mattermost-plugin-incident-collaboration pull request #437
Opened 2021-01-24 21:51 UTC by arjunagl

#### Summary
If a channel is archived this PR will prevent users from making changes to that channel meta-data.  This includes changes to both the front and back end.

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/16401

2021-01-24 21:51 UTC, mattermod commented
Hello @arjunagl,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-01-25 15:12 UTC, lieut-data commented
@cpoile, can you give this a quick "still in draft" review to help guide @arjunagl?

2021-01-25 16:51 UTC, cpoile requested changes
Nice work @arjunagl ! 
I've left some comments below. Overall very nice job.

This was a good first step, thank you for making the effort to contribute!

2021-01-25 16:51 UTC, cpoile commented on server/api/incidents.go
>  	channelRouter := incidentsRouter.PathPrefix("/channel").Subrouter()
There are some routes below that would need a `channelActive` gate. You can probably put the entire `checklistItem` router behind a `.use(channelActive...` gate, since they are all modification routes.

2021-01-25 16:51 UTC, cpoile commented on webapp/src/components/profile/profile_selector.tsx
> +    }
I'm not sure if we can use this selector here, since we use the `ProfileSelector` component in the backstage, and if you move to the backstage while in an archived channel, the backstage's component will think it's still in an archived channel. Better to pass in a disabled prop, I think.

And I'm not sure if returning a `null` is the right thing -- is there a disabled state for a react-select component?

2021-01-25 16:51 UTC, cpoile commented on webapp/src/components/rhs/rhs_footer_summary.tsx
> +    return !isChannelArchived && (
I don't think we want to eliminate the rhs footer completely, we probably just want to set any interactive components to a grayed-out "disabled" state.

2021-01-25 16:51 UTC, cpoile commented on webapp/src/components/rhs/rhs_footer_tasks.tsx
> +// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
I think we've removed this component -- perhaps you were building on an older version of master?

2021-01-25 16:51 UTC, cpoile commented on webapp/src/components/rhs/rhs_incident_tasks.tsx
> +    const isChannelArchived = useSelector<GlobalState, boolean>(isCurrentChannelArchived);
Nice, I think this will work. Good idea. 🎉

2021-01-28 03:27 UTC, arjunagl commented on webapp/src/components/profile/profile_selector.tsx
> +    }
thanks, introduced a disabled property.

2021-01-28 03:27 UTC, arjunagl commented on webapp/src/components/rhs/rhs_footer_summary.tsx
> +    return !isChannelArchived && (
thanks, set the state to a disabled state.

2021-01-28 03:29 UTC, arjunagl commented on webapp/src/components/rhs/rhs_footer_tasks.tsx
> +// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
thanks, removed the component.

2021-02-01 05:00 UTC, arjunagl commented
@cpoile I keep getting the following on linting

`Property 'css' does not exist on type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'`

However I believe I did not introduce a change for this to err, any idea ?

2021-02-03 20:42 UTC, arjunagl commented on server/api/incidents.go
>  	channelRouter := incidentsRouter.PathPrefix("/channel").Subrouter()
thanks @cpoile changed as requested.

2021-02-12 15:49 UTC, cpoile commented
Hi @arjunagl ! I'm sorry, this got buried. Could you merge master and then I'll take a look at it asap? Thanks!

2021-02-14 22:16 UTC, arjunagl commented
> Hi @arjunagl ! I'm sorry, this got buried. Could you merge master and then I'll take a look at it asap? Thanks!

hi @cpoile no worries, merged with master.

2021-02-25 01:00 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2021-03-08 16:00 UTC, cpoile commented
/update-branch

2021-03-08 16:05 UTC, cpoile requested changes
One more comment, otherwise well done @arjunagl !
I'll request another dev review now and then we can get QA to review after that's finished. Thank you for your contribution!

2021-03-08 16:05 UTC, cpoile commented on webapp/src/components/profile/profile_selector.tsx
> +    disabled?: boolean
I can't seem to see where this prop is being used in the `profile_selector` file, am I missing it?

2021-03-09 15:10 UTC, crspeller requested changes
Nice! Just a few comments.

2021-03-09 15:10 UTC, crspeller commented on server/api/incidents.go
> +	return c.DeleteAt > 0, nil
Generally we check `c.DeleteAt != 0` Not that we would expect it to be negative :P

2021-03-09 15:10 UTC, crspeller commented on server/api/incidents.go
> +	checklistsRouter.Use(handler.checkChannelArchived)
The `incidnetRouterAuthorized` already included this, so I think it's redundant here.

2021-03-20 01:00 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2021-03-29 16:12 UTC, agarciamontoro commented
Hi @arjunagl, thank you for your work on this! Are you still interested in finishing this PR? Let us know if you can't!

2021-03-29 21:03 UTC, arjunagl commented
> Hi @arjunagl, thank you for your work on this! Are you still interested in finishing this PR? Let us know if you can't!

Hi, yes I'm working on this, sorry for the delay in getting back, got a bit carried away, will work on this during the weekend and merge.

2021-03-30 07:21 UTC, agarciamontoro commented
Great, thank you! No worries about the delay, I know life gets in the way.

2021-06-18 18:27 UTC, lieut-data commented
Thanks for your help here, @arjunagl! I've been making some changes that touch a ton of code and probably make it easier to start on this PR from scratch. I'm going to close the PR for now and re-open the issue, but feel free to ping me if you're still interested!

2021-06-18 18:27 UTC, closed without merging