MM-32094 - Backend for Timeline v1 standard events and custom events
mattermost/mattermost-plugin-incident-collaboration pull request #447
Opened 2021-02-01 21:37 UTC by cpoile

#### Summary
- This should be able to support all standard (built-in) events, and custom events (manually entered)
- Built-in events are saved in the incident service when they happen
- Working on the frontend next, so some of this might change depending on what that needs.
- Assuming we'll be fine to display markdown in a simple div, we'll see.
- Assuming the `Details` field will be filled with the details of the event when the user enters a custom event (see figma designs: https://www.figma.com/file/XeYHk47Mn3nuDf0e00CVGZ/MM---32021?node-id=5%3A64).
- Tests will be more comprehensive on the frontend -- here they're just making sure the SQL works as expected. If you can think of anything I should test here, feel free to suggest and I'll add them!

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-32094

2021-02-01 21:40 UTC, cpoile commented on server/sqlstore/incident.go
> +func (s *incidentStore) UpdateTimelineEvent(event incident.TimelineEvent) error {
For now I imagine this will mostly be used to remove a timeline event. But when we add the ability to edit events probably everything is fair game.

2021-02-01 21:41 UTC, cpoile commented on server/sqlstore/migrations.go
> +		toVersion:   semver.MustParse("0.7.0"),
`toVesion: "Diplodocus"`

2021-02-02 14:01 UTC, lieut-data requested changes
Really slick! Just a handful of thought below :)

2021-02-02 17:09 UTC, crspeller requested changes
This looks good! Just one suggestion for a possible simplification.

2021-02-02 17:09 UTC, crspeller commented on server/incident/service.go
> +	if _, err = s.store.CreateTimelineEvent(event); err != nil {
This entry has all the same information as the status post, except what the status was update to. Would it make sense to just include that in the timeline event and query the timeline event table for the status updates? It would simplify the code greatly.

2021-02-03 19:39 UTC, cpoile commented on server/incident/incident.go
> +	var newTimelineEvents []TimelineEvent
Done! (with `[]StatusPost(nil)` so it doesn't break our tests)

2021-02-03 19:40 UTC, cpoile commented on server/incident/incident.go
> +	EventType  timelineEvent `json:"event_type"`
Yep, exactly. We'll add that when we need it. Maybe with more specific event types than just "custom", but probably custom to start.

2021-02-03 19:40 UTC, cpoile commented on server/incident/incident.go
> +	UserID     string        `json:"user_id"`
Not necessarily. It's more like a `SubjectUserID`, the subject of the event. The user who created the event (in the case of a custom event type) could be a different user. We should track the `CreatorUserID` too, and may as well add that now to keep the migration as clean as possible.
I'll change this to `SubjectUserID` to disambiguate it

2021-02-03 19:40 UTC, cpoile commented on server/incident/incident.go
> +	CreateTimelineEvent(event TimelineEvent) (string, error)
I was trying something new, should have changed it back. I do kind of want to stop returning a pointer in these functions (why bother, when the id is the only thing that was added, and the change is reflected in the change to the parameter pointer). But I've changed it back for consistency with how we currently do things.

2021-02-03 19:40 UTC, cpoile commented on server/incident/incident.go
> +	CreateAt   int64         `json:"create_at"`
Good idea!

2021-02-03 19:40 UTC, cpoile commented on server/incident/service.go
> +		CreateAt:   model.GetMillis(),
Good idea. I did it where we have a timestamp saved somewhere else. Otherwise I'm creating one for the `CreateAt` and `EventAt` times, so they're consistent.

2021-02-03 19:40 UTC, cpoile commented on server/sqlstore/incident.go
> +		Where(sq.Eq{"te.IncidentID": incidentIDs})
Yep, good idea. When we remove an event on the front end, we'll make an api call to do that, and then we'll probably send an updated incident (which would include that incident's events, minus the one that was just deleted). I think that's better than having any sorting or filtering done on the front-end.

2021-02-03 19:43 UTC, cpoile commented on server/incident/service.go
> +	if _, err = s.store.CreateTimelineEvent(event); err != nil {
Good idea: https://mattermost.atlassian.net/browse/MM-32578

2021-02-03 19:44 UTC, crspeller approved these changes

2021-02-03 19:44 UTC, cpoile commented on server/incident/incident.go
> +	UserID     string        `json:"user_id"`
More context: on the frontend we want to respect the username display settings, and events almost always talk about someone doing something. The `SubjectUserID` is for that.

2021-02-03 19:48 UTC, lieut-data approved these changes
Sweet! (Two non-blocking nits below.)

2021-02-03 19:48 UTC, lieut-data commented on server/incident/service.go
> +	eventTime := model.GetMillis()
nit: Could we use the time from the "modification message" post?

2021-02-03 19:48 UTC, lieut-data commented on server/sqlstore/migrations.go
> +                        SubjectUserID VARCHAR(26)   NOT NULL DEFAULT '',
nit: indentation here seems off?

2021-02-04 17:46 UTC, lieut-data approved these changes

2021-02-08 18:34 UTC, merged

2021-02-08 18:49 UTC, cpoile commented
To be QA tested in #432