added newid if pure multibyte character set
mattermost/mattermost-plugin-incident-collaboration pull request #457
Opened 2021-02-05 04:21 UTC by arjunagl

#### Summary
If the incident name has only multibyte characters its does not create the channel, this change will create a new id and it will allow channel creation.

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/16834#event-4282247227

2021-02-05 04:21 UTC, mattermod commented
Hello @arjunagl,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-02-05 14:17 UTC, lieut-data requested changes
This looks great, @arjunagl! Can you help us test this my updating the unit tests with a case that covers this path? 

If you're feeling really adventurous, you can even try your hand at an e2e test that programmatically tests this from the frontend as well.

2021-02-12 01:57 UTC, arjunagl commented
thanks @lieut-data, I have included an unit test as well into the .go code.

2021-02-16 18:15 UTC, agarciamontoro approved these changes
Thank you for your contribution,@arjunagl :tada:

The code looks good to me! I'd love to see an E2E test (I explained my specific concerns on the mocking below), but I'm approving it because it does solve the bug.

Thank you!

2021-02-16 18:15 UTC, agarciamontoro commented on server/incident/service_test.go
> +		})).Return(&model.Channel{Id: "channel_id"}, nil)
I'm a bit concerned about this part because this is exactly what we want to test, and mocking it kind of bypasses that. I see no other way of testing it, though, and at least we check that the function is called with the correct parameters (a channel with a non-empty name).

2021-02-16 18:26 UTC, lieut-data approved these changes
I think this makes sense -- thanks again, @arjunagl!

@prapti, this one could use an e2e test for full coverage. Is this something you might be able to take a stab at helping write for added coverage? (No immediate hurry :))

2021-02-16 18:26 UTC, lieut-data commented on server/incident/service_test.go
> +		})).Return(&model.Channel{Id: "channel_id"}, nil)
Maybe if we assert `model.IsValidId` here to verify?

2021-02-16 18:29 UTC, agarciamontoro commented on server/incident/service_test.go
> +		})).Return(&model.Channel{Id: "channel_id"}, nil)
That's a good idea!

2021-02-23 06:49 UTC, prapti approved these changes
Thank you for your contribution on this @arjunagl! I have tested and verified that your solution works great!
Approving to merge 🎉

2021-02-23 13:52 UTC, merged

2021-02-23 13:53 UTC, lieut-data commented
Just a heads up that this change may find an edge case in the bug filed over at https://mattermost.atlassian.net/browse/MM-32912, but it's something for the Web Platform team to investigate.