MM-32547 - Remove any event from Timeline
mattermost/mattermost-plugin-incident-collaboration pull request #468
Opened 2021-02-12 19:32 UTC by cpoile

#### Summary
- Can remove any event from the timeline
- Looks like:
![image](https://user-images.githubusercontent.com/1490756/107813730-d55d6600-6d3e-11eb-8e74-812ea017ef1f.png)
![image](https://user-images.githubusercontent.com/1490756/107813757-db534700-6d3e-11eb-8caf-2b34ac4ecb49.png)

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-32547

2021-02-12 19:39 UTC, crspeller approved these changes
Nice! One non-blocking

2021-02-12 19:39 UTC, crspeller commented on webapp/src/components/rhs/rhs_timeline_event_item.tsx
> +const HoverMenu = styled.div`
Should we share this? So when we get a new design we don't have to change it in multiple places?

2021-02-12 19:40 UTC, cpoile commented on webapp/src/components/rhs/rhs_timeline_event_item.tsx
> +const HoverMenu = styled.div`
I thought about it, but I wasn't sure if we wanted to make changes specific to just this (if I'm asked to from UI)... But, yah, let's worry about that if/when it happens. Will moved it to shared.

2021-02-12 19:46 UTC, cpoile commented on webapp/src/components/rhs/rhs_timeline_event_item.tsx
> +const HoverMenu = styled.div`
Done, thanks!

2021-02-15 09:17 UTC, agarciamontoro requested changes
Nice! :tada: The only thing I'm missing is the update of the API docs.

2021-02-15 09:17 UTC, agarciamontoro commented on server/api/incidents.go
> +func (h *IncidentHandler) removeTimelineEvent(w http.ResponseWriter, r *http.Request) {
We should probably update the api.yaml with this one

2021-02-17 19:03 UTC, cpoile commented on server/api/incidents.go
> +func (h *IncidentHandler) removeTimelineEvent(w http.ResponseWriter, r *http.Request) {
Good call, added. Thanks!

2021-02-18 10:33 UTC, agarciamontoro approved these changes
Great, thanks!

2021-02-23 06:27 UTC, prapti approved these changes
Tested and verified that removing the incident from timeline works as expected. LGTM!
Added the following tests:
1. Hovering over timeline event shows a delete hover button
2. Clicking on delete hover button shows a “Confirm Entry Delete” confirmation dialog
3. Clicking “Cancel” in “Confirm Entry Delete” confirmation dialog does not delete the timeline event
4. Clicking “Delete Entry” in “Confirm Entry Delete” confirmation dialog deletes the timeline event
5. Timeline event can be deleted by any incident channel member
6. A guest user can delete a timeline event (this will need to be tested later)

2021-02-23 19:51 UTC, merged