MM-32387: activate but functionally disable without license
mattermost/mattermost-plugin-incident-collaboration pull request #469
Opened 2021-02-12 19:39 UTC by lieut-data

#### Summary
Allow incident collaboration to start without a valid E20 license, but disable all user facing functionality (including the REST API and slash commands) until a license is installed. Dynamically transition across any license changes.

To make this work, I had to pull in the store functionality from the pluginapi and remove the built-in license check there (since I wanted to start up the store without a valid license in place). We should consider revisiting this artificial limitation, but for now I've at least put that in a separate commit.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-32387

2021-02-12 19:44 UTC, lieut-data commented on go.mod
> +	github.com/go-sql-driver/mysql v1.5.0
These are being pulled in as a result of incorporating the pluginapi's store support.

2021-02-12 19:44 UTC, lieut-data commented on plugin.json
> +        "header": "Incident Collaboration requires a Mattermost Cloud or Mattermost E20 License.",
Just in case someone is confused in the system console.

2021-02-12 19:44 UTC, lieut-data commented on server/sqlstore/database.go
> +package sqlstore
This is a lightly modified version pulled from the pluginapi.

2021-02-12 19:44 UTC, lieut-data commented on server/sqlstore/unexport_test.go
> +var NewDatabase = newDatabase
Let me use `NewDatabase` from `sqlstore_test` without actually exporting it (`_test.go` files are unconditionally ignored.)

2021-02-12 19:44 UTC, lieut-data commented on webapp/src/index.tsx
>          const updateMainMenuAction = () => {
Kept this section discrete since it has special handling.

2021-02-12 19:44 UTC, lieut-data commented
Lastly, I discussed this briefly with @prapti, but I don't know how to e2e test this given the current licensing architecture -- we don't seem to have any tests that remove/add as such.

2021-02-12 20:32 UTC, cpoile approved these changes

2021-02-12 20:32 UTC, cpoile commented on server/api/incidents_test.go
> +		retI.ChannelID = "channelID"
Not sure if we need these, right?

2021-02-12 20:32 UTC, cpoile commented on server/sqlstore/database.go
> +package sqlstore
Not reviewing it too closely then. :)

2021-02-12 20:32 UTC, cpoile commented on webapp/src/registry_wrapper.tsx
> +// RegistryWrapper intercepts component and event handling registrations with the WebApp
This is awesome.

2021-02-16 14:38 UTC, lieut-data commented on server/api/incidents_test.go
> +		retI.ChannelID = "channelID"
Good catch! Fixed :)

2021-02-16 20:07 UTC, crspeller requested changes

2021-02-16 20:41 UTC, lieut-data commented on server/command/command.go
> +	if !r.configService.IsLicensed() {
It's not my ideal experience, but it turns out there is no event telling plugins when the license changes, so there's no simply way to make this come back automatically. I /think/ it's close enough for now, but defer to @itao.

2021-02-16 20:41 UTC, lieut-data commented on server/sqlstore/database.go
> +type database struct {
That's reasonable -- I'll try to drive that, but it may require "upstream approval".

2021-02-16 20:46 UTC, lieut-data commented on server/sqlstore/database.go
> +type database struct {
Raised over at https://community.mattermost.com/core/pl/3akxk61ebjfqmbbh588pn5mrjr

2021-02-23 17:20 UTC, lieut-data commented
@itao, can I get your eyes on the proposed changes here? I'd like to get buy-in before asking for a second developer review just to avoid thrashing.

2021-02-23 19:23 UTC, itao approved these changes
Thanks for the ping @lieut-data, I read through the Jira ticket and this approach seems fine to me.

2021-02-23 22:49 UTC, crspeller approved these changes

2021-02-24 02:07 UTC, prapti commented
@lieut-data Not The plugin built from this branch works normally with all the UI functionalities available both on TE and E0 locally; I was thinking that even though it can get installed and enabled without error, the functionalities should not be available to users. Wondering if I understood it correctly?

2021-02-24 10:13 UTC, lieut-data commented
No, you definitely understood the intent correctly. That's very odd: let me take a double look to see what's gone (horribly) wrong! :)

2021-02-25 16:12 UTC, lieut-data commented
@prapti, a few updates. First, I merged master and pushed a change to depend on the formal `mattermost-plugin-api` that's since been updated to not enforce the E20 check on connecting to the store. This, however, is unrelated to your observation.

I was able to partially reproduce what you describe. For TE, I ran `BUILD_ENTERPRISE=false BUILD_ENTERPRISE_READY=false make run-server` and discovered that the existing license is still loaded, even though the `enterprise` code is not present to do anything advanced. So it seems possible to put TE into a semi-licensed state, which incident response honours. I'm unsure if we should do anything here, since the license is present and valid and we don't actually depend on anything enterprise-specific at that point.

But for both TE with the license removed, and E0 with the license removed, the plugin behaves as advertised: disabling itself when the license is not present on startup (or removed thereafter), and enabling otherwise. Can you help me reproduce the symptoms you were originally describing?

2021-03-02 01:25 UTC, prapti reviewed
@lieut-data It is looking much better now. I can't reproduce the issue I was seeing last week. However, TE (running locally as you mentioned) did show this error when trying to activate: `"Unable to activate plugin","plugin_id":"com.mattermost.plugin-incident-management","error":"a valid Mattermost Enterprise E20 license is required to use this plugin"`. I can see this happening in this server too although this server is more of an E0 than TE: https://ic-te.test.mattermost.cloud/
One other thing I noticed too was that, although the rest of the features are not available as expected, the `/incident` slash commands are still available
![Screen Shot 2021-03-01 at 4 12 06 PM](https://user-images.githubusercontent.com/691331/109582430-0239a900-7ab3-11eb-8e6a-69411f5af4da.png)

2021-03-02 13:09 UTC, lieut-data commented
Thanks, @prapti -- let's plan to chat through this one later today as I bet there's still a mismatch between my environment and yours, and I want to get to the bottom of that to make sure we've covered the cases here.

2021-03-04 20:56 UTC, prapti approved these changes
Thank you for taking a deeper look into this today @lieut-data. I tested again on a fresh server and can verify that there is no such issues that I had mentioned earlier. The plugin features stay hidden (except for the slash commands) in servers that don't have license but activate without any issue. The features turn on seamlessly when an E20 license is provided, or migrated from E0 or E10 to E20.
Approving.

2021-03-04 22:06 UTC, merged