MM-33439: Fetch invited users independently
mattermost/mattermost-plugin-incident-collaboration pull request #486
Opened 2021-03-03 17:37 UTC by agarciamontoro

#### Summary
The component was filtering the invited members out of the list that is fetched when the component is mounted. This list is capped at 100 users (the default for Client4.getUsers), so if the invited member was not originally there, it was not shown in the component.

This PR fixes the bug by pre-fetching all the invited members. In particular:
1. Fetch all the invited members on component mount.
2. If the user has not typed anything in the search box, just pass the fetched members to react-select as the group of invited members. All the invited members will be there.
3. If the user has typed something in the search box, rely on the server-side filtering. This is the tricky part: if there are more than 100 hits for your search term, it is possible that the invited member is still lost, but this also happens with non-invited members. The alternative is to do the filtering client-side, but I took a look at the filtering on the server side to try and replicate it and it's quite complex: we're filtering not only by username, but also by the first and last name, and I am sure t]at if we try to replicate that here, it will come back to bite us. That's why I decided it was an acceptable trade-off to rely on the server filtering in this case.

This is a working fix for this dot release, but we still need something more robust for the future (for example, we don't even have pagination in the fetching of the users). I added this to my now long list of things I want to tackle as part of https://mattermost.atlassian.net/browse/MM-32861

About the release itself: I created a branch from the v1.5.1 tag, release-v1.5.2, which is the base for this PR. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-33439

2021-03-03 17:42 UTC, agarciamontoro commented on webapp/src/components/backstage/automation/invite_users_selector.tsx
> +    }, [props.userIds, searchTerm, JSON.stringify(invitedUsers)]);
If using the raw array, the component enters a loop where this effect is called infinitely. This is because even though the contents are the same, the array is changing. I am relying on this stringify call, as stated in https://github.com/facebook/react/issues/14476#issuecomment-471199055

2021-03-03 17:45 UTC, agarciamontoro commented on webapp/src/components/backstage/automation/invite_users_selector.tsx
> +    }, [props.userIds, searchTerm, JSON.stringify(invitedUsers)]);
(if you have other ideas on how to approach this, please tell me so!)

2021-03-03 17:54 UTC, lieut-data requested changes
Good catch, @agarciamontoro! A few thoughts below.

2021-03-03 17:54 UTC, lieut-data commented on webapp/src/components/backstage/automation/invite_users_selector.tsx
> +                    invitedProfiles = invitedUsers.filter((user) => user);
This appears to just copy `invitedUsers`? Should we make that more explicit with:
```suggestion
                    invitedProfiles = [...invitedUsers];
```

2021-03-03 17:54 UTC, lieut-data commented on webapp/src/components/backstage/automation/invite_users_selector.tsx
> +                        (profile: UserProfile) => !props.userIds.includes(profile.id),
Just a caution that this is `O(n^2)` in terms of the number of invited users. /Probably/ not an issue, but just want to make sure it's expected that the list stays relatively small.

2021-03-03 17:54 UTC, lieut-data commented on webapp/src/components/backstage/automation/invite_users_selector.tsx
> +    }, [props.userIds, searchTerm, JSON.stringify(invitedUsers)]);
Could we avoid the dependency by having the effect maintain a set of `searchedUsers` and then just compute `invitedProfiles` and `nonInvitedProfiles` for each render from the available data?

2021-03-03 17:54 UTC, lieut-data commented on webapp/src/components/backstage/automation/invite_users_selector.tsx
> +                dispatch(fetchUser(props.userIds[idx]));
To avoid a future problem, is there a convenient `fetchUsers` we could use instead?

2021-03-03 17:55 UTC, agarciamontoro commented on webapp/src/components/backstage/automation/invite_users_selector.tsx
> +                    invitedProfiles = invitedUsers.filter((user) => user);
I'm filtering out the undefined ones! We can make it more explicit with `user !== undefined`, if you want to.

2021-03-03 17:59 UTC, agarciamontoro commented on webapp/src/components/backstage/automation/invite_users_selector.tsx
> +                dispatch(fetchUser(props.userIds[idx]));
Oh there is a getProfilesByIds, I'll check if it does what it says.

2021-03-03 18:03 UTC, agarciamontoro commented on webapp/src/components/backstage/automation/invite_users_selector.tsx
> +    }, [props.userIds, searchTerm, JSON.stringify(invitedUsers)]);
But we still need to depend on the list of invitedUsers being updated when the invited users are finally fetched, right? Maybe I misunderstood your proposal here.

2021-03-03 18:08 UTC, agarciamontoro commented on webapp/src/components/backstage/automation/invite_users_selector.tsx
> +                        (profile: UserProfile) => !props.userIds.includes(profile.id),
It is, but I cannot think of a simple way to reduce the complexity here. For every member in the list, we need to decide if it is invited or not.

2021-03-03 18:54 UTC, agarciamontoro commented on webapp/src/components/backstage/automation/invite_users_selector.tsx
> +                dispatch(fetchUser(props.userIds[idx]));
It does!

2021-03-03 18:56 UTC, agarciamontoro commented on webapp/src/components/backstage/automation/invite_users_selector.tsx
> +                    invitedProfiles = invitedUsers.filter((user) => user);
Typescript complains about using undefined. I see even more confusing to add a typescript ignore comment, so I let it as it was. The other cool option is doing `invitedUsers.filter(Boolean)` :sunglasses: But I see that it's equally confusing.

2021-03-03 18:56 UTC, agarciamontoro commented
@lieut-data, addressed one (1) of your comments, I replied to the other ones in place to follow the conversation.

2021-03-03 20:17 UTC, cpoile requested changes
Nice catch! This is a tricky one for sure. 

Not sure if the comment I gave will help or not, but let me know.

2021-03-03 20:17 UTC, cpoile commented on webapp/src/components/backstage/automation/invite_users_selector.tsx
> +    }, [props.userIds]);
Inside here, for example. Turn `invitedUsers` into a state hook above, and fill them inside this effect hook.

2021-03-03 20:17 UTC, cpoile commented on webapp/src/components/backstage/automation/invite_users_selector.tsx
> +                    invitedProfiles = invitedUsers.filter((user) => user);
The `(u) => u` is fine by me (we do a similar filtering elsewhere in the code). Maybe leave a comment for future us who won't remember this idiom? :)

2021-03-04 09:42 UTC, agarciamontoro commented on webapp/src/components/backstage/automation/invite_users_selector.tsx
> +    const invitedUsers = useSelector<GlobalState, UserProfile[]>((state: GlobalState) => props.userIds.map((id) => getUser(state, id)));
I vaguely remember this discussion in other parts of the codebase, but not the specifics on what caused the re-renders.

I took a look at the docs and, according to [this](https://react-redux.js.org/api/hooks#equality-comparisons-and-updates), the component will re-render only if the returned object is different (as in `===` returning false). It's true that the selector is executed with every change in the state, but the reason for the re-render in this specific case would be that `invitedUsers` changes. As `invitedUseres` is an array that gets created every time the selector is executed, it will definitely re-render, but it looks like we can prevent that by using a custom comparison operator, such as `shallowEqual` from `react-redux`

2021-03-04 10:08 UTC, agarciamontoro commented on webapp/src/components/backstage/automation/invite_users_selector.tsx
> +    const invitedUsers = useSelector<GlobalState, UserProfile[]>((state: GlobalState) => props.userIds.map((id) => getUser(state, id)));
Or maybe not: https://github.com/reduxjs/react-redux/issues/1654 I don't get it

2021-03-04 10:32 UTC, agarciamontoro commented on webapp/src/components/backstage/automation/invite_users_selector.tsx
> +    const invitedUsers = useSelector<GlobalState, UserProfile[]>((state: GlobalState) => props.userIds.map((id) => getUser(state, id)));
Anyway, I tested this with the paint flashing tool and I am not able to reproduce what you say. The component does not re-render when I make changes to the store (I tried removing a user, creating a new channel, inviting the user that has the backstage open to a new channel and then kicking them, and posting messages in channels where the user is). 
In none of the cases did I get a repaint, so I guess it is not being re-rendered. Maybe I'm missing something else here, of course.

2021-03-04 10:35 UTC, agarciamontoro commented on webapp/src/components/backstage/automation/invite_users_selector.tsx
> +                    invitedProfiles = invitedUsers.filter((user) => user);
Added a comment in https://github.com/mattermost/mattermost-plugin-incident-collaboration/pull/486/commits/5d0531150a2484814bde10fc027b0f61a0db7e72, resolving this one!

2021-03-04 10:45 UTC, agarciamontoro commented on webapp/src/components/backstage/automation/invite_users_selector.tsx
> +    }, [props.userIds, searchTerm, JSON.stringify(invitedUsers)]);
I think I know now what you mean, let me push a new commit with this.

2021-03-04 11:18 UTC, agarciamontoro commented
I've simplified the useEffect hook by moving all the logic to build the `options` outside of it, so the dependency on the invitedUsers is implicit. I empirically checked that there is no re-painting happening, but another look into that would be appreciated, as I still don't understand it completely, I think.

2021-03-04 12:45 UTC, lieut-data commented on webapp/src/components/backstage/automation/invite_users_selector.tsx
> +                        (profile: UserProfile) => !props.userIds.includes(profile.id),
One way out would be to convert the individual lookups to `O(1)` using a dictionary, but I suspect that's not necessary at this time.

2021-03-04 13:04 UTC, lieut-data commented on webapp/src/components/backstage/automation/invite_users_selector.tsx
> +    const invitedUsers = useSelector<GlobalState, UserProfile[]>((state: GlobalState) => props.userIds.map((id) => getUser(state, id)));
I don't think the issue is the inability to track the selector's dependencies -- Redux always calls all `mapStateToProps` every time the store changes -- but the fact that this selector always returns a new array even if the underlying conditions haven't changed:
```js
const userIds = ['userid1', 'userid2', 'userid3'];
getUser = (userId) => userId;

const call1 = userIds.map((id) => getUser(id));
const call2 = userIds.map((id) => getUser(id));

// returns false
console.log(call1 === call2);
```

Redux selectors are /supposed/ to be pure, so I think the pattern above will unconditionally trigger React's "render" phase whenever anything in the state changes. However, React won't actually render anything new to the DOM, since the output of this function will be the same as before. This does come at a cost, however, over skipping the render phase altogether.

I add this comment not that I think we necessarily need to touch anything here -- I see this as a low-bandwidth page whose components won't be mounted very often -- but just to share what I imagine is going on under the covers.

2021-03-04 13:05 UTC, lieut-data commented on webapp/src/components/backstage/automation/invite_users_selector.tsx
> +    }, [props.userIds]);
I /think/ this is perhaps an anti-pattern, having a component juggle second-order state like this. If this is a concern, perhaps we could introduced a memoized selector instead?

2021-03-04 13:06 UTC, lieut-data approved these changes
Nice simplifications, @agarciamontoro!

2021-03-04 14:39 UTC, agarciamontoro commented on webapp/src/components/backstage/automation/invite_users_selector.tsx
> +    const invitedUsers = useSelector<GlobalState, UserProfile[]>((state: GlobalState) => props.userIds.map((id) => getUser(state, id)));
Thank you for the insight! That's what I thought, but it's true that checking the repainting is not enough to test that the rendering phase is triggered again. Is there any easy way to test that? (just for the sake of knowing it for the future)

2021-03-04 14:41 UTC, agarciamontoro commented on webapp/src/components/backstage/automation/invite_users_selector.tsx
> +    const invitedUsers = useSelector<GlobalState, UserProfile[]>((state: GlobalState) => props.userIds.map((id) => getUser(state, id)));
But I still don't get why the issue I linked before is like that: even when using a custom comparison function, the reload is triggered (the useEffect hook in the example in the issue).

2021-03-04 15:36 UTC, agarciamontoro commented on webapp/src/components/backstage/automation/invite_users_selector.tsx
> +    }, [props.userIds, searchTerm, JSON.stringify(invitedUsers)]);
Done in https://github.com/mattermost/mattermost-plugin-incident-collaboration/pull/486/commits/5b7f98c04c4b89ee3f0923925e364014d3071ee6.

2021-03-04 15:37 UTC, agarciamontoro commented on webapp/src/components/backstage/automation/invite_users_selector.tsx
> +                        (profile: UserProfile) => !props.userIds.includes(profile.id),
That's a good point, and an obvious one, actually (note to self: not think about complexity after 7 pm). I'll check if it's a good addition when doing the merge of the components, thanks!

2021-03-04 19:13 UTC, cpoile commented on webapp/src/components/backstage/automation/invite_users_selector.tsx
> +    const invitedUsers = useSelector<GlobalState, UserProfile[]>((state: GlobalState) => props.userIds.map((id) => getUser(state, id)));
Hmm, this is an interesting issue... Definitely we're good to go for this fix, but I really want to know what's going on under the hood here. Wonder if we should have webapp (or someone from our team) do a deep dive and then a bit of a presentation (a brown bag?) to the rest of the dev team

2021-03-04 19:14 UTC, cpoile approved these changes
Nice, thanks @agarciamontoro !

2021-03-04 19:16 UTC, agarciamontoro commented on webapp/src/components/backstage/automation/invite_users_selector.tsx
> +    const invitedUsers = useSelector<GlobalState, UserProfile[]>((state: GlobalState) => props.userIds.map((id) => getUser(state, id)));
I've been wanting to do that for a while (also for the sake of my understanding, because I feel like I lack some knowledge on the low level aspects of react and redux)

2021-03-04 20:05 UTC, lieut-data commented on webapp/src/components/backstage/automation/invite_users_selector.tsx
> +    const invitedUsers = useSelector<GlobalState, UserProfile[]>((state: GlobalState) => props.userIds.map((id) => getUser(state, id)));
I might be mistaken, but I think you can just `console.log` within the functional component. If it's called, that's React's "render" phase. But React reserves the right to render at any time, so it's not a bug to have it render more than strictly necessary.

A deep dive here would be awesome!

2021-03-04 21:37 UTC, prapti approved these changes
Tested and verified that invited members and non-invited members still work as expected.
Approving.

2021-03-04 21:53 UTC, merged