MM-33408 Basic Stats View
mattermost/mattermost-plugin-incident-collaboration pull request #489
Opened 2021-03-09 14:43 UTC by crspeller

#### Summary
Basic statistics view. 
Single number stats included:
- The number of incidents in the reported state (clicking on this one opens incident list filtered by reported)
- The number of incidents in the active state (clicking on this on opens incident list filtered by active)
- The number of unique people in incident channels right now
- The average duration of incidents that are currently active (not resolved or archived)

Graphs included:
- The number of incidents that where active at any time on each day.
- The number of people currently in incidents that where created on each day.
- The average reported to active time for incidents created on each day
- The average reported to resolved time for incidents created on each day

"each day" begins at the current instant and are the 24 hour periods preceding regardless of day boundaries in the current time zone. 

This data is created using SQL queries on our existing data. Efficiency of these queries has not been looked at closely. `UniquePeopleInIncidents` is especially bad as it has to make separate queries for each day. 

If this expands, we may want to look into keeping this data as a time series rather than using these queries.

#### UI Screenshot
![Screenshot_2021-03-09 Mattermost](https://user-images.githubusercontent.com/3191642/110485360-64d90900-80a0-11eb-92f7-7f5123589a7d.png)

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-33408

2021-03-09 15:32 UTC, crspeller commented
@itao Updated with your text changes except the `Stats` vs `Dashboard` one. Waiting on @alexsiclari 

We could totally include one. Make a ticket including the text you want.

2021-03-09 16:15 UTC, crspeller commented
> Total Incidents per day and total participants per day is showing a high total when it may not be that actual high of an amount.

@alexsiclari That data is correct for my test server.

2021-03-09 16:40 UTC, itao commented
> Total Incidents per day and total participants per day is showing a high total when it may not be that actual high of an amount.

I think @alexsiclari meant the chart give the impression that the an alarmingly high number of people (ie. 100% of employees) are stuck in incidents. Please correct me if that's not the case.

@alexsiclari Could you provide guidance on the visualization as well as fit and polish with a high fidelity screenshot?

2021-03-12 21:01 UTC, cpoile commented
@crspeller Should we wait until iterating on design is finished before code review?

2021-03-12 21:02 UTC, crspeller commented
@cpoile No, this is ready for dev review. Polish can come in another PR.

2021-03-12 22:29 UTC, cpoile requested changes
Nothing really major, just suggestions and a few questions. Nice work!

2021-03-12 22:29 UTC, cpoile commented on server/sqlstore/stats.go
> +// Inefficent. Calculates the number of people in the incident using
For these queries, do we have any idea /how/ inefficient they are? They could be "bad" but not bad enough to worry about, considering we're not going to be running them that often. Or the could be really bad, and then we should just cache them. Just from eyeballing I can't tell, but it doesn't seem that horrible...

2021-03-12 22:29 UTC, cpoile commented on webapp/src/components/backstage/incidents/incident_list/incident_list.tsx
> +            status = queryForStatus;
`const status = queryForStatus | undefined`?

2021-03-12 22:29 UTC, cpoile commented on webapp/src/components/backstage/incidents/incident_list/incident_list.tsx
> +        };
ah, forgot about that. Probably got a "not mounted" react error, right?

2021-03-12 22:29 UTC, cpoile commented on webapp/src/components/backstage/stats.tsx
> +            <div className='total-count'>
Why not styled components (for this, and a lot of below)?

2021-03-12 22:29 UTC, cpoile commented on webapp/src/components/backstage/stats.tsx
> +                    <GraphBox>
Would it clean things up if we made a `GraphBox` FC? (similar to the `StatisticCount`)

2021-03-15 13:54 UTC, lieut-data requested changes
A handful of thoughts and comments -- I think the biggest win here in terms of performance is to minimize joins to any of `Channels`, `Posts` or `ChannelMembers`, and then only on indexed fields (like `Id`).

I'd love to do a second pass after we decide on next steps here.

2021-03-15 13:54 UTC, lieut-data commented on server/sqlstore/stats.go
> +		return []int{}
nit: `return nil` instead?

2021-03-15 13:54 UTC, lieut-data commented on server/sqlstore/stats.go
> +// Inefficent. Calculates the number of people in the incident using
If we can avoid using any fields from the `channel` table /except/ for the `Id`, I think I'm ok with this approach -- running the queries 14 times is suboptimal, but bounded.

The chief problem I'm worried about is a table scan, but if we can rely on just using the indexes instead, we should be fine.

2021-03-15 13:54 UTC, lieut-data commented on server/sqlstore/stats.go
> +		Select(fmt.Sprintf("COUNT(i.Id), (%v - c.CreateAt) / 86400000 as DayStarted", now)).
Also, I commented about this below, but let's avoid using `c.*` except for the `Id` to avoid the inevitable table scan.

2021-03-15 13:54 UTC, lieut-data commented on server/sqlstore/stats.go
> +// Average times from CreateAt to the first non reported update for the last number of days.
It wasn't obvious what `non-reported update` meant here until I read the query and parsed this as `non-"Reported"` update.

2021-03-15 13:54 UTC, lieut-data commented on server/sqlstore/stats.go
> +func (s *StatsStore) AverageStartToActive(filters *StatsFilters) []int {
This seems like the kind of query where we might consider adding explicit timestamps on the incident objects to record these instead.

2021-03-15 13:54 UTC, lieut-data commented on server/sqlstore/stats.go
> +		JOIN Posts AS p ON sp.PostId = p.Id
Is it feasible to avoid the `JOIN Posts`? That would remove most of the performance concerns.

2021-03-15 13:54 UTC, lieut-data commented on server/sqlstore/stats.go
> +		Join("Channels AS c ON (c.Id = i.ChannelId)").
Noted earlier, but if we can use `i.CreateAt` we won't need the `JOIN` at all.

2021-03-15 16:38 UTC, crspeller commented on server/api/stats.go
> +	}
Good call on the guests. Guests actually do have the view team permissions. They don't have the list team channels permission. So I will modify to check that instead. 

> And who knows, in the future we might accidentally include confidential info in the stats.

Agreed, this will need tightening in the future, but for right now all the stats are fine to share with everyone.

> What happens if I omit the TeamID?

That gets caught in two places. The parseStatsFilters will return an error if the team_id is blank. Also the HasPermissionToTeam check does a blank check internally. You never have permissions to invalid IDs.

2021-03-15 16:41 UTC, crspeller commented on server/sqlstore/stats.go
> +		Select("COUNT(ID)").
I believe there is a slight one. Probably optimized away in most cases, but `COUNT` excludes NULL rows, so counting a single column can eliminate some checks.

2021-03-15 16:46 UTC, crspeller commented on server/sqlstore/stats.go
> +func (s *StatsStore) TotalActiveParticipants(filters *StatsFilters) int {
That's a good point. I will ask Tao.

2021-03-15 16:48 UTC, crspeller commented on webapp/src/components/backstage/incidents/incident_list/incident_list.tsx
> +            status = queryForStatus;
Love to, but the linter won't let me use the keyword `undefined`.

2021-03-15 16:50 UTC, crspeller commented on webapp/src/components/backstage/incidents/incident_list/incident_list.tsx
> +        };
That, and if the `fetchParams` changed quickly, the correct request would sometimes not win the race.

2021-03-15 16:51 UTC, crspeller commented on webapp/src/components/backstage/stats.tsx
> +            <div className='total-count'>
Because I am stealing these from the system console. https://github.com/mattermost/mattermost-webapp/blob/master/components/analytics/statistic_count.tsx#L24

When we get our own styles we should replace these with styled components.

2021-03-15 17:10 UTC, crspeller commented on webapp/src/components/backstage/stats.tsx
> +                    <GraphBox>
Yes! I should have done that before!

2021-03-15 17:16 UTC, crspeller commented on server/sqlstore/stats.go
> +		Where("i.EndAt = 0")
To easily include both `Ended` and `Archived` status.

2021-03-15 17:19 UTC, crspeller commented on server/sqlstore/stats.go
> +		Select("AVG(c.CreateAt)").
Yes. Will assume https://github.com/mattermost/mattermost-plugin-incident-collaboration/pull/491 is merged and modify queries as such.

2021-03-15 17:36 UTC, crspeller commented on server/sqlstore/stats.go
> +		Select(fmt.Sprintf("COUNT(i.Id), (%v - c.CreateAt) / 86400000 as DayStarted", now)).
No way to avoid the `fmt.Sprintf` here as the `Select` function takes a raw string.

2021-03-15 17:47 UTC, crspeller commented on server/sqlstore/stats.go
> +func (s *StatsStore) AverageStartToActive(filters *StatsFilters) []int {
That would work until we had custom statuses or something like that. Something to consider though.

2021-03-15 19:02 UTC, crspeller commented on server/sqlstore/stats.go
> +		JOIN Posts AS p ON sp.PostId = p.Id
I don't think so. Love to be proved wrong though. The status post is what we record for when an incident leaves "Reported". 
Also we already do this join in `GetIncidents`: https://github.com/mattermost/mattermost-plugin-incident-collaboration/blob/678a3c1fe38dc809186410f9cb5d815883b0f5ab/server/sqlstore/incident.go#L183 probably our hottest route? 
I think it even has worse performance characteristics there.

2021-03-15 19:04 UTC, crspeller commented
Awaiting #491

2021-03-15 19:05 UTC, crspeller commented on server/sqlstore/stats.go
> +		return -1
It doesn't. But it simplifies the code. Otherwise there would be a huge block of err checks doing this elsewhere. `-1` provides some warning that the stat is invalid.
1/5 I could move all these over.

2021-03-15 19:06 UTC, crspeller commented on webapp/src/components/backstage/incidents/incident_list/incident_list.tsx
> +
No idea. Artifact of the auto importer. Removed.

2021-03-15 19:07 UTC, crspeller commented on webapp/src/types/stats.ts
> +export interface PlaybookUse {
Considering it's not used, that's not surprising 😆 Removed.

2021-03-15 19:07 UTC, crspeller commented on webapp/src/index.tsx
> +                        navigateToTeamPluginUrl(team.name, '/stats');
Good question. Will ask Tao.

2021-03-15 19:08 UTC, crspeller commented on server/sqlstore/stats.go
> +		return []int{}
Same as above.

2021-03-16 13:01 UTC, lieut-data commented on server/sqlstore/stats.go
> +		JOIN Posts AS p ON sp.PostId = p.Id
Yeah, that's fair. I was imagining a solution that lets us track `CreateAt` directly on our tables which might alleviate some of the need to interop with the core Mattermost schema.

2021-03-16 18:12 UTC, cpoile commented on webapp/src/components/backstage/incidents/incident_list/incident_list.tsx
> +            status = queryForStatus;
I would add an `ignore` -- that's an "incorrect" linter error anyway, since a lot of js and js packages use `undefined` to specifically mean "don't include this field."

2021-03-25 17:36 UTC, cpoile approved these changes
🚢 🇮🇹

2021-03-29 15:54 UTC, merged