MM-33512 Create the updateStatus API endpoint
mattermost/mattermost-plugin-incident-collaboration pull request #493
Opened 2021-03-12 21:21 UTC by cpoile

#### Summary
- Created the updateStatus API endpoint
- had to make some changes to the client library, will tag a new version after merged
- tests

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-33512

2021-03-12 21:22 UTC, cpoile commented on client/client.go
> +			errorResponse.Err = errors.New(errorText.Error)
@lieut-data This was a weird little bug that tripped me up for awhile -- is it correct as originally written? Because it doesn't make much sense that way. This version makes more sense, since we return `{"error": "message"}` from our API endpoints.

2021-03-12 21:25 UTC, cpoile commented
I'm not sure why `go mod tidy` is different on CircleCI -- there's no difference on my local machine...

2021-03-15 09:35 UTC, agarciamontoro requested changes
This is great, thank you! The tests are super thorough :pray: 

I left some minor comments below, all of them more than open to discussion!

2021-03-15 09:35 UTC, agarciamontoro commented on client/go.mod
> +	github.com/mattermost/mattermost-server/v5 v5.32.0
Why the bump here?

2021-03-15 09:35 UTC, agarciamontoro commented on server/api/incidents.go
> +	w.WriteHeader(http.StatusOK)
If we're not returning any data, we should consider responding with a `http.StatusNoContent`.

2021-03-15 09:35 UTC, agarciamontoro commented on client/incident.go
> +	IncidentID        string `json:"incident_id"`
This is not needed in the JSON body, right? As far as I understand, it is only used when building the URL. If so, we can ignore it when marshaling:
```suggestion
	IncidentID        string `json:"-"`
```

2021-03-15 09:35 UTC, agarciamontoro commented on server/api/api.yaml
> +                  example: Active
We can use the `enum` keyword here:
```suggestion
                status:
                  type: string
                  enum:
                    - Reported
                    - Active
                    - Resolved
                    - Archived
                  description: The new status.
                  example: Active
```

2021-03-15 09:35 UTC, agarciamontoro commented on server/api/api.yaml
> +        200:
(we should change this too if we finally decide to send the NoContent code, as proposed in the comment in `server/api/incidents.go`)

2021-03-15 09:35 UTC, agarciamontoro commented on server/api/incidents_test.go
> +			Status:            "Arrrrrrrctive",
This made me laugh :joy:

2021-03-15 12:42 UTC, lieut-data approved these changes
Nothing blocking, but a handful of comments.

2021-03-15 12:42 UTC, lieut-data commented on client/client.go
> +			errorResponse.Err = errors.New(errorText.Error)
Hmm, `ErrorResponse` defines the appropriate field into which to receive that `{"error": "message"}`:

https://github.com/mattermost/mattermost-plugin-incident-collaboration/blob/fa9fedde728f2f71319038a89343076925c3191d/client/error_response.go#L14-L15

Can you elaborate on what exactly was going wrong?

2021-03-15 12:42 UTC, lieut-data commented on client/incident.go
> +	SortByCreateAt IncidentSort = "create_at"
I realize this is the same as before, but a tangential observation nonetheless: `SortByCreateAt`, despite being an `IncidentSort`, is effectively a global name in this package. If we support sorting playbooks by similarly named fields, should we disambiguate either with a more precise name `SortIncidentByCreateAt`, or by making the sortable fields of a more generic, `Sort` type?

2021-03-15 12:42 UTC, lieut-data commented on client/incident.go
> +	DirectionAsc = "asc"
Do we need these /and/ `SortDirection` below?

2021-03-15 12:42 UTC, lieut-data commented on client/incident.go
> +	IncidentID        string `json:"incident_id"`
I think this is for marshalling to /send/ to the server.

2021-03-15 12:42 UTC, lieut-data commented on client/incidents.go
> +func (s *IncidentsService) UpdateStatus(ctx context.Context, opts StatusUpdateOptions) error {
Again, somewhat tangential given this interface is still changing, but I recall an observation from the plugin-api-wrapper days where we agreed to make required parameters explicit, and leave the options for optional ones. So for example, in this case I wonder if we should:

```
func (s *IncidentsService) UpdateStatus(ctx context.Context, incidentId string, status Status, Message string, opts StatusUpdateOptions) error {
```

The rationale was that this made it much more obvious to the author of the code what to supply, avoiding common mistakes like forgetting required fields. We don't /have/ to do this in this PR -- just surfacing for discussion. (We should probably do something similar for `List`, with `page` and `perPage` being required instead of optional to force the pagination problem into the forefront.)

2021-03-15 12:42 UTC, lieut-data commented on server/api/incidents.go
> +// updateStatusD handles the POST /incidents/{id}/update-status endpoint, user has edit permissions
```suggestion
// updateStatus handles the POST /incidents/{id}/update-status endpoint, requiring edit permissions from the user
```

2021-03-15 12:42 UTC, lieut-data commented on server/api/incidents.go
> +// updateStatusD handles the POST /incidents/{id}/update-status endpoint, user has edit permissions
Would it make more sense to anchor this at `POST /incidents/{id}/status`, since we're effectively creating a status for the given incident, vs. `update-status` which reads more like a `PUT`?

2021-03-15 12:42 UTC, lieut-data commented on server/api/incidents.go
> +	w.WriteHeader(http.StatusOK)
3/5, but while semantically correct, I bet some clients trip over "weird" status codes. I can't recall ever seeing `StatusNoContent` in the wild.

2021-03-15 13:42 UTC, agarciamontoro commented on server/api/incidents.go
> +	w.WriteHeader(http.StatusOK)
I'd say that in that case, it's a client bug. The standard [states](https://tools.ietf.org/html/rfc7231#section-6.3.1) that "Aside from responses to CONNECT, a 200 response always has a payload, though an origin server MAY generate a payload body of zero length.If no payload is desired, an origin server ought to send 204 (No Content) instead"

2021-03-15 13:43 UTC, agarciamontoro commented on client/incident.go
> +	IncidentID        string `json:"incident_id"`
Yes, but the server only reads the Message, Reminder and Status, right?

2021-03-15 13:45 UTC, cpoile commented on client/client.go
> +			errorResponse.Err = errors.New(errorText.Error)
Because the `"error"` field as parsed from the response is a `string`, so the marshaller throws an incompatible type error when it tries to stuff it into an `error` type.

2021-03-15 13:58 UTC, lieut-data commented on client/client.go
> +			errorResponse.Err = errors.New(errorText.Error)
Oh, that makes sense! Can we customize the unmarshalling of `ErrorResponse` to handle this correctly and avoid doing it here?

2021-03-15 15:51 UTC, cpoile commented on client/client.go
> +			errorResponse.Err = errors.New(errorText.Error)
Yep, I did it. Take a look to see if you agree with how I brought the "otherwise fall back to using the whole body as the error message" into `ErrorResponse`'s `UnmarshalJSON`. I like how that reduces the caller's code. But open to suggestions.

2021-03-15 15:51 UTC, cpoile commented on client/go.mod
> +	github.com/mattermost/mattermost-server/v5 v5.32.0
It's a dependency bump from plugin-api v0.0.14

2021-03-15 15:51 UTC, cpoile commented on server/api/incidents.go
> +	w.WriteHeader(http.StatusOK)
As a compromise I'm returning `{"status":"OK"}`. We're not doing that for every 200 endpoint, but we do for some (e.g.: the frontend telemetry, because javascript's fetch expects a body and will error out when it doesn't get it).

2021-03-15 15:51 UTC, cpoile commented on client/incident.go
> +	IncidentID        string `json:"incident_id"`
Right -- I'm removing `incident_id` and also making the argument list change below. Thanks!

2021-03-15 15:51 UTC, cpoile commented on server/api/api.yaml
> +                  example: Active
Awesome, thanks!

2021-03-15 15:52 UTC, cpoile commented on client/incident.go
> +	SortByCreateAt IncidentSort = "create_at"
I think `IncidentSort` -> `Sort` makes sense, since we do keep the field name consistent. Done.

2021-03-15 15:52 UTC, cpoile commented on client/incident.go
> +	DirectionAsc = "asc"
oops, I forgot to remove those (and these weren't being used)

2021-03-15 15:52 UTC, cpoile commented on client/incidents.go
> +func (s *IncidentsService) UpdateStatus(ctx context.Context, opts StatusUpdateOptions) error {
That's a good point, I like the arguments being a list of what is necessary, and prefer that over the struct. Done.

2021-03-15 15:53 UTC, agarciamontoro commented on client/go.mod
> +	github.com/mattermost/mattermost-server/v5 v5.32.0
Ooooh ok, thanks!

2021-03-15 15:58 UTC, agarciamontoro commented on server/api/incidents.go
> +	w.WriteHeader(http.StatusOK)
Don't want to block this PR, so I'm ok with the compromise suggested. However, we're using 204 in other parts of the codebase, and I still don't understand why we should not use them :thinking: We can continue the discussion elsewhere!

2021-03-15 16:00 UTC, agarciamontoro commented on server/api/incidents.go
> +	w.WriteHeader(http.StatusOK)
We can always return the status itself, which also complies with the standard.

2021-03-15 16:01 UTC, agarciamontoro commented on client/incident.go
> +	IncidentID        string `json:"incident_id"`
Cool, thanks!

2021-03-15 16:01 UTC, agarciamontoro approved these changes
Thank you for addressing all the changes :pray:

2021-03-15 16:11 UTC, lieut-data requested changes
Nice cleanup! Just one comment on something that seems broken.

2021-03-15 16:11 UTC, lieut-data commented on client/error_response.go
> +	if err := json.Unmarshal(data, &temp); err != nil || temp.Err == "" {
Why the `temp.Err == ""`? Won't that be the "successful" case, meaning we'll always copy the body of every payload into `e.Err`?

2021-03-16 13:54 UTC, cpoile commented on client/error_response.go
> +	if err := json.Unmarshal(data, &temp); err != nil || temp.Err == "" {
if `temp.Err == ""` it means we couldn't unmarshal the error message into the `error` field (maybe it wasn't formatted correctly, e.g.: `{"errors":"the error message"}`), so that's when the fall back is triggered (use the whole body as the error message).

2021-03-16 16:37 UTC, lieut-data commented on client/error_response.go
> +	if err := json.Unmarshal(data, &temp); err != nil || temp.Err == "" {
Ah, my apologies, I had forgotten we were already in the context of "an error occurred, we're trying to figure out what it is."

2021-03-16 16:38 UTC, lieut-data approved these changes

2021-03-22 16:28 UTC, merged