Mm 31562.announcement automation
mattermost/mattermost-plugin-incident-collaboration pull request #495
Opened 2021-03-16 14:58 UTC by agarciamontoro

#### Summary
As with #440 and #483, this keeps on adding automations! This one is somewhat similar to the feature of broadcasting the status updates to a channel, but now with the incident creation. The announcement channel is independent of the one to broadcast the status updates.

##### Changes in the DB
- New columns in `IR_Playbook`:
  - `AnnouncementChannelID`, that contains the ID of the channel where the announcement is made
  - `AnnouncementChannelEnabled`, that stores the on/off state of the setting.
- New column in `IR_Incident`:
  - `AnnouncementChannelID`, which stores a copy of the data in the playbook's column when the incident is created. If the playbook's `AnnouncementChannelEnabled` contains `false`, the data is not copied, so there's no need to add a `AnnouncementChannelEnabled` column to the `IR_Incident` table.

##### Changes in the service
When the incident is created, it is announced in the configured channel. If the channel does not exist or is archived/deleted, the bot posts a message in the channel warning the user about it.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-31562

2021-03-16 20:16 UTC, crspeller requested changes
Good stuff!

2021-03-16 20:16 UTC, crspeller commented on server/incident/service.go
> +	if announcementChannel.DeleteAt != 0 {
If we do care about the channel is in the right team thing, we need to check it here too. Channels can move between teams. (rare, but happens)

2021-03-16 20:16 UTC, crspeller commented on tests-e2e/cypress/integration/backstage/playbook_details_spec.js
> +                it('can be enabled', () => {
Is it necessary to check if a checkbox works?

2021-03-16 20:16 UTC, crspeller commented on tests-e2e/cypress/integration/backstage/playbook_details_spec.js
> +                it('allows changing the channel', () => {
Is it necessary to verify the channel can be selected?

2021-03-16 20:16 UTC, crspeller commented on webapp/src/components/backstage/automation/announcement.tsx
> +        <>
Remove extra wrapper?

2021-03-17 10:05 UTC, agarciamontoro commented on server/api/playbooks.go
> +		if channel.TeamId != pbook.TeamID {
This makes it consistent with what we show in the UI, which is channels in the same team. I'd rather err in the side of being consistent instead of giving too much flexibility in the API side. What do you think?

2021-03-17 10:09 UTC, agarciamontoro commented on server/api/playbooks.go
> +	if pbook.AnnouncementChannelID != "" {
Yeah, this was a design decision I made with the invite users: if one of the invited users is deleted/removed from the team, they are removed from the automation. Same with the commander, but in this case it is different: if the commander is gone, should we show the setting with no commander selected? That is not supported otherwise, and I think it would be more misleading having the setting enabled but completely useful (because we will not be able to assign the commander). Same for this setting with the announcement channel.

I agree with the helper function, thanks for catching that!

2021-03-17 10:09 UTC, agarciamontoro commented on server/incident/service.go
> +	if announcementChannel.DeleteAt != 0 {
Oh, I was not aware of that. Good catch!

2021-03-17 10:12 UTC, agarciamontoro commented on tests-e2e/cypress/integration/backstage/playbook_details_spec.js
> +                it('can be enabled', () => {
Common things can be broken for the most strange reasons. I would not say it is super necessary, but it gives me some peace of mind. I am not concerned about my time developing this, so the only missing concern is the time spent in the tests. I don't think this specific test adds that much time, although the solution for that would be to parallelize the tests.

2021-03-17 10:12 UTC, agarciamontoro commented on tests-e2e/cypress/integration/backstage/playbook_details_spec.js
> +                it('allows changing the channel', () => {
Same answer as above!

2021-03-17 10:13 UTC, agarciamontoro commented on webapp/src/components/backstage/automation/announcement.tsx
> +        <>
Oops, you're right, thanks!

2021-03-17 14:46 UTC, crspeller commented on server/api/playbooks.go
> +		if channel.TeamId != pbook.TeamID {
My intuition says the API should be as flexible as we can make it. I understand the need to simplify the UI. But what if a customer has the use case of a cross-team announcement and we can enable that for them using the API? I think someone using the API would probably appreciate the flexibility.

2021-03-17 14:50 UTC, crspeller commented on server/api/playbooks.go
> +	if pbook.AnnouncementChannelID != "" {
The part that gets me is removing it as a side effect of saving. I wonder if we could just forget about checking on update, and just put an error message in the UI warning that it's out of date? Like <Red highlight>"This user is disabled" or whatever.
This shouldn't block this PR though.

2021-03-17 14:55 UTC, crspeller commented on tests-e2e/cypress/integration/backstage/playbook_details_spec.js
> +                it('can be enabled', () => {
My concern is mostly the overall maintenance cost of all these e2e tests. It might be simple to write. But when Tao goes and has us rename something, or we refactor, or the webapp changes, these tests break because they are super brittle most of the time. The less and more focused the tests, the less breakage we have to deal with. 
0/5 on this specific case. This is more something I have been thinking about overall.

2021-03-17 16:43 UTC, agarciamontoro commented on server/api/playbooks.go
> +		if channel.TeamId != pbook.TeamID {
That's a good point. I'll remove this restriction, and check instead that the user is in the channel or can join it (the channel is public in a team the user is a member of, or the user is an admin). Do you happen to know if the PERMISSION_READ_CHANNEL would work for that use case?

2021-03-17 16:50 UTC, agarciamontoro commented on tests-e2e/cypress/integration/backstage/playbook_details_spec.js
> +                it('can be enabled', () => {
I agree that E2E tests are now very brittle. We need to solve that, but I'd vote for a different approach than writing less tests. I'd vote for leaving these ones here, but I'll take this into account for future tests. Does that sound good?

2021-03-17 16:52 UTC, agarciamontoro commented on server/api/playbooks.go
> +	if pbook.AnnouncementChannelID != "" {
I agree we need some error checking in the client side. That is something we've been postponing for a while, now, but that would let us simply return an error here. We need to discuss this to tackle it holistically, I think.

2021-03-18 11:33 UTC, agarciamontoro commented on server/api/playbooks.go
> +		if channel.TeamId != pbook.TeamID {
@crspeller, I was having a hard time changing this because it was not clearly defined, so I got back to the ticket and saw that this restriction was there by design. What do you think about leaving this as is and reviewing it in a future PR, with a better defined permission system?

2021-03-18 11:38 UTC, agarciamontoro commented on webapp/src/components/backstage/automation/announcement.tsx
> +        <>
Done in https://github.com/mattermost/mattermost-plugin-incident-collaboration/pull/495/commits/c5bf76ff373ef19c485ed3544d8255a8a314d8ed.

2021-03-18 11:39 UTC, agarciamontoro commented on server/incident/service.go
> +	if announcementChannel.DeleteAt != 0 {
Done in https://github.com/mattermost/mattermost-plugin-incident-collaboration/pull/495/commits/52ce165e96027496130681cf9d63e66a3e4d9d47.

2021-03-18 11:39 UTC, agarciamontoro commented on server/api/playbooks.go
> +	if pbook.AnnouncementChannelID != "" {
Done in https://github.com/mattermost/mattermost-plugin-incident-collaboration/pull/495/commits/52ce165e96027496130681cf9d63e66a3e4d9d47.

2021-03-18 22:23 UTC, crspeller commented on server/api/playbooks.go
> +		if channel.TeamId != pbook.TeamID {
@agarciamontoro Maybe just do the same check as the broadcast channel ID above? PERMISSION_CREATE_POST sounds about right. It's still restricted in the UI so we can do what the ticket says.

2021-03-22 10:49 UTC, agarciamontoro commented on server/api/playbooks.go
> +		if channel.TeamId != pbook.TeamID {
Done in https://github.com/mattermost/mattermost-plugin-incident-collaboration/pull/495/commits/647abb0a0f3e2eddb8cda4dd1f5838581a3b443e

2021-03-22 18:04 UTC, agarciamontoro commented
/update-branch

2021-03-24 14:50 UTC, crspeller approved these changes
Looking good!

2021-03-25 13:27 UTC, justinegeffen reviewed
I gave this a quick review and added some minor suggestions. :)

2021-03-25 13:27 UTC, justinegeffen commented on server/incident/service.go
> +	announcementMsg += fmt.Sprintf("**Commander**: @%s\n", commander.Username)
```suggestion
	announcementMsg += fmt.Sprintf("**Commander:** @%s\n", commander.Username)
```

2021-03-25 13:27 UTC, justinegeffen commented on server/incident/service.go
> +		announcementMsg += fmt.Sprintf("**Description**: %s\n", theIncident.Description)
```suggestion
		announcementMsg += fmt.Sprintf("**Description"** %s\n", theIncident.Description)
```

2021-03-25 13:27 UTC, justinegeffen commented on tests-e2e/cypress/integration/frontstage/incident_automation_spec.js
> +                    // # Create a new incident with the playbook.
```suggestion
                    // # Create a new incident with the playbook
```

2021-03-25 13:27 UTC, justinegeffen commented on server/incident/service.go
>  // CreateIncident creates a new incident. userID is the user who initiated the CreateIncident.
```suggestion
// CreateIncident creates a new incident. userID is the user who initiated the CreateIncident
```

2021-03-25 13:27 UTC, justinegeffen commented on tests-e2e/cypress/integration/frontstage/incident_automation_spec.js
> +                    // # Navigate to the incident channel.
```suggestion
                    // # Navigate to the incident channel
```

2021-03-25 13:27 UTC, justinegeffen commented on tests-e2e/cypress/integration/frontstage/incident_automation_spec.js
> +                    // * Verify that the channel is created and that the first post exists.
```suggestion
                    // * Verify that the channel is created and that the first post exists
```

2021-03-25 13:27 UTC, justinegeffen commented on tests-e2e/cypress/integration/frontstage/incident_automation_spec.js
> +                    // * Verify that the channel is created and that the first post exists.
```suggestion
                    // * Verify that the channel is created and that the first post exists
```

2021-03-25 17:59 UTC, cpoile approved these changes
Can't think of anything, looks great, thanks @agarciamontoro!

2021-03-26 15:41 UTC, merged