MM-33855 Ad-hoc Tasks
mattermost/mattermost-plugin-incident-collaboration pull request #502
Opened 2021-03-24 23:30 UTC by crspeller

#### Summary
Allows editing of the incident task list. Supports add, remove, edit, and reorder operations.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-33855

2021-03-25 10:59 UTC, agarciamontoro requested changes
Wow, this is a great job, thank you! I'm happy we got these features back :tada:

I left a bunch of comments, a lot of them nits. I also have a couple of UI considerations:
- The cursor is not a pointer on the menu with the drag/edit/delete/assignee buttons. I don't know if it was like that before this PR, but I guess it's easily fixable here in any case.
- I cannot drag items between checklists. I think this is expected, as there is an Add new task button in each checklist, but it felt weird on the first interaction. Something to evaluate on the UX side, probably not on this PR.
- The slash command autocomplete in the edit modal (which is really cool!) has a couple of bugs (I'm on Firefox, I have not tested in other browsers): the whole modal is misaligned, and the spacing in the individual items seems weird. The screenshot below shows both errors:
![image](https://user-images.githubusercontent.com/3924815/112461573-56f1dc00-8d60-11eb-990f-0ba0cde2332a.png)

Also, what happened with the `package.json`? I must admit I was a bit scared when I saw the + 23,299 on the lines changed count :joy:

2021-03-25 10:59 UTC, agarciamontoro commented on server/incident/service.go
> +func (s *ServiceImpl) GetChecklistAutocompleteItem(incidentID string) ([]model.AutocompleteListItem, error) {
Also, are the names swapped? This is returning the checklists, so I *think* this should be `GetChecklistAutocomplete`. Maybe I'm missing something?

2021-03-25 10:59 UTC, agarciamontoro commented on tests-e2e/cypress/integration/frontstage/incident_rhs_checklist_spec.js
> +            // CHeck that it was created
Nit
```suggestion
            // Check that it was created
```

2021-03-25 10:59 UTC, agarciamontoro commented on tests-e2e/cypress/integration/frontstage/incident_rhs_checklist_spec.js
> +            // CHeck that it was created
Nit
```suggestion
            // Check that it was created
```

2021-03-25 10:59 UTC, agarciamontoro commented on tests-e2e/cypress/integration/frontstage/incident_rhs_checklist_spec.js
> +            cy.findByText(newTasktext).should('exist');
Should we isolate this at least to the RHS? Or maybe make the text unique with a timestamp or something similar. Same comment in the other test.

2021-03-25 10:59 UTC, agarciamontoro commented on tests-e2e/cypress/support/plugin_ui_commands.js
> +    cy.findByText('Add Task').click();
Same isolation comment here. Maybe this selector is too flexible. Is there a way to isolate it? Getting the dialog first and then finding by text, maybe?

2021-03-25 10:59 UTC, agarciamontoro commented on webapp/src/components/assets/inputs.tsx
> +    transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s, -webkit-box-shadow ease-in-out .15s;
According to [the docs](https://styled-components.com/docs/basics#motivation), we should not need the prefixes here: "Automatic vendor prefixing: write your CSS to the current standard and let styled-components handle the rest." Do we need it here?

2021-03-25 10:59 UTC, agarciamontoro commented on webapp/src/components/checklist_item.tsx
> +                <CheckboxContainer >
Nit
```suggestion
                <CheckboxContainer>
```

2021-03-25 10:59 UTC, agarciamontoro commented on webapp/src/components/checklist_item_input.tsx
> +    }, [focus, setFocus]);
Not sure what this does

2021-03-25 10:59 UTC, agarciamontoro commented on webapp/src/components/command_input.tsx
> +const OverrideWebappStyle = createGlobalStyle`
How do the `createGlobalStyle` work? Isn't it the same as writing a CSS file?

2021-03-25 10:59 UTC, agarciamontoro commented on webapp/src/components/widgets/generic_modal.tsx
> +export default class GenericModal extends React.PureComponent<Props, State> {
Why is this a class component and not a functional one?

2021-03-25 13:56 UTC, crspeller commented on server/api/incidents.go
> +		HandleErrorWithCode(w, http.StatusForbidden, "user does not have permissions", nil)
Copy pasted error. Fixed in the other function too.

2021-03-25 13:57 UTC, crspeller commented on server/api/incidents.go
> +		HandleErrorWithCode(w, http.StatusBadRequest, "failed to decode SubmitDialogRequest", nil)
But there is no err here?

2021-03-25 13:58 UTC, crspeller commented on server/api/incidents.go
> +	if err := h.incidentService.AddChecklistItem(incidentID, userID, checklistNum, checklistItem); err != nil {
Nope. It's done in a router `Use` (check `incidentRouterAuthorized`)

2021-03-25 13:59 UTC, crspeller commented on server/command/command.go
> +		"Available commands: start, end, update, restart, check, item, announce, list, commander, info, timeline")
The fact this isn't automatic makes me angry.

2021-03-25 14:11 UTC, crspeller commented on server/incident/service.go
> +func (s *ServiceImpl) GetChecklistAutocompleteItem(incidentID string) ([]model.AutocompleteListItem, error) {
Yes you are right. No need to preserve API compatibility so I did mean to flip them around.

2021-03-25 14:13 UTC, crspeller commented on tests-e2e/cypress/integration/frontstage/incident_rhs_checklist_spec.js
> +            cy.findByText(newTasktext).should('exist');
Added a timestamp to make the text more unique.

2021-03-25 14:14 UTC, crspeller commented on tests-e2e/cypress/support/plugin_ui_commands.js
> +    cy.findByText('Add Task').click();
But this is nice, because it only tests what we care about. It's somewhere on the screen. So if we re-arrange the UI, this test doesn't break :D

2021-03-25 14:15 UTC, crspeller commented on webapp/src/components/assets/inputs.tsx
> +    transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s, -webkit-box-shadow ease-in-out .15s;
Probably not. Didn't write this CSS just copy pasted. Willing to horribly break safari if you are 😆

2021-03-25 14:21 UTC, crspeller commented on webapp/src/components/command_input.tsx
> +const OverrideWebappStyle = createGlobalStyle`
Pretty much.

2021-03-25 14:34 UTC, crspeller commented
@agarciamontoro 
- Fixed the pointer thing (it was actually a problem before)
- I know about the not being able to drag between checklists. Going to add a separate ticket for that.
- Fixed the strange spacing, but the offset appears intentional? It works the same in the backstage and in the webapp. 
- Not sure why the package-lock.json keeps doing this... I didn't even change anything!

2021-03-25 19:18 UTC, cpoile approved these changes
noice. Can't see anything blocking. Thanks @crspeller!

2021-03-25 19:18 UTC, cpoile commented on webapp/src/components/widgets/generic_modal.tsx
> +export default class GenericModal extends React.PureComponent<Props, State> {
Probably because it's from webapp, right?

2021-03-25 19:19 UTC, crspeller commented on webapp/src/components/widgets/generic_modal.tsx
> +export default class GenericModal extends React.PureComponent<Props, State> {
Yes! Sorry I skipped this on the first pass. I just copy pasted this from the webapp.

2021-03-29 07:50 UTC, agarciamontoro commented on server/api/incidents.go
> +	if err := h.incidentService.AddChecklistItem(incidentID, userID, checklistNum, checklistItem); err != nil {
Oh yeah, that's true, always forget about that. Thanks!

2021-03-29 07:51 UTC, agarciamontoro commented on server/api/incidents.go
> +		HandleErrorWithCode(w, http.StatusBadRequest, "failed to decode SubmitDialogRequest", nil)
Indeed, I commented on the wrong line. But you fixed it on the one I actually wanted to comment on :joy:

2021-03-29 07:55 UTC, agarciamontoro commented on tests-e2e/cypress/support/plugin_ui_commands.js
> +    cy.findByText('Add Task').click();
That's true! I agree that in this case, it's probably more probable that we re-arrange the UI than that someone else adds a "Add Task" text somewhere.

2021-03-29 07:56 UTC, agarciamontoro commented on webapp/src/components/assets/inputs.tsx
> +    transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s, -webkit-box-shadow ease-in-out .15s;
I am :man_shrugging:

2021-03-29 08:28 UTC, agarciamontoro approved these changes
Cool! Nothing major blocking on the second review, thank you!

About the `package-lock.json` changes: is it possible that you are using npm 7? Your change is now using the new [lockfile format](https://github.blog/2021-02-02-npm-7-is-now-generally-available/#changes-to-the-lockfile). It seems to be backwards compatible, so I'm ok leaving it as it is. @cpoile and I may have to update, though?

2021-03-29 08:28 UTC, agarciamontoro commented on server/incident/incident.go
>  	// GetChecklistAutocomplete returns the list of checklist items for incidentID to be used in autocomplete
Still nit:
```suggestion
	// GetChecklistItemAutocomplete returns the list of checklist items for incidentID to be used in autocomplete
```

2021-03-29 15:10 UTC, merged