MM-31558: Outgoing webhook on incident's creation
mattermost/mattermost-plugin-incident-collaboration pull request #503
Opened 2021-03-26 10:32 UTC by agarciamontoro

#### Summary
One more automation! This is a bit more fun, as we are talking to the outside world now via a webhook!

##### Changes in the backstage
There's a new "Send a webhook" entry in the automations group, with a simple text box. The text box validates itself via some cool `input` attributes (`required` and `pattern`) and CSS pseudo-classes (`:invalid`) I did not know about.
| Correct webhook 	| Misconfigured webhook 	|
|-	|-	|
| ![good](https://user-images.githubusercontent.com/3924815/112617311-18722500-8e25-11eb-839f-0b1dafcf1cc6.png) 	| ![wrong](https://user-images.githubusercontent.com/3924815/112617334-21fb8d00-8e25-11eb-9f94-1c45246c69df.png) 	|

##### Changes in the DB
- New columns in `IR_Playbook`:
  - `CreationWebhookURL`, which contains the, ehem, webhook URL.
  - `CreationWebhookEnabled`, that stores the on/off state of the setting.
- New column in `IR_Incident`:
  - `CreationWebhookURL`, which stores a copy of the data in the playbook's column when the incident is created. If the playbook's `CreationWebhookEnabled` contains `false`, the data is not copied, so there's no need to add a `CreationWebhookEnabled` column to the `IR_Incident` table.

##### Changes in the service
When the incident is created, a POST request is sent to the URL with a payload consisting of the incident data plus a couple of absolute URLs: one to the incident's channel, and another one to the incident's details in the backstage. I decided to isolate this work in a goroutine because I did not want to block the incident creation with the response from an external server we know nothing about.

If the response to the request is not in the 2XX range, the bot posts a message in the incident's channel warning about it. There are no retries whatsoever.

![image](https://user-images.githubusercontent.com/3924815/112618598-9420a180-8e26-11eb-9b9f-8211d2fd2f87.png)

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-31563

2021-03-26 10:34 UTC, agarciamontoro commented
@justinegeffen, I wanted to know your opinion on the bot's message. And, if you have time, on the changes in the `api.yaml` file

2021-03-26 12:28 UTC, justinegeffen reviewed
I've taken a look through the PR and made some suggestions. I think I missed the bot messages though - could you let me know whether I did and I'll give it a second pass.

2021-03-26 13:49 UTC, agarciamontoro commented on server/api/api.yaml
> +                  description: Your server returns a 2XX code if it successfuly received the request.
- I used the uppercase X because it's like that in the official docs: https://swagger.io/specification/#patterned-fields-1
- I never  trust myself when writing so many double consonants in that word. I'll add it in a separate comment not to add the lowercase, too, if that's ok!

2021-03-26 13:52 UTC, agarciamontoro commented on server/incident/service.go
> +				_, _ = s.poster.PostMessage(channel.Id, "Failed to communicate the incident's creation through the outgoing webhook.")
This is the bot message, @justinegeffen

2021-03-26 16:06 UTC, agarciamontoro commented
Sorry for the forced push, this was based on #495 and a simple merge was a bit cumbersome. All good to go now.

2021-03-29 15:53 UTC, crspeller requested changes

2021-03-29 15:53 UTC, crspeller commented on server/incident/service.go
> +		ChannelURL: channelURL,
These are just conveniences for the webhook receiver? We are imagining the receiver want's to display the incident to the user and these are the back-links?

2021-03-29 15:53 UTC, crspeller commented on server/incident/service.go
> +	resp, err := http.Post(theIncident.CreationWebhookURL, "application/json", bytes.NewReader(body))
It's really tempting to use this, but we should make an `http.Client` and use that. At least the last time I checked `http.Post` has many many issues. 
I think the biggest things are having a constant connection pool and specifying a timeout. Have a look at how the server uses `services/httpservice` for inspiration.

2021-03-29 15:53 UTC, crspeller commented on server/incident/service.go
> +	}
Need to close the response body. See: https://golang.org/pkg/net/http/#Client.Post

2021-03-29 15:53 UTC, crspeller commented on tests-e2e/cypress/integration/frontstage/incident_automation_spec.js
> +                    creationWebhookURL: 'https://httpbin.org/post',
This will fail if this URL is unavailable. Or when there is an inevitable glitch.

2021-03-29 15:53 UTC, crspeller commented on tests-e2e/cypress/integration/frontstage/incident_automation_spec.js
> +                    creationWebhookURL: 'http://example.com/not-an-actual-endpoint',
What happens if the owner of example.com decides this URL should return success?

2021-03-29 15:53 UTC, crspeller commented on webapp/src/components/backstage/automation/creation_webhook.tsx
> +                pattern={'https?://.*'}
Nice!

2021-03-29 15:56 UTC, agarciamontoro commented on server/incident/service.go
> +		ChannelURL: channelURL,
Yes, they are! It's an ask from Tao so that the users don't need to do it themselves. We do know it's redundant, as you can derive this string from the other fields (and the base URL) but it's a couple of strings and it can make their lives easier.

2021-03-29 15:58 UTC, agarciamontoro commented on tests-e2e/cypress/integration/frontstage/incident_automation_spec.js
> +                    creationWebhookURL: 'https://httpbin.org/post',
Yup, that's true, but it was way easier to do it this way than to spin up a new server listening to this for the sake of testing. I'd vote for fixing it if/when it fails.

2021-03-29 15:58 UTC, agarciamontoro commented on tests-e2e/cypress/integration/frontstage/incident_automation_spec.js
> +                    creationWebhookURL: 'http://example.com/not-an-actual-endpoint',
The test will fail. As before, I think we should fix this if the need arise.

2021-03-29 15:59 UTC, cpoile requested changes
Minor suggestions, but requesting changes because I'd like to know what you decide. :)

Nice work @agarciamontoro!

2021-03-29 15:59 UTC, cpoile commented on server/api/api.yaml
> +          "{$request.body#/creation_webhook_url}":
Is this specific `api.yaml` code? I'm not sure how to parse it, to tell if it's correct or not. :)

2021-03-29 15:59 UTC, cpoile commented on server/incident/service.go
> +// It blocks until a response is received.
iirc, there's a client method you can use with a `Context` that will fire a timeout and close the request. Maybe we should use that? I agree that we don't need to worry about retries, but we 1/5 should try to protect against opening connections without a timeout.

2021-03-29 15:59 UTC, cpoile commented on server/sqlstore/migrations.go
> +				if err := addColumnToMySQLTable(e, "IR_Incident", "CreationWebhookURL", "TEXT"); err != nil {
0/5 naming: should we prefix all webhooks with a standard, like `On` or `Webhook`, e.g.: `OnCreationWebhookURL` or `WebhookCreationURL`

2021-03-29 15:59 UTC, agarciamontoro commented on server/incident/service.go
> +	resp, err := http.Post(theIncident.CreationWebhookURL, "application/json", bytes.NewReader(body))
I did not know about those issues. Thanks for that!

2021-03-29 16:02 UTC, agarciamontoro commented on server/api/api.yaml
> +          "{$request.body#/creation_webhook_url}":
I got this from https://swagger.io/docs/specification/callbacks/?sbsearch=callback%20SmartBear It displays literally like that in the rendered docs, so I'm not that sure it's correct. I'll take another look, I had forgotten I had added that.

2021-03-29 16:03 UTC, agarciamontoro commented on server/sqlstore/migrations.go
> +				if err := addColumnToMySQLTable(e, "IR_Incident", "CreationWebhookURL", "TEXT"); err != nil {
I like the second option, it's true that it will be easier to parse it in the future. Thanks!

2021-03-29 16:09 UTC, agarciamontoro commented on server/incident/service.go
> +// It blocks until a response is received.
What I meant with the code is that it will block until we get a response, even with a timeout. I was assuming there was a default timeout in http.Post, but I actually did not check. I'll take a look, along with the suggestion from Christopher to use an actual client.

2021-03-30 08:50 UTC, agarciamontoro commented on server/api/api.yaml
> +          "{$request.body#/creation_webhook_url}":
It is actually part of the spec: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#runtimeExpression Sadly, redocly shows the literal string. I'd vote for leaving it as it is. I think it is understandable, and it is correct. We can also use a simple string such as "URL specified at creation_webhook_url".
What do you think?

2021-03-30 09:56 UTC, agarciamontoro commented on server/sqlstore/migrations.go
> +				if err := addColumnToMySQLTable(e, "IR_Incident", "CreationWebhookURL", "TEXT"); err != nil {
Done in https://github.com/mattermost/mattermost-plugin-incident-collaboration/pull/503/commits/f8ec2f6612d7d58927d019e5d698f42e61e81457. I ended up prefixing everything by `Webhook`, then `OnCreation`, then whatever.

2021-03-30 10:00 UTC, agarciamontoro commented on server/incident/service.go
> +	resp, err := http.Post(theIncident.CreationWebhookURL, "application/json", bytes.NewReader(body))
Done in https://github.com/mattermost/mattermost-plugin-incident-collaboration/pull/503/commits/3307d570f4e333e0f818d8f74eb4b23c70dcd3df
I ended up doing something similar to https://github.com/mattermost/mattermost-server/blob/master/app/webhook.go#L150-L167, but with [the default transport](https://github.com/golang/go/blob/master/src/net/http/transport.go#L37-L53) instead of a custom one. I also thought about maintaining a client in the service, but I think that, for now, we are ok creating one.
Thoughts?

2021-03-30 10:00 UTC, agarciamontoro commented on server/incident/service.go
> +	}
Done in https://github.com/mattermost/mattermost-plugin-incident-collaboration/pull/503/commits/3307d570f4e333e0f818d8f74eb4b23c70dcd3df. Thanks!

2021-03-30 10:04 UTC, agarciamontoro commented on server/incident/service.go
> +// It blocks until a response is received.
Done in https://github.com/mattermost/mattermost-plugin-incident-collaboration/pull/503/commits/3307d570f4e333e0f818d8f74eb4b23c70dcd3df. I specified a timeout of 30 seconds, which is [the default](https://github.com/mattermost/mattermost-server/blob/master/services/httpservice/client.go#L19) used by the `service/httpservice` in the server. Thoughts?

2021-03-30 19:54 UTC, cpoile commented on server/api/api.yaml
> +          "{$request.body#/creation_webhook_url}":
Sounds good to me, just checking. :)

2021-03-30 19:55 UTC, cpoile commented on server/incident/service.go
> +// It blocks until a response is received.
Awesome!

2021-03-31 08:05 UTC, justinegeffen commented on server/incident/service.go
> +				_, _ = s.poster.PostMessage(channel.Id, "Failed to communicate the incident's creation through the outgoing webhook.")
Thanks, @agarciamontoro! Are there remediation steps provided or is it a once-off message as-is? I wonder if something like "Check the logs for more information" would be helpful, and then elaborating on the log as to what exactly failed in terms of the POST request? Helpful error messages are few and far between and this is a good opportunity to provide helpful guidance. :)

2021-03-31 08:06 UTC, justinegeffen commented on server/incident/service.go
> +				_, _ = s.poster.PostMessage(channel.Id, "Failed to communicate the incident's creation through the outgoing webhook.")
Something like: "Incident creation using an outgoing webhook was unsuccessful. Review the logs for more details."

^^ if that works, I can do another review for any other warnings/errors and we can set a standard for them going forward.

2021-03-31 08:07 UTC, agarciamontoro commented on server/incident/service.go
> +				_, _ = s.poster.PostMessage(channel.Id, "Failed to communicate the incident's creation through the outgoing webhook.")
There would be more information in the logs, yes. Only available to admins, of course, while this message is readable by everyone on the incident's channel.

2021-03-31 08:10 UTC, justinegeffen commented on server/incident/service.go
> +				_, _ = s.poster.PostMessage(channel.Id, "Failed to communicate the incident's creation through the outgoing webhook.")
Is there an associated error message? For example, we can say "Incident creation using the outgoing webhook was unsuccessful with error xxx. Contact your System Admin for more information." That way it's easier to diagnose and fix the issue?

2021-03-31 08:10 UTC, justinegeffen commented on server/incident/service.go
> +				_, _ = s.poster.PostMessage(channel.Id, "Failed to communicate the incident's creation through the outgoing webhook.")
Sorry, error code, not error message. Like 200, 504, etc.

2021-03-31 08:13 UTC, agarciamontoro commented on server/incident/service.go
> +				_, _ = s.poster.PostMessage(channel.Id, "Failed to communicate the incident's creation through the outgoing webhook.")
Mmm it can fail for other reasons we may not want to surface in the channel to everyone, so I'd err on the safe side and simply point to the logs. What do you think?

2021-03-31 09:01 UTC, justinegeffen commented on server/incident/service.go
> +				_, _ = s.poster.PostMessage(channel.Id, "Failed to communicate the incident's creation through the outgoing webhook.")
Yep, I agree. How about: "Incident creation using the outgoing webhook was unsuccessful. Contact your System Admin for more information."

2021-03-31 13:51 UTC, agarciamontoro commented
/update-branch

2021-03-31 13:53 UTC, agarciamontoro commented on server/incident/service.go
> +				_, _ = s.poster.PostMessage(channel.Id, "Incident creation using the outgoing webhook was unsuccessful. Contact your System Admin for more information.")
@justinegeffen To me, this sounds like the creation of the incident was unsuccessful. But the creation was successful. The only error occurred when sending the request to the configured webhook (i.e., kind of announcing the creation of the incident to the configured webhook), which does not prevent the incident from being created. Maybe I'm misunderstanding something?

2021-04-06 08:48 UTC, justinegeffen commented on server/incident/service.go
> +				_, _ = s.poster.PostMessage(channel.Id, "Incident creation using the outgoing webhook was unsuccessful. Contact your System Admin for more information.")
Ah, I see, I misunderstood! So something like:

"Incident creation announcement through the outgoing webhook failed. Contact your System Admin for more information."

For reference, the original was: "Failed to communicate the incident's creation through the outgoing webhook." which imo also works if my suggestion over-complicates things! :)

2021-04-06 08:50 UTC, agarciamontoro commented on server/incident/service.go
> +				_, _ = s.poster.PostMessage(channel.Id, "Incident creation using the outgoing webhook was unsuccessful. Contact your System Admin for more information.")
I think that works perfectly, thank you! I'll add it myself, I also need to change a test so it does not fail.

2021-04-06 14:05 UTC, agarciamontoro commented
@crspeller, ready for re-review!

2021-04-06 14:09 UTC, crspeller commented on server/incident/service.go
> +	resp, err := http.Post(theIncident.CreationWebhookURL, "application/json", bytes.NewReader(body))
@agarciamontoro Looks good, but optimally we should keep the client on the service. It keeps a connection pool for subsequent requests.

2021-04-06 14:09 UTC, crspeller requested changes
Just the one issue with the client.

2021-04-06 14:13 UTC, agarciamontoro commented on server/incident/service.go
> +	resp, err := http.Post(theIncident.CreationWebhookURL, "application/json", bytes.NewReader(body))
Ok, let me move it to the incident service, thanks!

2021-04-06 14:23 UTC, crspeller approved these changes
Awesome!

2021-04-06 15:51 UTC, agarciamontoro commented
/update-branch

2021-04-07 07:30 UTC, agarciamontoro commented
/update-branch

2021-04-07 08:03 UTC, agarciamontoro commented
Skipping QA review because this feature is fairly isolated.

2021-04-07 08:30 UTC, merged