MM-34098, MM-34047, MM-34482, MM-34567 - New Incident backstage: overview
mattermost/mattermost-plugin-incident-collaboration pull request #516
Opened 2021-04-13 18:08 UTC by cpoile

#### Summary
- These are mostly webapp changes, so not too complicated to review I think.  Like I mentioned before, I tried to keep the components as small and compartmentalized as possible.
- The design hasn't been finalized, so I'm using a kind of Whimsical style. That will change.
- The Metrics component is placeholder for now.
- The backend changes are mostly related to adding the "changes since last update" textarea to the `Update Status` dialog, adding the defaults to the playbook templates, and connecting the playbook templates to the incident instance.
- I'm using the description field as the "changes since last update", this way we don't have to add anything to the SQL, and we weren't using it anyway. Tao doesn't want us to do anything with the channel headers anymore.

#### Notes / TODOs
- This won't build / pass CI until we figure out what to do about npm 7 in CI

#### This changes quite a few parts of the flow:
![image](https://user-images.githubusercontent.com/1490756/114599362-fec44080-9c60-11eb-837e-ec48acd06fc2.png)

![image](https://user-images.githubusercontent.com/1490756/114599288-e522f900-9c60-11eb-93bb-8a7b1e20f51f.png)

![image](https://user-images.githubusercontent.com/1490756/114599394-08e63f00-9c61-11eb-8b48-af5111bc2e55.png)

![image](https://user-images.githubusercontent.com/1490756/114599416-0f74b680-9c61-11eb-9b46-e7e13b823f4f.png)

![image](https://user-images.githubusercontent.com/1490756/114599457-21565980-9c61-11eb-8ea7-c984db84f1dd.png)

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-34047 - In `Update Status` dialog, separate the Current Status and Changes Since Last Update
- https://mattermost.atlassian.net/browse/MM-34482 - Description (changes since last update) in the RHS and backstage overview
- https://mattermost.atlassian.net/browse/MM-34567 - Participants list in backstage overview
- https://mattermost.atlassian.net/browse/MM-34098 - Prototyping the backstage overview

2021-04-13 18:12 UTC, cpoile commented on webapp/src/components/backstage/backstage.tsx
> +                        {/*<BackstageIncidentDetails/>*/}
`BackstageIncidentDetails` will be removed in final cleanup PR. I need them for now for reference.

2021-04-13 18:12 UTC, cpoile commented on webapp/src/components/backstage/backstage.tsx
> +                        {/*<Dashboard/>*/}
this is coming in a future PR

2021-04-13 18:15 UTC, cpoile commented on webapp/src/components/backstage/incidents/incident_backstage/overview/participants.tsx
> +            {showMessage && <SecondaryButtonRight>{'Message'}</SecondaryButtonRight>}
Todo

2021-04-14 09:35 UTC, agarciamontoro approved these changes
The code looks good! I left a handful of comments, all of them nits, so nothing blocking. I also found some commented code in the CSS, but assumed it was because the design is not finished.

I like the small components, and *love* the new hooks, thank you!

2021-04-14 09:35 UTC, agarciamontoro commented on webapp/src/hooks.ts
> +        dispatch(getProfilesInChannel(channelId, 0, PROFILE_CHUNK_SIZE));
This gets only a few of the profiles, right?

2021-04-14 09:35 UTC, agarciamontoro commented on webapp/src/selectors.ts
> +}
Not sure about what this function does. Maybe add a comment?

2021-04-14 09:42 UTC, agarciamontoro requested changes
I had skipped over the non-themed CSS before, because I assumed you were consciously not doing that until the design is finished. But it looks like some change here also broke the dark mode in the whole backstage:
![image](https://user-images.githubusercontent.com/3924815/114689551-190c2600-9d16-11eb-844a-2876fc22229d.png)

2021-04-14 14:56 UTC, cpoile commented on server/incident/service.go
> +	}
Good idea, don't know why I didn't do that originally. Done!

2021-04-14 14:56 UTC, cpoile commented on webapp/src/components/backstage/incidents/incident_backstage/overview/updates.tsx
> +            {statusPosts?.map((sp) => (
Thanks -- I've changed this around a bit too to handle the case where there's no status posts.

2021-04-14 14:56 UTC, cpoile commented on webapp/src/components/backstage/incidents/shared.tsx
> +`;
Ah, yes! But I should have removed all of that logic anyway. Fixed!

2021-04-14 14:56 UTC, cpoile commented on webapp/src/components/rhs/rhs_footer.tsx
> +    const incident = useSelector(currentIncident);
Thanks good catch! (was for a convenience 'go to backstage' button that I removed before submitting the PR)

2021-04-14 14:56 UTC, cpoile commented on webapp/src/hooks.ts
> +        dispatch(getProfilesInChannel(channelId, 0, PROFILE_CHUNK_SIZE));
200, which I thought would be enough. Should we get thousands just in case?

2021-04-14 14:56 UTC, cpoile commented on webapp/src/selectors.ts
> +}
Ok, done -- it's a function used in mm-redux (but which isn't exported) whenever a list of user profiles is returned by a selector. Here we're making our own selector (getProfileSetForChannel) so we have to populate the profiles before returning them.

2021-04-14 14:59 UTC, cpoile commented
@agarciamontoro Thanks! Fixed the css. The rest of the css is still WIP, will be done in a design-pass PR. Here's what it looks like for now:
![image](https://user-images.githubusercontent.com/1490756/114732131-4655d580-9d10-11eb-81f0-ab74b45298d1.png)
![image](https://user-images.githubusercontent.com/1490756/114732238-5bcaff80-9d10-11eb-9137-34bd51c059c3.png)
![image](https://user-images.githubusercontent.com/1490756/114732369-74d3b080-9d10-11eb-9616-ba72d61ad960.png)

2021-04-14 15:03 UTC, agarciamontoro commented on webapp/src/hooks.ts
> +        dispatch(getProfilesInChannel(channelId, 0, PROFILE_CHUNK_SIZE));
0/5 on the limit, just wondering whether we need to get *all* of them, regardless of the limit. Probably something to solve if there's a need to.

2021-04-14 15:03 UTC, agarciamontoro commented on webapp/src/selectors.ts
> +}
Oh, I see, thank you!

2021-04-14 15:04 UTC, agarciamontoro approved these changes
:tada:

2021-04-14 15:06 UTC, cpoile commented on webapp/src/hooks.ts
> +        dispatch(getProfilesInChannel(channelId, 0, PROFILE_CHUNK_SIZE));
@crspeller let me know what you think -- I don't think there's a way to "get all" other than using a crazy-high chunk size.

2021-04-19 14:06 UTC, crspeller approved these changes
Non blocking comments. Good work!

2021-04-19 14:06 UTC, crspeller commented on webapp/src/components/backstage/incidents/incident_backstage/overview/updates.tsx
> +    let updates: JSX.Element | JSX.Element[] = <EmptyBody>{'There are no updates available.'}</EmptyBody>;
Shouldn't typescript infer this type?

2021-04-19 14:06 UTC, crspeller commented on webapp/src/hooks.ts
> +        dispatch(getProfilesInChannel(channelId, 0, PROFILE_CHUNK_SIZE));
Probably make this clear that it doesn't get all the profiles in the channel. 
Just getting the first few really depends on context. If it's just to populate one of those profile selector boxes with search, then it's fine. But in other situations it might be unexpected. I think this just gets used in context where you don't really need every profile, right?

2021-04-19 14:23 UTC, cpoile commented on server/incident/incident.go
> +	Description string        `json:"description"`
Agreed, it's a bad name. It's only named `Description` to match the field we're using to store it in the incident struct/sql table. Otherwise I would have called it `CurrentSummary` or something like that. I didn't want to alter the table, so we're repurposing the `description` field.

2021-04-19 14:24 UTC, cpoile commented on webapp/src/components/backstage/incidents/incident_backstage/overview/updates.tsx
> +    let updates: JSX.Element | JSX.Element[] = <EmptyBody>{'There are no updates available.'}</EmptyBody>;
No, it would infer a single element, but below we might need to store an array of elements.

2021-04-19 14:25 UTC, crspeller commented on server/incident/incident.go
> +	Description string        `json:"description"`
@cpoile What's wrong with just altering the table?

2021-04-19 14:25 UTC, cpoile commented on client/incidents.go
> +func (s *IncidentsService) UpdateStatus(ctx context.Context, incidentID string, status Status, description, message string, reminderInSeconds int64) error {
From a previous review Jesse suggested we make the required fields be parameters, not an options struct -- that way we don't have to manually verify the required fields.

2021-04-19 14:28 UTC, cpoile commented on server/incident/incident.go
> +	Description string        `json:"description"`
@crspeller For speed. We originally wanted to get this out really quickly (before npm and circleCI delayed it), and we're not using the `description` field at all, so I just used it. I can make a new field if you really want, I'm only 1/5.

2021-04-19 14:57 UTC, crspeller commented on client/incidents.go
> +func (s *IncidentsService) UpdateStatus(ctx context.Context, incidentID string, status Status, description, message string, reminderInSeconds int64) error {
You can still pass "" to a function parameter though? Maybe I don't understand.
I guess if forces a break in the client every time we update? Maybe that's desirable to remember to update?

2021-04-19 15:00 UTC, cpoile commented on client/incidents.go
> +func (s *IncidentsService) UpdateStatus(ctx context.Context, incidentID string, status Status, description, message string, reminderInSeconds int64) error {
I think it's that, and it's like documentation. True, you could pass "", but then you're choosing to, and you will get the error from the server that you need to provide those. I guess it makes it more explicit, rather than just forgetting to fill in a field in the options (and not knowing which are required).

2021-04-19 19:39 UTC, merged