MM-34480 MM-34483 Configurable restrictions on who can create playbooks.
mattermost/mattermost-plugin-incident-collaboration pull request #522
Opened 2021-04-20 03:59 UTC by crspeller

#### Summary
@abhijit-singh @justinegeffen Asking for a quick review of UI / text. Might make follow up tickets for big UI changes (this stuff is rough)

Adds a settings tab to the backstage:
![image](https://user-images.githubusercontent.com/3191642/115334672-a86b6c00-a150-11eb-9795-be5b5e499342.png)

Within this view adds a setting for restricting who can create playbooks. Uses the same controls as automation. If the option is activated, anyone on the list will be able to create playbooks but nobody else on the server can. You also need to be on the list in order to edit who can create playbooks. (Expansion in the future to define playbook admins who can change this setting from the system console)
![image](https://user-images.githubusercontent.com/3191642/115334716-b7521e80-a150-11eb-96f0-72d5691b8559.png)

How it looks when you can't create a playbook: 
![image](https://user-images.githubusercontent.com/3191642/115335025-44957300-a151-11eb-9008-411257610665.png)

Can't create and you don't have any playbooks:
![image](https://user-images.githubusercontent.com/3191642/115335177-87574b00-a151-11eb-898b-e9f5e34ac491.png)

Informative message on settings page: 
![image](https://user-images.githubusercontent.com/3191642/115335334-d69d7b80-a151-11eb-95cf-226f1d49bb7f.png)

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-34480
https://mattermost.atlassian.net/browse/MM-34483

2021-04-22 09:40 UTC, agarciamontoro requested changes
Cool, thanks! I left some comments below

A couple of general considerations:
1. What happens when the user does not have permissions to create playbooks but directly navigates to `/playbooks/new`?
2. On permissions: thank you for the refactor there, it's really helpful! One thing I noticed for future PRs is that we should try to make them consistent: some of them return `error` and others return `bool`. They all should return the same.

2021-04-22 09:40 UTC, agarciamontoro commented on server/permissions/permissions.go
> +	}
I find it confusing that the functions in the `permissions` package modify their arguments. I'd rather add functions like `CanViewTeam`, `CanPostInChannel`... that abstract the actual permissions away, but keep the modifications on the API handler itself.

2021-04-22 09:40 UTC, agarciamontoro commented on webapp/src/types/actions.ts
> +export const RECIVED_GLOBAL_SETTINGS = pluginId + '_recived_global_settings';
Typo
```suggestion
export const RECEIVED_GLOBAL_SETTINGS = pluginId + '_received_global_settings';
```

2021-04-22 09:40 UTC, agarciamontoro commented on webapp/src/types/actions.ts
> +export interface RecivedGlobalSettings {
Typo
```suggestion
export interface ReceivedGlobalSettings {
```

2021-04-22 09:40 UTC, agarciamontoro commented on webapp/src/index.tsx
> +        // Grab gloal settings
Typo
```suggestion
        // Grab global settings
```

2021-04-22 09:40 UTC, agarciamontoro commented on webapp/src/hooks.ts
> +    });
Feel free(er) to ignore this one:

Maybe it makes sense to create a selector, instead of a hook?

```ts
export const currentUserCanCreatePlaybooks = createSelector(
    globalSettings,
    getCurrentUserId,
    (settings, userId) => {
        const playbookCreators = globalSettings?.playbook_editors_user_ids;
        if (!playbookCreators || playbookCreators.length === 0) {
            return true;
        }
        
        return playbookCreators.includes(userId);
    },
);

2021-04-22 09:40 UTC, agarciamontoro commented on webapp/src/components/backstage/settings.tsx
> +    const [enabled, setEnabled] = useState<boolean>(Boolean(props.settings.playbook_editors_user_ids) && props.settings.playbook_editors_user_ids?.length !== 0);
Can't this be simplified as follows (not sure, have not tested)?
```suggestion
    const [enabled, setEnabled] = useState<boolean>(Boolean(props.settings.playbook_editors_user_ids?.length !== 0));
```

2021-04-22 09:40 UTC, agarciamontoro commented on webapp/src/types/settings.ts
> +    playbook_editors_user_ids?: string[]
Wouldn't it simplify the code a bit if we make this field mandatory and default to an empty string when there is nothing?

2021-04-22 17:41 UTC, abhijit-singh reviewed
Worked on some changes to the UI for the Settings page & discussed them with @itao. Not sure if there'll be time to get these in. Open to feedback & suggestions.

Design link: https://www.figma.com/file/2EKxGlxlYFMkgXLQqv9cUz/Playbook-Permissions?node-id=4%3A605

![img](https://user-images.githubusercontent.com/14369607/115765680-b32e3700-a3c4-11eb-9cc7-4cc503977dd9.png)

The pattern for selecting and removing people can be the same one as currently used in Playbooks > Permissions (RHS) > Playbook access

@justinegeffen It'll be awesome if you can review the copy in these

2021-04-26 05:49 UTC, crspeller commented on server/api/api.go
> +	api.HandleFunc("/settings", handler.setSettings).Methods(http.MethodPost)
OK. Will do if that one gets merged first.

2021-04-26 05:49 UTC, crspeller commented on server/permissions/permissions.go
> +	}
You are right. I debated this and came to the wrong conclusion on if that was confusing or not.

2021-04-26 05:49 UTC, crspeller commented on webapp/src/hooks.ts
> +    });
I just find the hook method much clearer. Those `createSelector` things get out of hand fast. I find them super confusing.

2021-04-26 05:50 UTC, crspeller commented on webapp/src/components/backstage/settings.tsx
> +    const [enabled, setEnabled] = useState<boolean>(Boolean(props.settings.playbook_editors_user_ids) && props.settings.playbook_editors_user_ids?.length !== 0);
Nope, because `undefined !== 0` evaluates to `true`

2021-04-26 05:50 UTC, crspeller commented on webapp/src/types/settings.ts
> +    playbook_editors_user_ids?: string[]
Thank you for pointing this out!!! 
It lead me down the path to looking up how to deal with this elegantly in Typescript and lead to me learning about `Partial<T>`.

2021-04-26 08:50 UTC, agarciamontoro commented on webapp/src/hooks.ts
> +    });
Oh, that's interesting, I do find them pretty clear. Anyway, I was 0/5 on this, so I'm ok leaving as it is, thanks!

2021-04-26 08:50 UTC, agarciamontoro commented on webapp/src/components/backstage/settings.tsx
> +    const [enabled, setEnabled] = useState<boolean>(Boolean(props.settings.playbook_editors_user_ids) && props.settings.playbook_editors_user_ids?.length !== 0);
Urgh, that's true!

2021-04-26 09:15 UTC, justinegeffen reviewed
Thanks, @crspeller! I've added some additional review comments for existing content which hopefully tightens it up and adds some empathy. LMK your thoughts - happy to discuss further.

2021-04-26 09:15 UTC, justinegeffen commented on server/permissions/permissions.go
> +			"userID %s does not have permission to create playbook on teamID %s because they are a guest",
```suggestion
			"userID %s doesn't have permission to create a playbook on teamID %s because they're a guest",
```

2021-04-26 09:15 UTC, justinegeffen commented on server/permissions/permissions.go
> +			"userID %s does not have permission to create posts in the channel %s",
```suggestion
			"userID %s doesn't have permission to create posts in the channel %s",
```

2021-04-26 09:15 UTC, justinegeffen commented on server/permissions/permissions.go
> +			"userID %s does not have permission to create playbook on teamID %s",
```suggestion
			"userID %s doesn't have permission to create a playbook on teamID %s",
```

2021-04-26 09:15 UTC, justinegeffen commented on server/permissions/permissions.go
> +			"userID %s does not have permission to create posts in the channel %s",
```suggestion
			"userID %s doesn't have permission to create posts in the channel %s",
```

2021-04-26 09:15 UTC, justinegeffen commented on server/permissions/permissions.go
> +				"invited user with ID %s does not have permission to playbook's team %s",
```suggestion
				"invited user with ID %s doesn't have permission for playbook's team %s",
```

2021-04-26 09:15 UTC, justinegeffen commented on server/permissions/permissions.go
> +				"group %s does now allow references",
```suggestion
				"group %s does not allow references",
```

2021-04-26 09:15 UTC, justinegeffen commented on server/permissions/permissions.go
> +			"userID %s does not have permission to create posts in the channel %s",
```suggestion
			"userID %s doesn't have permission to create posts in the channel %s",
```

2021-04-26 09:15 UTC, justinegeffen commented on webapp/src/components/backstage/playbook_list.tsx
>              <Description>{'A playbook is a workflow template which must be created before an incident occurs. It defines the stages and tasks associated with an incident, as well as who can use playb
```suggestion
            <Description>{'A playbook is a workflow template which must be created before an incident occurs. It defines the checklists and tasks associated with an incident, as well as who can use playbook to start an incident.'}</Description>
```

2021-04-26 09:15 UTC, justinegeffen commented on webapp/src/components/backstage/playbook_list.tsx
> +            <DescriptionWarn>{'There are no playbooks and you do not have permissions to create playbooks on this server.'}</DescriptionWarn>
```suggestion
            <DescriptionWarn>{'You don't have permission to view and create playbooks on this server.'}</DescriptionWarn>
```
Is this strictly accurate? There may surely be playbooks but the viewer just can't see and create them because of permissions?

2021-04-26 09:15 UTC, justinegeffen commented on webapp/src/components/backstage/settings.tsx
> +                <NoPermissionsTitle>{'Playbook creation is currenty restricted to these users:'}</NoPermissionsTitle>
```suggestion
                <NoPermissionsTitle>{'Only the listed users can create playbooks:'}</NoPermissionsTitle>
```

2021-04-26 09:15 UTC, justinegeffen commented on webapp/src/components/backstage/settings.tsx
> +                    {'Only selected people can create playbooks'}
```suggestion
                    {'Only selected users can create playbooks.'}
```

2021-04-26 09:15 UTC, justinegeffen commented on webapp/src/components/backstage/settings.tsx
> +                    {'Everyone on the server can create playbooks'}
```suggestion
                    {'Everyone on the server can create playbooks.'}
```

2021-04-26 09:15 UTC, justinegeffen commented on webapp/src/components/backstage/settings.tsx
> +                message={'Are you sure you want to remove yourelf as a playbook creator? You will not be able to add yourself back.'}
```suggestion
                message={'When you remove yourself as a playbook creator you won't be able to add yourself back. Are you sure you'd like to perform this action?'}
```

2021-04-26 09:15 UTC, justinegeffen commented on webapp/src/components/backstage/stages_and_steps_edit.tsx
> +                <BackstageSubheaderDescription>{'Checklists allow you to group your tasks. Tasks are meant to be completed by members of the incident channel.'}</BackstageSubheaderDescription>
```suggestion
                <BackstageSubheaderDescription>{'Checklists are groups of tasks which are assigned to and completed by members of the incident channel.'}</BackstageSubheaderDescription>
```

2021-04-26 09:17 UTC, agarciamontoro approved these changes
Looking good, thank you! Some non-blocking comments below:

2021-04-26 09:17 UTC, agarciamontoro commented on server/api/playbooks.go
> +	}
Should this be in `permissions.PlaybookModify` too?

2021-04-26 09:17 UTC, agarciamontoro commented on webapp/src/components/backstage/settings.tsx
> +                message={'Are you sure you want to remove yourelf as a playbook creator? You will not be able to add yourself back.'}
Typo:
```suggestion
                message={'Are you sure you want to remove yourself as a playbook creator? You will not be able to add yourself back.'}
```

2021-04-26 09:17 UTC, agarciamontoro commented on server/api/playbooks.go
> +// This function modifys the pbook argument.
Typo:
```suggestion
// This function modifies the pbook argument.
```

2021-04-26 14:38 UTC, crspeller commented on webapp/src/components/backstage/playbook_list.tsx
> +            <DescriptionWarn>{'There are no playbooks and you do not have permissions to create playbooks on this server.'}</DescriptionWarn>
@justinegeffen 
Ya, there might be playbooks they can't view. 
> You don't have permission to view and create playbooks on this server.

Is not accurate because they have permission to view playbooks, but there just are none that they qualify to view at the moment. 

Perhaps:
```
There are no playbooks to view. You don't have permission create playbooks on this server.
```

2021-04-26 14:44 UTC, crspeller commented
@justinegeffen Thanks! Committed most of your suggestions. Only one comment on possible inaccuracy in the wording. 

BTW a lot of your comments where on error messages that don't get displayed to the user (only the admin). In the future you can save time by not reviewing those.

2021-04-26 14:56 UTC, crspeller commented on server/api/playbooks.go
> +	}
I don't think so, it's validation not permissions. Maybe we should factor out the validation too, especially considering this is duplicated. Separate PR though.

2021-04-26 15:03 UTC, crspeller commented
@abhijit-singh Awesome design! Really made me go "oh ya, that's how that should work"

How it looks in practice: 
![image](https://user-images.githubusercontent.com/3191642/116105081-d4fa1900-a665-11eb-9fb6-0e62ef50cf91.png)

2021-04-26 15:08 UTC, agarciamontoro commented on server/api/playbooks.go
> +	}
Makes sense, thanks!

2021-04-26 15:15 UTC, justinegeffen commented on webapp/src/components/backstage/playbook_list.tsx
> +            <DescriptionWarn>{'There are no playbooks and you do not have permissions to create playbooks on this server.'}</DescriptionWarn>
Nice suggestion, thanks! I've updated my suggestion. :)

2021-04-26 15:15 UTC, justinegeffen approved these changes

2021-04-26 15:18 UTC, cpoile approved these changes

2021-04-26 15:18 UTC, cpoile commented on server/api/api.go
> +	}
I think this is going to cause some confusion. When we're in the backstage it's at the team-level. I'm guessing people have come to expect that. But this setting is server-level. And it's right beside three other tabs (`Stats`, `Incidents`, `Playbooks`) that are team-level scoped. 

Not sure how to solve it, but is it something we should think about (if only to say "yah, it might cause confusion, but there's no other way")?

2021-04-26 15:18 UTC, cpoile commented on server/permissions/permissions.go
> +func isPlaybookCreator(userID string, cfgService config.Service) error {
Should this be named `isPlaybookEditor`?

2021-04-26 15:18 UTC, cpoile commented on webapp/src/components/backstage/select_users_below.tsx
> +}
nit: can we put props next to the function? (makes it easier to reference)

2021-04-26 15:18 UTC, cpoile commented on webapp/src/components/backstage/settings.tsx
> +        return dispatch(getProfiles(0, PROFILE_CHUNK_SIZE, {active: true}));
hehe, this chunk size again. Have we run into a problem where you won't be shown the profile you actually want to add?

2021-04-26 15:18 UTC, cpoile commented on webapp/src/index.tsx
> +        getStuff();
`getStuff`? :)

2021-04-26 15:36 UTC, crspeller commented on server/api/api.go
> +	}
Ya, it is a bit confusing. Basically we are going to switch everything to be "workspace" (server) scoped and this is just the first step. The end result will be more clear.

2021-04-26 15:40 UTC, crspeller commented on server/permissions/permissions.go
> +func isPlaybookCreator(userID string, cfgService config.Service) error {
Actually it's the setting that should change to creator. Good catch.

2021-04-26 15:41 UTC, crspeller commented on webapp/src/components/backstage/settings.tsx
> +        return dispatch(getProfiles(0, PROFILE_CHUNK_SIZE, {active: true}));
No because the expected flow is typing here.

2021-04-26 15:42 UTC, crspeller commented on webapp/src/index.tsx
> +        getStuff();
Huh. Maybe I was just annoyed I had to do a function to discard the async? 😆

2021-04-26 17:44 UTC, merged