MM-34775 Playbook open by default
mattermost/mattermost-plugin-incident-collaboration pull request #523
Opened 2021-04-20 04:12 UTC by crspeller

#### Summary
Modifies the playbook permissions to be in a tab. Creates a toggle to enable and disable playbook restrictions. Default to open. Admin privileges no longer apply to the restrictions. For now, works the same as it did before with only one level of permissions, everything or nothing. More granular permissions in the future. 

Draft only because this is based on https://github.com/mattermost/mattermost-plugin-incident-collaboration/pull/522

New Permissions tab:
![image](https://user-images.githubusercontent.com/3191642/115336136-70195d00-a153-11eb-9092-1eb0e4de8a66.png)

Adding restrictions:
![image](https://user-images.githubusercontent.com/3191642/115336185-87f0e100-a153-11eb-869d-75e90e279f24.png)

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-34483

2021-04-20 13:07 UTC, itao commented
Please request review from @justinegeffen as well for copy to clarify the feature. For example, it's currently not clear that by not hitting the toggle, everyone in the team can access it.

Btw @abhijit-singh I wanted to tag you for heads up. This pattern will likely be used in a bunch of additional places like incident permission and becomes a wee bit more complex when we expand to workspace-scope as opposed to the current team-scope. So it's worth more design input in the near future when we cross that bridge.

2021-04-20 13:11 UTC, itao commented
Why is the `Permissions` tab placed between `Preferences` and `Automations`?

If I think out loud from the user perspective of "how do I get the most value with least amount of work", I'd order them as
- Automation
- Preferences (which will soon be merged as Automations that are on by default)
- Tasks
- Permissions

2021-04-20 13:56 UTC, crspeller commented
@justinegeffen Tagging you on this. See @itao's comment. Maybe just expand the help text to include an explanation? I was hoping it would be clear by the disabled state that there was no restrictions unless activated. Hence "Enable access restriction". Maybe there is a more clear name for the toggle too?

2021-04-20 14:00 UTC, crspeller commented
@itao I was actually debating if it should go:

- Tasks
- Permissions
- Preferences
- Automation
or 
- Tasks
- Preferences
- Permissions
- Automation

I was thinking the natural order would be the most important to least important. So the tasks obviously wins there. Then it's probably preferences or permissions, then automatons are completely optional 0/5. I am 2/5 on tasks first though. Landing on Automation would be strange. Especially since once you have those setup you are probably not changing them often.

2021-04-22 10:14 UTC, agarciamontoro requested changes
Cool! Only concerned about the tests being removed.

I also think that disabling the setting to allow everyone to use the playbook is a bit confusing.

2021-04-22 10:14 UTC, agarciamontoro commented on server/sqlstore/playbook_test.go
> +		},*/
Are all the commented tests not valid anymore?

2021-04-22 14:46 UTC, crspeller commented on server/sqlstore/playbook_test.go
> +		},*/
Ya, those are testing if the Admin has their special powers, which this PR removes. One of the tests added makes sure they don't. 
I didn't remove them because I am a bit worried we will immediately backtrack on that.

2021-04-22 18:02 UTC, abhijit-singh commented
Suggesting some changes based on the UI recommended for Settings here (https://github.com/mattermost/mattermost-plugin-incident-collaboration/pull/522#pullrequestreview-642498335) and to make it clear what does it mean to 'not' restrict access.

Design link: https://www.figma.com/file/2EKxGlxlYFMkgXLQqv9cUz/Playbook-Permissions?node-id=6%3A998

<img width="1342" alt="01 04 - IM - New Playbook - Permissions" src="https://user-images.githubusercontent.com/14369607/115764143-d657e700-a3c2-11eb-8d3c-b77bec0718bb.png">

2021-04-26 15:30 UTC, crspeller commented
@abhijit-singh Awesome! Applied the tweaks here too.
![image](https://user-images.githubusercontent.com/3191642/116109426-99f9e480-a669-11eb-94bd-1f02cccc93ea.png)

2021-04-26 16:12 UTC, cpoile requested changes

2021-04-26 16:12 UTC, cpoile commented on webapp/src/components/backstage/share_playbook.tsx
> +    const currentTeamName = useSelector<GlobalState, string>((state: GlobalState) => getCurrentTeam(state).name);
I think when you use a function inside `useSelector` redux can't tell when it needs to refresh the component, so it does on every store state change.

2021-04-26 16:30 UTC, crspeller commented on webapp/src/components/backstage/share_playbook.tsx
> +    const currentTeamName = useSelector<GlobalState, string>((state: GlobalState) => getCurrentTeam(state).name);
Yup. Because the reference to the arrow function changes every time, we would have to re-run the selector when the redux store has not changed and see we got the same result. Modified to use a single function.

2021-04-26 17:31 UTC, cpoile approved these changes
Cool, thanks. The whole backstage is rerendering on any store change, so we need to fix something higher up in the hierarchy.

2021-04-28 17:12 UTC, agarciamontoro approved these changes
Looks good, thank you! :tada:

2021-04-28 18:11 UTC, merged