MM-32419 Auto send an outgoing webhook on incident archive
mattermost/mattermost-plugin-incident-collaboration pull request #526
Opened 2021-04-21 19:17 UTC by hakansa

#### Summary

Implementation of automated outgoing webhook when an incident archived.

Many thanks to @agarciamontoro for exhaustive help and support.  I've read a lot the PR https://github.com/mattermost/mattermost-plugin-incident-collaboration/pull/503  when I was working on this feature.

#### Changes in the Backstage

A new "When an incident archived" Section and Webhook component added.

<img width="650" alt="Screen Shot 2021-04-21 at 22 04 50" src="https://user-images.githubusercontent.com/43675540/115607386-9a9f1d80-a2ed-11eb-9b7a-2e82003a1f19.png">

<img width="650" alt="Screen Shot 2021-04-21 at 22 05 23" src="https://user-images.githubusercontent.com/43675540/115607450-ae4a8400-a2ed-11eb-828d-455e20a2944e.png">

#### Changes in the DB
- New columns in `IR_Playbook`:
    * `WebhookOnArchiveURL`, which contains the, ehem, webhook URL. 
    * `WebhookOnArchiveEnabled`, that stores the on/off state of the setting.
- New column in IR_Incident:
    * `WebhookOnArchiveURL`, which stores a copy of the data in the playbook's column when the incident is created. If the playbook's `WebhookOnArchiveEnabled` contains false, the data is not copied, so there's no need to add `WebhookOnArchiveEnabled` column to the `IR_Incident` table.

#### Tests
I tested that the webhook is sent and that the payload is correct in `server/incident/service_test.go`.
#### Ticket Link
https://mattermost.atlassian.net/browse/MM-32419

2021-04-21 19:17 UTC, mattermod commented
Hello @hakansa,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-04-22 07:50 UTC, agarciamontoro commented
Thank you for your contribution, @hakansa :tada: I'll try to review this today, tomorrow at the latest!

In the meanwhile: I see that the E2E tests are failing, do you know if they're failing also for you locally?

2021-04-22 08:08 UTC, hakansa commented
@agarciamontoro I'm not sure why e2e are failing.. I just added `webhookOnArchiveURL` to  `plugin_api_commands.js` and push it but tests are still failing. I'm looking for what the problem is.

2021-04-22 08:26 UTC, agarciamontoro commented
I'd suggest to first try if they are failing in your dev environment too, we've been having some problems with the E2E tests in CI and this may be another symptom of that problem.

For running them locally:
1. First, make sure you have your local server running with your version of the plugin installed.
2. Then, `cd` into `tests-e2e` and run `npm i` to install cypress. 
3. Finally, run `npm run cypress:open`. This will open Cypress, from where you can run the test files.

Try to run some of the tests that are failing on CI and see if they fail for you locally.

2021-04-22 08:40 UTC, hakansa commented
I'm getting `HTTP 401 Unauthorized` error for every test on Cypress. Should I add an user for cypress  like Username: `sysadmin` ?

2021-04-22 09:42 UTC, agarciamontoro commented
We are relying on test data on the server, sorry that I forgot to mention that!

In the mattermost-server repo, run `make test-data`. That should create the needed teams and users on which the E2E tests rely.

2021-04-22 11:07 UTC, hakansa commented
Actually I couldn't find any problem on e2e-tests.. Also I double checked my commits but I didn't see any piece of code that could break e2e tests..

2021-04-22 14:44 UTC, agarciamontoro commented
/update-branch

2021-04-22 14:44 UTC, agarciamontoro commented
Let's see if merging master fixes things!

2021-04-22 14:52 UTC, agarciamontoro commented
I'll check this locally tomorrow, E2E tests are always brittle!

2021-04-22 16:20 UTC, hakansa commented
@agarciamontoro Thanks! I will also try to look again..

2021-04-23 08:41 UTC, agarciamontoro commented
/update-branch

2021-04-23 10:02 UTC, agarciamontoro requested changes
Thank you very much for your work, @hakansa! :tada:

I left some suggestions below, mostly typos and some code refactoring issues, but otherwise it looks really good!

I've been taking a look at the E2E tests and, of course, the failures do not reproduce locally. Let's tackle that problem after you can address the changes requested here. I'm not entirely sure what's happening there.

2021-04-23 14:34 UTC, hakansa commented
@agarciamontoro hi again, I push new commits by considering your reviews.  Some tests were failed on CI (`test-MySQL57-Postgres10 `) , but these tests passing locally.

2021-04-23 16:33 UTC, agarciamontoro commented
Hm, it looks like you found a race condition, but it's actually happening on the other webhook. I cannot reproduce locally wither, but that's what race conditions do to us.

As for this PR, the same issue may affect your code too, let me see.

2021-04-23 17:23 UTC, agarciamontoro requested changes
Some extra changes to prevent more race conditions, and I think we're good to go!

2021-04-24 05:56 UTC, hakansa commented
@agarciamontoro thanks for suggestions.. I clearly understand what's happening there.. 
I pushed the new commits and it looks like tests will be OK!

2021-04-26 09:31 UTC, agarciamontoro requested changes
Amazing, @hakansa, thank you very much! :tada:

QA just found a bug with in my own implementation of the webhook on creation, and it reproduces here: if the UI toggle is disabled but an invalid URL was entered, the playbook cannot be created nor saved, so we need to change a couple of conditions in the API handlers. I left the suggestions below:

2021-04-26 09:31 UTC, agarciamontoro commented on server/api/playbooks.go
> +	if pbook.WebhookOnArchiveURL != "" {
QA just found a bug with this on my own implementation of the webhook on creation, and it reproduces here: if the UI toggle is disabled but an invalid URL was entered, the playbook cannot be created nor saved, so we need to change this condition:
```suggestion
	if pbook.WebhookOnArchiveEnabled {
```

2021-04-26 09:31 UTC, agarciamontoro commented on server/api/playbooks.go
> +	if pbook.WebhookOnArchiveURL != "" {
```suggestion
	if pbook.WebhookOnArchiveEnabled {
```

2021-04-26 11:08 UTC, hakansa commented
@agarciamontoro thanks for review.. I pushed the new commits..

2021-04-26 11:19 UTC, agarciamontoro commented on server/api/playbooks.go
> +	if pbook.WebhookOnArchiveURL != "" {
@hakansa: we also need it here, in the updatePlaybook function!

2021-04-26 11:29 UTC, hakansa commented on server/api/playbooks.go
> +	if pbook.WebhookOnArchiveURL != "" {
@agarciamontoro oops.. I push a  new commit to fix that.

2021-04-26 11:34 UTC, agarciamontoro approved these changes
Yay! :tada: Thank you very much for all your work on this, @hakansa, it will be really useful!

2021-04-26 19:09 UTC, cpoile requested changes
Great work and thank you @hakansa !

One small change (I think).

2021-04-26 19:09 UTC, cpoile commented on server/sqlstore/migrations.go
> +				}
I think these still need to be removed  from the 0.13->0.14, no?

2021-04-27 05:00 UTC, hakansa commented on server/sqlstore/migrations.go
> +				}
@cpoile  thanks! I'm not sure, the comment below is opposite of that.
https://github.com/mattermost/mattermost-plugin-incident-collaboration/pull/526#discussion_r619096213

2021-04-27 14:39 UTC, cpoile commented on server/sqlstore/migrations.go
> +				}
I think that comment is saying the same thing I'm saying -- you shouldn't modify previously existing migrations. You can assume previous migrations have already been run, so whatever you add will not be executed. Put whatever new columns/tables into a new separate migration. 

Make sense? Of course let me know if I'm misreading your code. :)

2021-04-27 15:38 UTC, hakansa commented on server/sqlstore/migrations.go
> +				}
@cpoile i think i couldn't explain myself properly, sorry for that..

You are absolutetly right. In my previous commits, i updated the previous migration function, and as @agarciamontoro  suggests, i write a new migration function ( from 0.14 to 0.15) and added the new column migrations there.

On the other hand, I forgot to remove my old additions to older migrate function..  I removed that blocks and push the new commits..

Thanks for your review!

2021-04-28 08:26 UTC, agarciamontoro commented on server/sqlstore/migrations.go
> +				}
Oh I had completely missed that, thank you for the second pair of eyes, @cpoile!

2021-04-28 12:37 UTC, cpoile approved these changes
Awesome, thanks @hakansa !

2021-04-28 12:37 UTC, cpoile commented
@agarciamontoro Should we invite Prapti now?

2021-04-28 17:28 UTC, agarciamontoro commented
Yes, we should!

2021-04-28 18:39 UTC, agarciamontoro commented
Last commit just fixes the conflicts we had with `api/playbooks`

2021-05-09 01:00 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2021-05-10 22:03 UTC, prapti commented
In test queue.

2021-05-19 10:03 UTC, hakansa commented
@prapti thanks! Are there any updates in here?

2021-05-20 00:00 UTC, prapti commented
Hi @hakansa! Sorry it took a while to get to this PR. I think it looks great except for one little clarification that I may need with regards to invalid webhook URL while archiving an incident -- I see that with an invalid URL, there is no notification in the incident channel that the outgoing webhook has failed when archiving the incident. In a similar scenario, the outgoing webhook 'when an incident starts' posts a message in the incident channel that "Incident creation announcement through the outgoing webhook failed. Contact your System Admin for more information." If this is an actual issue, honestly I think taking care of it in a different PR will be fine too.
@agarciamontoro thoughts? Not sure if this has already been discussed.

2021-05-20 14:40 UTC, agarciamontoro commented
@prapti, we should definitely have that warning if the request failed, but I see that the code is actually there: https://github.com/mattermost/mattermost-plugin-incident-collaboration/pull/526/files#diff-a3c78b2448c749821fb13b31a33b5b285db50d8f18c8991b165cb0b434434579R746 It doesn't work?

2021-05-21 01:12 UTC, prapti commented
@agarciamontoro Yeah, I don't see the 'invalid webhook' message coming through on archiving, only on incident start (seen in the screenshot below). The following was set up using the same invalid webhook `http://badwebhook` for both starting and archiving the incident:
![Screen Shot 2021-05-20 at 5 43 06 PM](https://user-images.githubusercontent.com/691331/119067428-e7325300-b996-11eb-8e85-79bc6561a0e8.png)

2021-05-21 07:41 UTC, agarciamontoro commented
Thanks for checking @prapti! @hakansa, could you take a look? I don't see any obvious error in the code, but something must be missing :thinking:

2021-05-21 17:05 UTC, hakansa commented
@agarciamontoro i've take a look but i couldn't see any obvious code..

2021-05-22 02:07 UTC, prapti commented
@hakansa @agarciamontoro Wondering if either of you can reproduce this issue if I had it tested incorrectly. Would you be willing to give this invalid webhook case a try?

2021-05-24 09:24 UTC, agarciamontoro requested changes

2021-05-24 09:24 UTC, agarciamontoro commented on server/incident/service.go
> +					_, _ = s.poster.PostMessage(incidentToModify.BroadcastChannelID, "Incident archived announcement through the outgoing webhook failed. Contact your System Admin for more information.")
The ID of the incident's channel is stored in the `ChannelID` field. The `BroadcastChannelID` field contains the ID of a channel where the incident creation is optionally broadcasted. That's why we were not seeing the error in the incident's channel:
 
```suggestion
					_, _ = s.poster.PostMessage(incidentToModify.ChannelID, "Incident archived announcement through the outgoing webhook failed. Contact your System Admin for more information.")
```

2021-05-24 09:35 UTC, hakansa commented on server/incident/service.go
> +					_, _ = s.poster.PostMessage(incidentToModify.BroadcastChannelID, "Incident archived announcement through the outgoing webhook failed. Contact your System Admin for more information.")
@agarciamontoro thanks for correction! I've pushed a new commit to fix that.

2021-05-24 10:06 UTC, agarciamontoro commented
@hakansa, if you can merge master and fix the conflicts, I think we will be able to merge this as soon as @prapti approves it! Thank you for all your effort here :pray:

2021-05-24 10:06 UTC, agarciamontoro approved these changes

2021-05-24 10:25 UTC, hakansa commented
@agarciamontoro thanks.. I've fixed some of the conflicts but I have to fix some linting problems etc. I will make a commit a few hours later and fix all of issues.

2021-05-24 10:31 UTC, agarciamontoro commented
Great, thank you, @hakansa!

2021-05-25 02:04 UTC, prapti commented
/update-branch

2021-06-05 01:00 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2021-06-09 10:47 UTC, agarciamontoro commented
Hi @hakansa! We just merged [a PR](https://github.com/mattermost/mattermost-server/issues/17317) that has created some more conflicts here. Would you mind taking a look at those? Sorry for the additional work!

2021-06-10 17:31 UTC, lieut-data commented
@hakansa, don't worry about the merge conflicts -- we'll tackle these while we finish up review. Thanks for your patience :)

2021-06-11 14:26 UTC, agarciamontoro commented
Hi again @hakansa! After we merged https://github.com/mattermost/mattermost-server/issues/17317, which sends an outgoing webhook on every status update, we realized its scope already covers the problem solved by your PR, which sends the outgoing webhook on the particular case of the status changing to Archived. After a discussion with the team, we decided that closing this PR is the best decision for the product, as merging it would mean having duplicated code that would need duplicated maintenance effort.

Of course, this is completely on me for not having identified the duplication of efforts before, and I am really really sorry that your hard work is not being merged. Please get in touch here or in community.mattermost.com (I'm @alejandro.garcia there) if you have any doubts, if you want to keep contributing, or simply if you want to have a quick chat with us! :)

By the way, I'm in touch with a colleague to try to get you some swag anyway, because in a normal scenario, we would have merged your PR, its quality is really good and it definitely needs some reward. We'll get back to you :)

2021-06-11 14:40 UTC, agarciamontoro commented
Yay, we got you a little something! Please, get in touch with me in https://community.mattermost.com/core/messages/@alejandro.garcia or through my email: alejandro dot garcia at mattermost dot com :)

2021-06-11 14:40 UTC, closed without merging