MM-35051 Experimental features flag
mattermost/mattermost-plugin-incident-collaboration pull request #535
Opened 2021-04-27 14:02 UTC by crspeller

#### Summary
Adding experimental features flag for users to turn on and off in the system console.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-35051

2021-04-27 14:07 UTC, cpoile requested changes

2021-04-27 14:07 UTC, cpoile commented on webapp/src/browser_routing.ts
> -    return `/${teamName}/${pluginId}/` + cleanPath;
Why removed?

2021-04-27 14:07 UTC, cpoile commented on webapp/src/hooks.ts
> +    return useSelector<GlobalState, boolean>((state: GlobalState) => Boolean(globalSettings(state)?.enable_experimental_features));
extract into a constant function (so it won't rerender on every global state change)?

2021-04-27 14:11 UTC, crspeller commented on webapp/src/hooks.ts
> +    return useSelector<GlobalState, boolean>((state: GlobalState) => Boolean(globalSettings(state)?.enable_experimental_features));
This is quite annoying. At it to the list of reasons why JS sucks and the reasons why redux sucks. 
Fixed the one above it too.

2021-04-27 14:14 UTC, cpoile approved these changes

2021-04-27 14:14 UTC, cpoile commented on webapp/src/hooks.ts
> +}
Can this be removed now completely? (use the selector instead?)

2021-04-27 14:16 UTC, crspeller commented on webapp/src/hooks.ts
> +}
I like the renaming. It make it more clear. See: https://kyleshevlin.com/use-encapsulation

2021-04-27 14:20 UTC, cpoile commented on webapp/src/hooks.ts
> +}
Except that blog is about encapsulating useEffects, which makes sense. Above you're encapsulating a single selector in a hook, why bother?  Up to you, but seems to be adding lines of code for no reason to me.

2021-04-27 16:07 UTC, lieut-data approved these changes
Looks good -- just a few comments below.

2021-04-27 16:07 UTC, lieut-data commented on server/config/configuration.go
> +	// PlaybookCreatorsUserIds is a list of users that can edit playbooks
```suggestion
	// EnableExperimentalFeatures determines if experimental features are enabled.
```

2021-04-27 16:07 UTC, lieut-data commented on webapp/src/hooks.ts
> +}
The pain point here seems to be the `<GlobalState, boolean>` -- how hard does TypeScript complain without this? (i.e. if you could write `useSelector(selectCanCreatePlaybooks)`, the hook doesn't seem justified.)

I'm guessing it's our use of redux-thunk that makes `GlobalState` typing a requirement, hence the otherwise unnecessary verbosity.

2021-04-28 21:34 UTC, crspeller commented on webapp/src/hooks.ts
> +}
It actually can infer the type here. 
But I see your point of it kinda just looking like a selector. I modified how the function was written to be more, custom hook like. Makes the behavior way more obvious.
Thanks for the nudge!

2021-04-29 14:34 UTC, merged

2021-04-29 14:35 UTC, crspeller commented on webapp/src/hooks.ts
> +}
Feel free to debate this if you still don't like my solution. I am up for a refactor PR :)