MM-32420 - Send a message when new incident member joins
mattermost/mattermost-plugin-incident-collaboration pull request #536
Opened 2021-04-28 19:57 UTC by cpoile

#### Summary
- When a user joins an incident channel the message is sent 10 seconds after (if it's sent right away it doesn't work).
- Heheh, I didn't read the ticket details and I called it `MessageOnJoin` -- let me know if anyone has a problem with that. :) (I'm a bad contributor)

#### Todo
- update migration and fix conflicts when #526 is merged

#### UX and Editing review
- @justinegeffen for the new automation tab labels, and the default template text.
- @abhijit-singh to review the automation tab style.  

![image](https://user-images.githubusercontent.com/1490756/116464533-15aa8b80-a83a-11eb-8ce3-b9f7a01a7cf4.png)

![image](https://user-images.githubusercontent.com/1490756/116464233-b9476c00-a839-11eb-8d02-122c724d72a1.png)

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-32420

2021-04-29 21:58 UTC, cpoile commented
requirements changed, needs more work

2021-05-06 20:00 UTC, cpoile commented
@crspeller @agarciamontoro Ready for review. Still waiting on final copy for the default welcome message from @justinegeffen.

2021-05-07 14:46 UTC, justinegeffen reviewed
Just a minor suggestion. But I have a question: Where is the help text that leads into this as an example? Similar to the content we provide for the incident status updates.

2021-05-07 14:46 UTC, justinegeffen commented on webapp/src/types/playbook.ts
> +export const defaultMessageOnJoin = 'Welcome. This channel was automatically created by an Incident Collaboration playbook. To view information about this incident, such as the commander\'s name, and
```suggestion
export const defaultMessageOnJoin = 'Welcome. This channel was automatically created by an Incident Collaboration playbook. To view information about this incident, such as the commander\'s name and list of tasks, select the shield icon in the channel header. You can also use the `/incident info` slash command.\n' +
```

2021-05-07 17:04 UTC, cpoile commented
@justinegeffen Yep, we can add that, but then that will actually be in the welcome message (if they choose to keep it as the default). Is that fine?

2021-05-07 17:11 UTC, justinegeffen commented
Thanks for clarifying! No that definitely won't work. :) Let's leave it as it is for now then?

2021-05-10 12:42 UTC, justinegeffen commented
@cpoile, re-reading that default message, as this is what is displayed when someone joins, should we make those URLs valid and provide a Mattermost docs/IC channel link instead of a placeholder?

2021-05-10 13:14 UTC, cpoile commented
@justinegeffen Yes please!

2021-05-10 13:23 UTC, justinegeffen commented on webapp/src/types/playbook.ts
> +    '`[Link to list of useful contacts](your-url-here)`\n' +
```suggestion
    '`[Mattermost Incident Collaboration channel](https://community.mattermost.com/core/channels/ee-incident-response)`\n' +
```

2021-05-10 13:28 UTC, justinegeffen commented on webapp/src/types/playbook.ts
> +    '`[Link to list of processes](your-url-here)`';
```suggestion
    '`[Incident Collaboration documentation](https://docs.mattermost.com/administration/devops-command-center.html)`';
```

2021-05-10 13:29 UTC, justinegeffen commented
@cpoile, done. I added them as comments for your approval and just in case I messed up any formatting inadvertently. :)

2021-05-10 16:26 UTC, crspeller requested changes

2021-05-10 16:26 UTC, crspeller commented on server/sqlstore/migrations.go
> +						INDEX     IR_ViewedChannel_ChannelID (ChannelID)
Maybe use a combined index on ChannelID and UserID since that's the main query?

2021-05-10 16:26 UTC, crspeller commented on webapp/src/websocket_events.ts
> +export const handleWebsocketChannelViewed = (getState: GetStateFunc, dispatch: Dispatch) => {
Does it maybe make more sense to have this logic in a redux store listener on channel change rather than listening for a websocket event? Given this behavior can be driven by the client. I am thinking this approach maybe makes less intuitive sense and adds latency.

2021-05-10 16:48 UTC, justinegeffen approved these changes

2021-05-10 17:21 UTC, cpoile commented on webapp/src/websocket_events.ts
> +export const handleWebsocketChannelViewed = (getState: GetStateFunc, dispatch: Dispatch) => {
@crspeller Having a bit of a delay is a good thing, in this case -- you want to make sure the user is seeing the channel and /then/ the ephemeral post is posted. But I'm fine with listening to the store, too. Do you think there would be any downsides to using the `currentChannelId` to detect a change?

2021-05-10 17:28 UTC, lieut-data commented on server/sqlstore/incident.go
> +// record of that userID/channelID (i.e., will create duplicate rows)
Can we avoid the duplicate rows? The query to check existence can be much faster if we assume uniqueness.

2021-05-10 17:28 UTC, lieut-data commented on server/sqlstore/incident.go
> +		Select("COUNT(*)").
Propose using `EXISTS` and a `UNIQUE` index that constrains this to only ever one row per channel and user.

2021-05-10 17:28 UTC, lieut-data commented on server/sqlstore/migrations.go
> +						INDEX     IR_ViewedChannel_ChannelID (ChannelID)
I think the index will basically be the same size as the table, but in creating it, you trade storage space for the knowledge that the database intends to query just a single row. See comments above, but otherwise agree with @crspeller on using a combined index.

2021-05-10 17:33 UTC, crspeller commented on webapp/src/websocket_events.ts
> +export const handleWebsocketChannelViewed = (getState: GetStateFunc, dispatch: Dispatch) => {
I think the current channel ID in redux should work.

2021-05-10 19:30 UTC, cpoile commented on server/sqlstore/incident.go
> +// record of that userID/channelID (i.e., will create duplicate rows)
Sounds good, done.

2021-05-10 19:33 UTC, cpoile commented on webapp/src/websocket_events.ts
> +export const handleWebsocketChannelViewed = (getState: GetStateFunc, dispatch: Dispatch) => {
@crspeller Now I'm not so sure I want to worry about the complications of listening to the redux store (#552). I think the websocket event is simpler.

2021-05-10 21:31 UTC, lieut-data commented on webapp/src/websocket_events.ts
> +export const handleWebsocketChannelViewed = (getState: GetStateFunc, dispatch: Dispatch) => {
I LOVE the idea of a redux store listener... mumble, mumble, saga ... but defer to what's pragmatic here :)

2021-05-10 21:35 UTC, lieut-data approved these changes
Nice! A few nits, but nothing blocking. (Note that I just reviewed the delta since my comments, not the whole review. If you want a more holistic look, let me know!)

2021-05-10 21:35 UTC, lieut-data commented on server/sqlstore/incident.go
> +		`SELECT EXISTS(SELECT *
Reading this now, I realize it might be easier to just `SELECT TRUE FROM ... ` to get the same result without the indentation. Probably need a pointer for `exists`, though. 0/5.

2021-05-10 21:35 UTC, lieut-data commented on server/sqlstore/incident.go
> +	if s.HasViewedChannel(userID, channelID) {
nit: This will catch many of the duplicate inserts, but not all of them. Another option is to `Insert` with a condition using the same query as `HasViewedChannel`. But even that won't guarantee anything, and one usually has to explicitly handle the unique constraint exception. 0/5 here, just commenting.

2021-05-11 14:56 UTC, cpoile commented on server/sqlstore/incident.go
> +	if s.HasViewedChannel(userID, channelID) {
@lieut-data Could you clarify why it wouldn't catch duplicate inserts? (Other than the obvious race condition possibility.) But regardless, we don't even technically need that check (or a conditional statement) -- a duplicate entry should return an error. (Correct me if I'm wrong, but that's what I've seen from the tests.)
I've made a commit so that returning an error (for a duplicate entry) is handled correctly.

2021-05-11 14:57 UTC, cpoile commented on server/sqlstore/incident.go
> +		`SELECT EXISTS(SELECT *
I just took this pattern from what a docs page suggested, but since you know more about this I'll defer to your expertise. Since you're 0/5 on it I'll assume you don't mind either way. :) So I'll keep it as it is.

2021-05-11 17:24 UTC, lieut-data commented on server/sqlstore/incident.go
> +		if strings.Contains(err.Error(), duplicateMsg) {
Can we do this by checking the error code in question, vs. string matching? For example, on MySQL see https://stackoverflow.com/questions/38493985/how-to-parse-mysql-error-golang. I think this is factored out as a helper function on the server code.

2021-05-11 20:29 UTC, cpoile commented on server/sqlstore/incident.go
> +		if strings.Contains(err.Error(), duplicateMsg) {
Good idea, done!

2021-05-11 21:09 UTC, cpoile commented on webapp/src/types/playbook.ts
> +        typeof arg.messageOnJoinEnabled === 'boolean';
Yes! Good catch!

2021-05-11 21:09 UTC, cpoile commented on webapp/src/types/actions.ts
> +export const SET_HAS_VIEWED_Channel = pluginId + '_set_has_viewed';
Nice catch (again)!

2021-05-11 21:09 UTC, cpoile commented on webapp/src/types/actions.ts
> +    hasViewed: boolean;
I just wanted to keep it flexible. I'm 0/5 if you're stronger I'll change it.

2021-05-11 21:10 UTC, cpoile commented
@agarciamontoro 
> P.S; You're a good contributor, I like the naming you came up with better than the one I suggested.

😂

2021-05-12 07:14 UTC, agarciamontoro commented on webapp/src/reducer.ts
> +const hasViewedByChannel = (state: Record<string, boolean> = {}, action: SetHasViewedChannel) => {
Oh no :( Thanks for the info!

2021-05-12 08:03 UTC, agarciamontoro commented on webapp/src/types/actions.ts
> +    hasViewed: boolean;
Up to you completely! It's just that I cannot imagine a situation where we want that boolean to be false, but if you do, I'm ok with it.

2021-05-12 08:03 UTC, agarciamontoro approved these changes
Thank you! :tada:

2021-05-12 14:05 UTC, merged