Update license to allow for extended usage
mattermost/mattermost-plugin-incident-collaboration pull request #540
Opened 2021-04-30 15:38 UTC by jamiehurewitz

Removed specific references to E20 so the tool can be used for limited purposes in other versions of the software.

#### Summary

#### Ticket Link

2021-04-30 16:08 UTC, lieut-data requested changes
This is terrific, @jamiehurewitz! One thought below.

2021-04-30 16:08 UTC, lieut-data commented on LICENSE
>  purposes, without requiring a subscription.  You agree that Mattermost and/or
```suggestion
the foregoing, you may copy and modify the Software for development and testing
purposes, without requiring a valid license or Subscription.  You agree that Mattermost and/or
```

2021-05-03 15:29 UTC, itao approved these changes

2021-05-03 15:57 UTC, lieut-data commented
@jamiehurewitz, from your perspective, is there anything else pending to move this from draft status and merging it?

2021-05-03 16:12 UTC, jamiehurewitz commented
This should be ready to go @lieut-data

2021-05-03 17:24 UTC, merged