MM32419: Auto send outgoing webhook on status update
mattermost/mattermost-plugin-incident-collaboration pull request #542
Opened 2021-05-03 15:19 UTC by madhavhugar

#### Summary

#### Ticket Link

2021-05-03 15:19 UTC, mattermod commented
Hello @madhavhugar,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-05-03 15:31 UTC, agarciamontoro commented
Thank you for this, @madhavhugar, we'll take a look as soon as we can!

2021-05-04 04:33 UTC, madhavhugar commented
@agarciamontoro looks like the e2e tests are failing because of lack of permissions, anything that can be done from my end to fix that?

2021-05-04 07:46 UTC, agarciamontoro commented
That's an error I'd never seen before, weird. I tried to re-run it manually, but no luck. I think it may be for some changes we are doing in the pipelines infrastructure. I'll get back to you when I know something else!

2021-05-04 08:03 UTC, agarciamontoro commented
/update-branch

2021-05-04 08:06 UTC, agarciamontoro commented
It looks like we were using an old docker image that was removed right after you opened the PR, but that's already fixed on the main branch, so just merging master should do the trick. Thanks for the heads-up!

2021-05-05 18:01 UTC, crspeller approved these changes
Looking good!

2021-05-06 08:35 UTC, agarciamontoro requested changes
This is really really cool! Thank you for your contribution, @madhavhugar, it will be really useful :tada:

I left a couple of minor comments below.

2021-05-06 08:35 UTC, agarciamontoro commented on server/api/playbooks.go
> +	if pbook.WebhookOnStatusUpdateURL != "" {
We should change this to the following, so we can actually save playbooks that have the setting disabled, even if the URL is wrong.

```suggestion
	if pbook.WebhookOnStatusUpdateEnabled {
```

2021-05-06 08:35 UTC, agarciamontoro commented on server/incident/service.go
> +	}
Good catch!

2021-05-06 08:35 UTC, agarciamontoro commented on server/incident/service.go
> +		},
Do we need to add this as a separate payload? Because it's already in `theIncident`, so I guess we're duplicating it here, right?

2021-05-06 08:35 UTC, agarciamontoro commented on server/incident/service.go
> +func (s *ServiceImpl) sendWebhookOnUpdateStatus(theIncident *Incident) error {
There's no need to pass a pointer here, I think. What do you think about passing it by value?

2021-05-06 08:35 UTC, agarciamontoro commented on server/incident/service.go
> +}
Cool refactor, thank you!

2021-05-06 08:35 UTC, agarciamontoro commented on server/sqlstore/incident.go
> +// CreateTimelineEvent creates the timeline event
Thanks!

2021-05-06 08:35 UTC, agarciamontoro commented on server/sqlstore/incident.go
> +// UpdateTimelineEvent updates (or inserts) the timeline event
And thanks again!

2021-05-06 08:35 UTC, agarciamontoro commented on server/sqlstore/migrations.go
> +		migrationFunc: func(e sqlx.Ext, sqlStore *SQLStore) error {
This looks good, but https://github.com/mattermost/mattermost-plugin-incident-collaboration/pull/526/files will probably be merged sooner, so you will need to move this to a migration from 0.15 to 0.16. I'll ping you when that's needed, no worries!

2021-05-06 08:35 UTC, agarciamontoro commented on server/sqlstore/playbook.go
> +			"WebhookOnCreationURL", "WebhookOnCreationEnabled", "WebhookOnStatusUpdateURL", "WebhookOnStatusUpdateEnabled").
Can you move this to another line?
```suggestion
			"WebhookOnCreationURL", "WebhookOnCreationEnabled",
			"WebhookOnStatusUpdateURL", "WebhookOnStatusUpdateEnabled").
```

2021-05-06 08:35 UTC, agarciamontoro commented on webapp/src/components/backstage/automation/webhook.tsx
> +export const Webhook: FC<Props> = (props: Props) => (
This will also conflict with https://github.com/mattermost/mattermost-plugin-incident-collaboration/pull/526/files#diff-905c0f515dd19d445500217b98ac49fb422cbeade4d21f18427335b895825aba. I'll also ping you when needed!

2021-05-14 13:13 UTC, madhavhugar commented on server/incident/service.go
> +		},
Yes, we are duplicating it. It was to indicate explicitly that the status has been updated. Also, in a way to differentiate between a created and an updated payload. 

Should we avoid the duplication?

2021-05-16 09:42 UTC, madhavhugar commented on server/incident/service.go
> +func (s *ServiceImpl) sendWebhookOnUpdateStatus(theIncident *Incident) error {
agreed 💯

2021-05-17 09:00 UTC, agarciamontoro commented on server/incident/service.go
> +		},
I think we should avoid the duplication, and tackle the problem of differentiating the different webhooks independently. Maybe we could add an "event" field or something similar, but we can tackle that in a separate PR.

2021-05-20 14:38 UTC, agarciamontoro requested changes
Thank you for keeping this in sync, @madhavhugar! I left a couple more comments, and we still need to remove the duplication of the fields in the struct sent with the webhook.

Thank you :tada:

2021-05-23 19:27 UTC, madhavhugar commented on server/incident/service.go
> +		},
makes sense ➕1
I've updated the payload to avoid duplication

2021-05-24 11:15 UTC, agarciamontoro approved these changes
Thank you for all your work on this, @madhavhugar :tada: It looks good to me!

Now it's time for QA to review it!

A piece of feedback for next PRs: we usually do not force-push anything to an already open PR, but instead just keep adding commits. When merging, we squash all commits into one, so there is no need to worry for having a long list of commits with several changes. This way makes it easier for the reviewers to see the incremental changes.

2021-06-03 01:53 UTC, prapti approved these changes
This PR is looking great. Tested with valid and invalid outgoing webhook URLs during incident channel update (including reopening the incident), and things are working as expected.
Approving.
Thank you for this contribution @madhavhugar!

2021-06-09 10:40 UTC, agarciamontoro commented
Took another quick look and everything looks great. Thank you very much, @madhavhugar, great job!

2021-06-09 10:41 UTC, merged