MM-35041 MM-35042 Basic retrospective tab and infrastructure
mattermost/mattermost-plugin-incident-collaboration pull request #544
Opened 2021-05-05 00:54 UTC by crspeller

#### Summary
Infrastructure for the backstage retrospective tab. This is all behind the experimental features flag for now. All this is is the tab and and editable field in the backstage. Pressing the save button will save a "draft" that you can't do anything with for now. 

Thanks to @cpoile for the client framework and timeline which is the basis for this PR. 

FYI and feedback appreciated @itao @abhijit-singh 

#### Where we are
- **Placeholder Elements**
- **Basic saving of retrospective** <-- We are here
- Ability to publish retrospective
- Reminder to fill out retrospective
- Templating retrospective report
- Configurable persistant reminders
- Polish

#### Retrospective tab:
![image](https://user-images.githubusercontent.com/3191642/117082010-f5754380-acf5-11eb-8e4a-97b40c467432.png)

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-35041
https://mattermost.atlassian.net/browse/MM-35042

2021-05-05 15:42 UTC, lieut-data requested changes
Nice! Love that we can iterate "safely" under the experimental flag. A few comments below.

2021-05-05 15:42 UTC, lieut-data commented on server/incident/incident.go
> +	Retrospective           string               `json:"retrospective"`
I'd love to see this modelled in a separate table. It's not super obvious that I'd want to query the retrospective for an incident quite like this, and I think there's a potential that retrospectives might not always be tied to an incident.

2021-05-05 15:42 UTC, lieut-data commented on server/telemetry/rudder.go
> +	properties := taskProperties(incidentID, userID)
Why `taskProperties` and not `incidentProperties`?

2021-05-05 15:42 UTC, lieut-data commented on webapp/src/components/backstage/incidents/incident_backstage/retrospective/profile_vertical.tsx
> +        profileUri = Client4.getProfilePictureUrl(props.userId, user.last_picture_update);
nit: while `uri` is technically more correct, I fear it's extra cognitive load to just using `url`.

2021-05-05 15:42 UTC, lieut-data commented on webapp/src/components/backstage/incidents/incident_backstage/retrospective/timeline.tsx
> +            {
nit: worth merging this to the previous to avoid unnecessary indents?

2021-05-05 15:42 UTC, lieut-data commented on webapp/src/components/backstage/incidents/incident_backstage/retrospective/timeline_retro.tsx
> +    const displayPreference = useSelector<GlobalState, string | undefined>(getTeammateNameDisplaySetting) || 'username';
Ugh, I despise the constant need to resolve the display name setting. Would love to "fix" this in Redux at some point :)

2021-05-05 15:42 UTC, lieut-data commented on webapp/src/components/backstage/incidents/incident_backstage/retrospective/timeline_retro.tsx
> +    const getStateFn = useStore().getState;
Something smells "off" here -- it shouldn't normally be necessary to access the state like this. Can you elaborate?

2021-05-05 15:42 UTC, lieut-data commented on webapp/src/components/backstage/incidents/incident_backstage/retrospective/timeline_retro.tsx
> +                const ret = await getUserFn(e.subject_user_id) as { data?: UserProfile, error?: any };
Is there an opportunity to fetch users in bulk vs. firing off a request per user?

2021-05-05 20:36 UTC, crspeller commented on webapp/src/components/backstage/incidents/incident_backstage/retrospective/timeline_retro.tsx
> +    const displayPreference = useSelector<GlobalState, string | undefined>(getTeammateNameDisplaySetting) || 'username';
Yes I hate this so much.

2021-05-05 20:45 UTC, crspeller commented on webapp/src/components/backstage/incidents/incident_backstage/retrospective/timeline_retro.tsx
> +    const getStateFn = useStore().getState;
I don't understand this. Since this code was copy pasted by ChrisP from the RHS I am hesatent to start modifying it here. Ticket to resolve this and the following comment: https://mattermost.atlassian.net/browse/MM-35475

2021-05-05 20:45 UTC, crspeller commented on webapp/src/components/backstage/incidents/incident_backstage/retrospective/timeline_retro.tsx
> +                const ret = await getUserFn(e.subject_user_id) as { data?: UserProfile, error?: any };
https://mattermost.atlassian.net/browse/MM-35475

2021-05-05 20:45 UTC, crspeller commented on webapp/src/components/backstage/incidents/incident_backstage/retrospective/timeline.tsx
> +            {
Yup.

2021-05-05 20:45 UTC, crspeller commented on webapp/src/components/backstage/incidents/incident_backstage/retrospective/profile_vertical.tsx
> +        profileUri = Client4.getProfilePictureUrl(props.userId, user.last_picture_update);
Yup. Also fixed the logic a bit. Added a comment to make sure people know this is a stub component.

2021-05-05 20:45 UTC, crspeller commented on server/telemetry/rudder.go
> +	properties := taskProperties(incidentID, userID)
Because... I copy pasted that.

2021-05-05 21:05 UTC, crspeller commented on server/incident/incident.go
> +	Retrospective           string               `json:"retrospective"`
I am hesitant to add the complexity of a new table and another join. Right now I have seen no plans for multiple retrospectives. 
Are you OK with this for now and seeing how the design evolves? Or do you have a strong feeling we are going to need a table? A whole separate object?

2021-05-06 09:23 UTC, agarciamontoro requested changes
Looks good! I really like that the experimental features setting allow us to ship in-progress stuff <3 Btw, I had the setting disabled, so I enabled it, but then I went to the incident overview page and the Retrospective tab did not show up until I refreshed the page.

Also, a minor UI thing with dark themes, maybe worth fixing it here:
![image](https://user-images.githubusercontent.com/3924815/117274448-59fee280-ae5d-11eb-93cf-9e8fddf755f2.png)

2021-05-06 09:23 UTC, agarciamontoro commented on webapp/src/components/backstage/incidents/incident_backstage/retrospective/report.tsx
> +        setTimeout(() => setSaved(false), 1000);
This is for changing the text from `Saved!` back to `Save Draft` in one second? Why do we need that?

2021-05-06 09:23 UTC, agarciamontoro commented on webapp/src/components/backstage/incidents/incident_backstage/retrospective/timeline_retro.tsx
> +    const displayPreference = useSelector<GlobalState, string | undefined>(getTeammateNameDisplaySetting) || 'username';
Hating this is indeed a general feeling.

2021-05-06 09:23 UTC, agarciamontoro commented on webapp/src/components/backstage/incidents/incident_backstage/retrospective/report.tsx
> +        setTimeout(() => setSaved(false), 1000);
I realized that this may be one of the in-progress features.

2021-05-06 16:16 UTC, lieut-data commented on server/incident/incident.go
> +	Retrospective           string               `json:"retrospective"`
I'm less concerned about the table than if fetching `/incidents/blah` will also return a big markdown blob. I /feel/ like this is more of a "document" than a property of the incident.

2021-05-06 21:55 UTC, crspeller commented on server/incident/service.go
> +	s.telemetry.PublishRetrospective(incidentToPublish, publisherID)
I don't think it matters to just leave it there. Next PR will be implementing that.

2021-05-06 21:57 UTC, crspeller commented on server/telemetry/rudder.go
> +
Ok.

2021-05-06 21:58 UTC, crspeller commented on webapp/src/components/backstage/incidents/incident_backstage/retrospective/report.tsx
> +        setTimeout(() => setSaved(false), 1000);
Yes the UX will be improved here.

2021-05-06 22:35 UTC, crspeller commented on server/incident/incident.go
> +	Retrospective           string               `json:"retrospective"`
I feel like doing that would be a bit of over-optimization at this point. I agree that it's a better overall design, I just don't know where retrospectives are going at this point. What if suddenly they need to be in the RHS? Then the optimization of only fetching them sometimes was pointless. 

Maybe this is an item for the new Monday meeting?

2021-05-07 14:05 UTC, lieut-data approved these changes

2021-05-11 18:50 UTC, merged