MM-17468: Accept a number of days instead of two date arguments in `/incident test bulk-data`
mattermost/mattermost-plugin-incident-collaboration pull request #549
Opened 2021-05-07 04:28 UTC by alankan886

#### Summary
This PR is for simplifying two date arguments in `/incident test bulk-data` into one number argument. Instead of `/incident test bulk-data 10 3 2020-01-31 2020-11-22 2`, now it's `/incident test bulk-data 10 3 342 2`. And the number of days is expected to be larger than 0.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/17468

2021-05-07 04:28 UTC, mattermod commented
Hello @alankan886,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2021-05-07 04:32 UTC, alankan886 commented
/check-cla

2021-05-07 04:37 UTC, alankan886 commented
/check-cla

2021-05-07 07:23 UTC, agarciamontoro commented
/update-branch

2021-05-07 07:28 UTC, agarciamontoro commented
Thank you for your contribution, @alankan886 :tada: We will review it as soon as we can!

2021-05-07 12:29 UTC, cpoile approved these changes
Looks good to me from a code standpoint, thanks @alankan886 !

2021-05-07 12:29 UTC, cpoile commented on server/command/command.go
> +		r.warnUserAndLogErrorf("unable to parse in location on time.Now(): %v", err)
```suggestion
		r.warnUserAndLogErrorf("unable to parse in location on time.Now().AddDate: %v", err)
```

2021-05-08 01:11 UTC, alankan886 commented
Thank you for the comment @cpoile! The suggested change is made and pushed.

2021-05-12 09:20 UTC, agarciamontoro requested changes
Thank you, @alankan886, it looks great! :tada:

I left some suggestions below.

2021-05-12 09:20 UTC, agarciamontoro commented on server/command/command.go
>  		testData.AddTextArgument("Date in format 2020-01-31", "First possible creation date", "")
We also need to update these descriptions. We need to modify this one as shown here and remove the next line

```suggestion
		testData.AddTextArgument("An integer n. The incidents generated will have a start date between n days ago and today.", "Range of days for the incident start date", "")
```

@justinegeffen may have a better wording for this.

2021-05-12 09:24 UTC, agarciamontoro commented
@itao, I think it is ok getting rid of the old way of creating the test incidents and use instead just a number of days. What this means effectively is that it will be much easier to specify the number of days you want the incidents to go back (you just write that number), but also that it is now impossible to specify an end date, so the range will always be `[n days ago, today]`, with the range always ending in the day the test command is executed.

Is that ok? Or do we want to maintain the old way of generating this data?

2021-05-13 00:22 UTC, alankan886 commented on server/command/command.go
> +	begin, err := time.ParseInLocation("2006-01-02", time.Now().AddDate(0, 0, -days).Format("2006-01-02"), time.Now().Location())
Hello, not sure if this matters, but they are slightly different where `time.ParseInLocation()` would give `2021-05-12 00:00:00` (no specific time) and `time.Now()` would give `2021-05-12 19:53:00.596493` (specific time). If you don't mind the differences, I'm happy to change them. Let me know if you have any thoughts on this!

2021-05-13 08:15 UTC, agarciamontoro commented on server/command/command.go
> +	begin, err := time.ParseInLocation("2006-01-02", time.Now().AddDate(0, 0, -days).Format("2006-01-02"), time.Now().Location())
We do not need a high specificity here, as the dates will be picked randomly in the range of dates. So I'd vote for making the code more readable using just `time.Now()`.

2021-05-14 13:11 UTC, itao approved these changes
This is awesome! It makes the command one-clickable in a playbook which is helpful for the customer demo playbook. Nice!

2021-05-14 13:50 UTC, agarciamontoro commented
/update-branch

2021-05-14 13:55 UTC, agarciamontoro approved these changes
This is great, @alankan886, thank you very much! Skipping QA as it is an internal, testing command.

2021-05-14 14:41 UTC, merged