MM-35044 Ability to publish retrospective
mattermost/mattermost-plugin-incident-collaboration pull request #557
Opened 2021-05-14 18:45 UTC by crspeller

#### Summary
- Adds the ability to publish the retrospective, along with some minor improvements to saving. 
- Moves to using router for incident backstage tabs to support linking directly to retrospective.

#### Where we are
- **Placeholder Elements**
- **Basic saving of retrospective** 
- **Ability to publish retrospective** <-- We are here
- Reminder to fill out retrospective
- Templating retrospective report
- Configurable persistant reminders
- Polish

#### Screenshots
In a state where the retrospective has already been published (button says published if not already published):
![image](https://user-images.githubusercontent.com/3191642/118304921-27c43500-b49c-11eb-80e6-4e28d6119401.png)
Pressing edit gets you markdown:
![image](https://user-images.githubusercontent.com/3191642/118305040-4aeee480-b49c-11eb-9144-7ab8cd73e36e.png)
Published retrospective, link leads to retrospective in backstage. 
![image](https://user-images.githubusercontent.com/3191642/118305122-6bb73a00-b49c-11eb-9d6b-75df6e7dee9a.png)

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-35044

#### Checklist
[x] Telemetry updated
[x] Gated by experimental feature flag
[x] Unit tests updated

2021-05-14 18:46 UTC, crspeller commented
@justinegeffen Specifically looking for feedback on the text at the top of the retrospective report published in the channel. Thanks!

2021-05-17 08:03 UTC, agarciamontoro approved these changes
Looks perfect, nothing blocking from my side!

P.S.: I'm loving this series of smaller PRs instead of a huge one, it's much easier to review.

2021-05-17 17:47 UTC, crspeller commented on server/incident/service.go
> +	}
Yes. I was surprised as well, but it works.

2021-05-17 17:48 UTC, crspeller commented on webapp/src/components/backstage/incidents/incident_backstage/retrospective/report.tsx
> +    const [publishedThisSession, setPublishedThisSession] = useState(false);
No I added the "This session" as a hint that it's not persisted. It just turns the button to say published until you leave and come back. Then it says re-publish.

2021-05-17 20:22 UTC, cpoile requested changes
Awesome! Just minor questions.

2021-05-17 20:22 UTC, cpoile commented on server/incident/incident.go
> +	RetrospectivePublished  int64                `json:"retrospective_published"` // The last time a retrospective was published. 0 if never published.
propose "RetrospectivePublishedAt" to match the other time fields?

2021-05-17 20:22 UTC, cpoile commented on webapp/src/components/backstage/incidents/incident_backstage/incident_backstage.tsx
> -    min-height: 100vh;
Have you tested that this (and the css change above) don't mess up the backgrounds on the other backstage pages? (just in case)

2021-05-17 20:22 UTC, cpoile commented on webapp/src/components/backstage/incidents/incident_backstage/incident_backstage.tsx
> +    && {
just curious if we /need/ the `&& {`? Can't you just add the new css without it?

2021-05-17 20:22 UTC, cpoile commented on webapp/src/components/backstage/incidents/incident_backstage/incident_backstage.tsx
> +                    </Switch>
nice 👍

2021-05-18 16:49 UTC, crspeller commented on webapp/src/components/backstage/incidents/incident_backstage/incident_backstage.tsx
> +    && {
Tested, it's necessary. It has to override some webapp styling I think.

2021-05-18 16:49 UTC, crspeller commented on server/incident/incident.go
> +	RetrospectivePublished  int64                `json:"retrospective_published"` // The last time a retrospective was published. 0 if never published.
Makes sense.

2021-05-18 16:53 UTC, crspeller commented on webapp/src/components/backstage/incidents/incident_backstage/incident_backstage.tsx
> -    min-height: 100vh;
Yup. The other pages look fine to me.

2021-05-18 19:48 UTC, cpoile approved these changes
Great! (with one more little change, which I think we should do, but up to you)

2021-05-18 19:48 UTC, cpoile commented on server/incident/incident.go
> +	RetrospectivePublishedAt int64                `json:"retrospective_published"` // The last time a retrospective was published. 0 if never published.
also? (and related webapp changes needed)
(sorry)

```suggestion
	RetrospectivePublishedAt int64                `json:"retrospective_published_at"` // The last time a retrospective was published. 0 if never published.
```

2021-05-18 19:48 UTC, crspeller commented on server/incident/incident.go
> +	RetrospectivePublishedAt int64                `json:"retrospective_published"` // The last time a retrospective was published. 0 if never published.
Ack! of course.

2021-05-18 20:30 UTC, justinegeffen reviewed
Just one suggestion - otherwise reads well to me. :)

2021-05-18 20:30 UTC, justinegeffen commented on webapp/src/components/backstage/incidents/incident_backstage/retrospective/report.tsx
> +        publishButtonText = 'Re-Publish';
```suggestion
        publishButtonText = 'Republish';
```

2021-05-19 14:48 UTC, merged