MM-35046 MM-35043 Reminders to fill in the retrospective
mattermost/mattermost-plugin-incident-collaboration pull request #566
Opened 2021-05-20 13:38 UTC by crspeller

#### Summary
When an incident is resolved, a reminder will be sent to fill in the retrospective report

#### Where we are
- **Placeholder Elements**
- **Basic saving of retrospective** 
- **Ability to publish retrospective** 
- **Reminder to fill out retrospective**
- **Configurable persistent reminders**  <-- We are here
- Templating retrospective report
- _NEW:_ Replace reminder message with custom message for interactivity.
- _NEW:_ Add ability to disable retrospectives at playbook level.
- Polish

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-35043
https://mattermost.atlassian.net/browse/MM-35046

#### Checklist
~~[ ] Telemetry updated~~
[x] Gated by experimental feature flag
[x] Unit tests updated

2021-05-20 13:41 UTC, crspeller commented on server/incident/reminder.go
> +const RetrospectivePrefix = "retro_"
@cpoile Interested in your opinion on how I ended up using the reminder functionality.

2021-05-20 13:41 UTC, crspeller commented on server/incident/reminder.go
> +	// Jobs can't be rescheduled within themselves with the same key. As a temporary workaround do it in a delayed goroutine
This isn't ideal. This is done because rescheduling a reminder within the callback doesn't work as the reminder is removed after the callback is invoked. 
@cpoile Does a ticket make sense to fix this, or am I missing something?

2021-05-20 20:02 UTC, cpoile requested changes
Nice!

2021-05-20 20:02 UTC, cpoile commented on server/playbook/playbook_test.go
> +			expected: []byte(`"checklists":[]`),
A little confused why this changed so much (and only checklists was left)?

2021-05-21 15:43 UTC, crspeller commented on server/incident/service.go
> +	incidentToCancel.RetrospectivePublishedAt = now
I could have a separate field that indicates that the retrospective was canceled.
This way it's like you are publishing the fact that it's canceled. 
Hmm... but what if you wanted to filter by which ones are canceled? Sounds like I need a field. Will add one.

2021-05-21 15:44 UTC, crspeller commented on server/playbook/playbook_test.go
> +			expected: []byte(`"checklists":[]`),
Changed the test so it doesn't take so much maintenance. Just checks for contains.

2021-05-21 15:56 UTC, crspeller commented on server/incident/reminder.go
> +	// Jobs can't be rescheduled within themselves with the same key. As a temporary workaround do it in a delayed goroutine
The problem with that is then I need to keep track of attempt_1 attempt_2 etc.
But if the suffixing is the solution, maybe we can just build that in. It also would be nice to have a separate data field so the key didn't have to be the data too. 
Made a ticket for that here: https://mattermost.atlassian.net/browse/MM-35938

2021-05-21 18:23 UTC, cpoile commented on server/incident/reminder.go
> +	// Jobs can't be rescheduled within themselves with the same key. As a temporary workaround do it in a delayed goroutine
Why do you need to keep track of attempt_1, attempt_2, etc? You only have to send in the parsed attempt number and set the next attempt (attempt + 1) and then return from this one. No need to keep track. Or if you don't want to parse, you could use a uuid after the `retro_incidentid_` bit.

For https://mattermost.atlassian.net/browse/MM-35938 -- personally, I think we should keep that kind of complexity out of the jobOnce scheduler, and let consumers decide how they want to handle it.

2021-05-24 10:42 UTC, agarciamontoro approved these changes
Great work! Only non-blocking comments below. Thank you :)

2021-05-24 10:42 UTC, agarciamontoro commented on server/incident/incident.go
> +	RetrospectiveReminderIntervalSeconds int64                `json:"retrospective_reminder_interval_seconds"`
Super nit: Can we group all retrospective fields together?
```suggestion
	RetrospectiveWasCanceled             bool                 `json:"retrospective_was_canceled"`
	RetrospectiveReminderIntervalSeconds int64                `json:"retrospective_reminder_interval_seconds"`
	MessageOnJoin                        string               `json:"message_on_join"`
```

2021-05-24 10:42 UTC, agarciamontoro commented on server/incident/reminder.go
> +	// Jobs can't be rescheduled within themselves with the same key. As a temporary workaround do it in a delayed goroutine
I think I'm with @cpoile here: unless I'm missing something obvious, it looks easy to just schedule a new one.

2021-05-24 10:42 UTC, agarciamontoro commented on server/incident/service.go
> +		previousStatus != StatusResolved &&
This is good. Although it makes me wonder whether updating the status (from Active to Resolved, for example) and posting a status update (as in writing what's going on) should be two clearly separated processes, so it would not be possible to update the status from Resolved to Resolved. Definitely for the future, not this PR, but I think it's worth giving it a second thought.

2021-05-24 10:42 UTC, agarciamontoro commented on server/incident/service.go
> +		s.scheduler.Cancel(RetrospectivePrefix + incidentID)
Why do we need this `Cancel` here?

2021-05-24 10:42 UTC, agarciamontoro commented on webapp/src/components/backstage/playbook_edit.tsx
> +                                                    retrospective_reminder_interval_seconds: option ? option.value : option,
Is this different than the following?
```suggestion
                                                    retrospective_reminder_interval_seconds: option?.value,
```

2021-05-24 10:42 UTC, agarciamontoro commented on webapp/src/types/incident.ts
> +    retrospective_was_canceled: boolean;
Is this interface missing the `retrospective_reminder_interval_seconds` field?

2021-05-27 14:11 UTC, cpoile commented on server/incident/service.go
> +		s.scheduler.Cancel(RetrospectivePrefix + incidentID)
hmm, good question, didn't notice that.

2021-06-01 16:05 UTC, crspeller commented on server/incident/service.go
> +		previousStatus != StatusResolved &&
Ya. I think the idea is actually to remove all the extra statuses. So decoupling will make sense then.

2021-06-01 16:13 UTC, crspeller commented on server/incident/service.go
> +		s.scheduler.Cancel(RetrospectivePrefix + incidentID)
Because you can't reschedule without canceling the existing one.

2021-06-01 16:44 UTC, crspeller commented on webapp/src/types/incident.ts
> +    retrospective_was_canceled: boolean;
Yup, but we never use that on the client.

2021-06-01 16:55 UTC, crspeller commented on server/incident/reminder.go
> +	// Jobs can't be rescheduled within themselves with the same key. As a temporary workaround do it in a delayed goroutine
I could schedule a new one. But now I need to know this magic number in order to cancel it. From the clients point of view it only has one thing it cares about, but if we don't implement this on the job scheduler side, suddenly it has more than one.

2021-06-01 20:08 UTC, cpoile approved these changes
Ok, I understand what's going on now. I misunderstood where the reminder was being set and why it was being cancelled. Makes sense now, and yes, that should be fixed! :)

2021-06-01 20:09 UTC, merged