[MM-35825] Message on every keyword
mattermost/mattermost-plugin-incident-collaboration pull request #569
Opened 2021-05-24 12:19 UTC by iomodo

#### Summary
This PR takes a first stab at keyword signals. User is able to specify comma separated keywords which will trigger the ephemeral message with the list of relevant playbooks. 

https://user-images.githubusercontent.com/2340127/119346824-c1b18c00-bcab-11eb-8bbf-866b8a5d1c56.mp4

#### Ticket Link
  Fixes: https://mattermost.atlassian.net/browse/MM-35825

#### Checklist

[ ] Telemetry updated
[ ] Gated by experimental feature flag
[ ] Unit tests updated

2021-05-24 16:15 UTC, agarciamontoro requested changes
Great work, @iomodo, thank you :tada:

I'm a bit concerned with the performance impact of the whole feature (not actually of your specific implementation, which seems quite sensible). I'm not sure whether the ratio between the improvement to the discoverability of playbooks and the impact on performance is worth it, but I think we will know when we ship it.

2021-05-24 16:15 UTC, agarciamontoro commented on server/plugin.go
> +		message += playbook.Title + "\n"
These could be links to the playbooks themselves, maybe.

2021-05-24 16:15 UTC, agarciamontoro commented on server/plugin.go
> +		}
In order to get rid of the `PlaybookAccess` call everytime a playbook matches, we could maybe ask for only the playbooks available for this user, instead of all the playbooks with `GetPlaybooks`. We'd need to add a new `GetPlaybooksForUser` (or something similar) to the store, but maybe it would be better? I'd say so, but difficult to know  without measuring, actually. This is just me being concerned with the overall performance impact of the feature.

2021-05-24 16:15 UTC, agarciamontoro commented on server/playbook/playbook.go
> +	SignalAnyKeywords           string      `json:"signal_any_keywords"`
What if we make this a `[]string` and split the string stored in the database when we perform the select, instead of splitting with every message?

2021-05-24 16:15 UTC, agarciamontoro commented on webapp/src/components/backstage/automation/patterned_input.tsx
> +export const PatternedInput: FC<Props> = (props: Props) => (
Nice refactor :ok_hand:

2021-06-02 21:00 UTC, iomodo commented
Heads up @agarciamontoro @crspeller 
Implemented optimization - playbooks are being cached and retrieved from DB only if they've been updated. Still on every user message we have to get a channel and make a query to DB to know if playbooks have been updated.

Do not pay attention to the ephemeral message format. I will submit a different PR to make it more presentable/usable.

2021-06-02 21:05 UTC, iomodo commented on server/sqlstore/migrations.go
> +					if !strings.Contains(err.Error(), "Duplicate key name") { // Instead of IF NOT EXISTS which is not supported
Please pay attention to this. When you name the index mysql is throwing an `duplicate key name` error if you try to execute twice. Another way to implement this is to create something like `IF NOT EXISTS` by querying the index first. I thought error throwing was less effort :)

2021-06-03 10:11 UTC, agarciamontoro requested changes
This is great, I really liked reading through it :) Thank you!

I left some comments, but nothing major.

2021-06-03 10:11 UTC, agarciamontoro commented on server/playbook/service.go
> +	playbooks := s.cacher.GetPlaybooks()
Is there any case where we want to call `cacher.GetPlaybooks` without calling `UpdatePlaybooksIfNeeded`? If not, maybe we can embed everything in `GetPlaybooks`. What do you think?

2021-06-03 10:11 UTC, agarciamontoro commented on webapp/src/types/playbook.ts
> +        arg.invited_group_ids && Array.isArray(arg.invited_group_ids) && arg.invited_group_ids.every((id: any) => typeof id === 'string') &&
Whoops, good catch!

2021-06-03 10:12 UTC, agarciamontoro commented on server/playbook/service_test.go
> +		store.EXPECT().GetTimeLastUpdated().Return(int64(1100), nil).After(firstCall)
Oh, but it got updated with the max time in the playbooks, which is 1100. Is that right?

2021-06-03 14:41 UTC, iomodo commented on server/playbook/service_test.go
> +				SignalAnyKeywords: []string{" some", "other"},
It is. Generally a keyword can be any string not containing a comma.

2021-06-03 14:41 UTC, iomodo commented on server/playbook/service_test.go
> +		store.EXPECT().GetTimeLastUpdated().Return(int64(1100), nil).After(firstCall)
Correct, time should be greater than `1100` to trigger an update from the DB

2021-06-03 14:41 UTC, iomodo commented on server/sqlstore/migrations.go
> +				if _, err := e.Exec("UPDATE IR_Playbook SET UpdatedAt = CreateAt"); err != nil {
Here it is https://github.com/mattermost/mattermost-plugin-incident-collaboration/blob/7f144404dcdeec0f6be715679f13c318ae807a47/server/sqlstore/migrations.go#L787

2021-06-03 14:42 UTC, iomodo commented on server/sqlstore/playbook_test.go
> +		})
Great catch!

2021-06-03 14:42 UTC, iomodo commented on server/sqlstore/migrations.go
> +				if err := addColumnToMySQLTable(e, "IR_Playbook", "UpdatedAt", "BIGINT NOT NULL DEFAULT 0"); err != nil {
Yep you are right!

2021-06-03 14:42 UTC, iomodo commented on server/playbook/service.go
> +	playbooks := s.cacher.GetPlaybooks()
Good point

2021-06-03 14:51 UTC, agarciamontoro commented on server/sqlstore/migrations.go
> +				if _, err := e.Exec("UPDATE IR_Playbook SET UpdatedAt = CreateAt"); err != nil {
I meant something like `time.Now()`, instead of the `CreateAt` timestamp.

2021-06-03 14:53 UTC, agarciamontoro approved these changes
It looks good! The only thing is the `CreateAt` / `time.Now()` issue (which I defer to your opinion, but wanted to clarify what I meant!)

2021-06-03 17:31 UTC, iomodo commented on server/sqlstore/migrations.go
> +				if _, err := e.Exec("UPDATE IR_Playbook SET UpdatedAt = CreateAt"); err != nil {
Sorry, totally misread your comment.

2021-06-03 18:56 UTC, crspeller requested changes

2021-06-03 18:56 UTC, crspeller commented on server/plugin.go
> +		message += playbook.Title + "\n"
Feature seems pretty useless without this. I am guessing the plan is to be able to start an incident from here?

2021-06-03 18:56 UTC, crspeller commented on server/playbook/cache.go
> +type Cacher interface {
The naming here is confusingly generic for something that solves a very specific problem.

2021-06-03 18:56 UTC, crspeller commented on server/sqlstore/playbook.go
> +func (p *playbookStore) GetTimeLastUpdated(onlyPlaybooksWithKeywordsEnabled bool) (int64, error) {
This has to be run for every cache request. Do we know that this query is actually significantly faster than the above? Otherwise there is a lot of complexity here that might be avoided.

2021-06-03 18:56 UTC, crspeller commented on server/playbook/playbook.go
> +	GetTimeLastUpdated(onlyPlaybooksWithKeywordsEnabled bool) (int64, error)
Why is there a boolean option here? I don't see anywhere we use this with `false`.

2021-06-03 18:56 UTC, crspeller commented on webapp/src/components/backstage/playbook_edit.tsx
> +        if (!hasSameElements(playbook.signal_any_keywords, final_keywords)) {
Why bother checking?

2021-06-03 18:56 UTC, crspeller commented on webapp/src/components/backstage/playbook_edit.tsx
> +            const typingKeyword = keywords.substring(index + 1);
Why bother doing any of this? Why not just split on `,`?

2021-06-03 18:56 UTC, crspeller commented on server/sqlstore/migrations.go
> +				if _, err := e.Exec(`ALTER TABLE IR_Playbook ADD INDEX IR_Playbook_UpdateAt (UpdateAt)`); err != nil {
Why an index on UpdateAt?

2021-06-07 12:38 UTC, iomodo commented on server/sqlstore/playbook.go
> +func (p *playbookStore) GetTimeLastUpdated(onlyPlaybooksWithKeywordsEnabled bool) (int64, error) {
If number of playbooks is small time difference will be negligent. But we decided to go this route in case of many playbooks.

2021-06-07 12:40 UTC, iomodo commented on server/playbook/playbook.go
> +	GetTimeLastUpdated(onlyPlaybooksWithKeywordsEnabled bool) (int64, error)
Correct, `false` is not used. I thought creating a method like `GetTimeLastUpdatedForPlaybooksWithKeywordsEnabled` would be mouthful. Maybe we will need to get last updated playbook in the future, the method will be there.

2021-06-07 12:42 UTC, iomodo commented on webapp/src/components/backstage/playbook_edit.tsx
> +        if (!hasSameElements(playbook.signal_any_keywords, final_keywords)) {
To use `setPlaybook` only when there is an actual update.

2021-06-07 12:48 UTC, iomodo commented on webapp/src/components/backstage/playbook_edit.tsx
> +            const typingKeyword = keywords.substring(index + 1);
There is a difference between representation and data storage. For example
`one,two,three` is saved as a list `["one", "two", "three"]` and later represented as `one,two,three`
`one,two,three,` is saved as a list `["one", "two", "three", ""]` and later represented as `one,two,three,`
If we just split on`,` we will lose the last element in the array and store `one,two,three,` as `["one", "two", "three"]` and later represent as `one,two,three`. In fact we will not be able to even represent that because the commas will be lost.
`one,` will be saved as `["one"]` and represented as `one` later.

2021-06-07 12:51 UTC, iomodo commented on server/sqlstore/migrations.go
> +				if _, err := e.Exec(`ALTER TABLE IR_Playbook ADD INDEX IR_Playbook_UpdateAt (UpdateAt)`); err != nil {
We have an index here to perform the `MAX` on `UpdateAt` field, which will be logarithmic complexity with the `B-Tree`. Exactly this makes the caching strategy faster for the many playbooks case.

2021-06-07 12:52 UTC, iomodo commented
> Feature seems pretty useless without this. I am guessing the plan is to be able to start an incident from here?

Correct, my next PR will do exactly that.

2021-06-07 12:54 UTC, iomodo commented on server/playbook/cache.go
> +type Cacher interface {
Will rename it to `KeywordsCacher`

2021-06-07 21:09 UTC, crspeller commented on server/sqlstore/playbook.go
> +func (p *playbookStore) GetTimeLastUpdated(onlyPlaybooksWithKeywordsEnabled bool) (int64, error) {
I am not convinced this is worth the cost. I wonder how many playbooks we would need to see a difference?

2021-06-07 21:11 UTC, crspeller commented on webapp/src/components/backstage/playbook_edit.tsx
> +        if (!hasSameElements(playbook.signal_any_keywords, final_keywords)) {
How are you supposed to actually cause this to happen? Any edit would cause this, even if it reverts later.

2021-06-07 21:32 UTC, crspeller commented on webapp/src/components/backstage/playbook_edit.tsx
> +            const typingKeyword = keywords.substring(index + 1);
Split trims the last element? 
Also I think if I type something like `re, result` The second re will be deleted before I finish result? 
This appears to be too much control over input. I would suggest maybe just using a text field, otherwise you can get strangeness. Like what happens if I try to add a comma right after another one in the middle?

2021-06-08 13:58 UTC, iomodo commented on server/sqlstore/playbook.go
> +func (p *playbookStore) GetTimeLastUpdated(onlyPlaybooksWithKeywordsEnabled bool) (int64, error) {
I did some benchmarking here are some data points `getTimeLastUpdated` vs `GetPlaybooksForKeywords`.

10-30 playbooks - same
50-100 playbooks - 20% time decrease
200-500 playbooks - 40% time decrease
600-1000 playbooks - 50% time decrease - twice as fast. In absolute terms `3ms` vs `6ms`.

When measured difference is not that big. Maybe it's better to avoid all the caching?

P.S. I tested this before but I compared `GetLastUpdate` with `GetPlaybooks`(which already existed) and there was a big difference for 10-30 playbooks twice as fast, for 100-200 5 times as fast.

Thoughts? cc @agarciamontoro @crspeller

2021-06-08 14:06 UTC, iomodo commented on webapp/src/components/backstage/playbook_edit.tsx
> +        if (!hasSameElements(playbook.signal_any_keywords, final_keywords)) {
Yes, that is correct, I'll remove the check

2021-06-08 14:09 UTC, iomodo commented on webapp/src/components/backstage/playbook_edit.tsx
> +            const typingKeyword = keywords.substring(index + 1);
`re, result` will work fine. 
If you repeat the keyword it will get deleted. That is if you'll type `re,re,` you will get `re,`. Do you think we should remove this feature?

2021-06-08 14:15 UTC, agarciamontoro commented on server/sqlstore/playbook.go
> +func (p *playbookStore) GetTimeLastUpdated(onlyPlaybooksWithKeywordsEnabled bool) (int64, error) {
I'm not sure whether any normal server would get to 600 playbooks :thinking: But I'd say that even a 20% performance improvement is worth it, given that this happens in every message posted in the whole server.

2021-06-08 14:46 UTC, crspeller commented on webapp/src/components/backstage/playbook_edit.tsx
> +            const typingKeyword = keywords.substring(index + 1);
I would defer to @abhijit-singh for an answer to that.

2021-06-08 14:49 UTC, crspeller commented on server/sqlstore/playbook.go
> +func (p *playbookStore) GetTimeLastUpdated(onlyPlaybooksWithKeywordsEnabled bool) (int64, error) {
Alright. I think we can keep it then. I would happen a lot on a production server.

2021-06-09 17:40 UTC, iomodo commented on webapp/src/components/backstage/playbook_edit.tsx
> +            const typingKeyword = keywords.substring(index + 1);
Talked to @abhijit-singh offline, removed extra control over the input. Duplicate keywords will still be removed on save.

cc @crspeller ready for your review.

2021-06-10 17:33 UTC, crspeller approved these changes

2021-06-10 17:44 UTC, merged