[MM-35059] Make /incident test bulk-data command create playbooks
mattermost/mattermost-plugin-incident-collaboration pull request #570
Opened 2021-05-25 11:40 UTC by arvinDarmawan

Summary
This code will do two things : 
- create new command /incident test create-playbook  to create multiple playbooks
- update existing command /incident test bulk-data

Ticket Link
Jira card: https://mattermost.atlassian.net/browse/MM-35059
Github issue: https://github.com/mattermost/mattermost-server/issues/17469

```release-note
Release Note
- create new command /incident test create-playbook (parameter [total_playbooks]  to create multiple playbooks
- update existing command /incident test bulk-data
```

2021-05-25 11:40 UTC, mattermod commented
Hello @arvinDarmawan,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-05-25 12:02 UTC, agarciamontoro commented
Thank you for your contribution, @arvinDarmawan! :tada:

Could you update your branch with the latest changes in master? I think CI is failing because of that.

2021-05-25 12:14 UTC, arvinDarmawan commented
> Thank you for your contribution, @arvinDarmawan! 🎉
> 
> Could you update your branch with the latest changes in master? I think CI is failing because of that.



> Thank you for your contribution, @arvinDarmawan! 🎉
> 
> Could you update your branch with the latest changes in master? I think CI is failing because of that.

ok, thank you

2021-05-26 04:35 UTC, arvinDarmawan commented
Pull Request #17469

2021-05-27 07:09 UTC, iomodo approved these changes
Looks great! Thanks for the contribution @arvinDarmawan

2021-05-27 15:56 UTC, agarciamontoro requested changes
This is really good, @arvinDarmawan, thank you! :tada: I left some suggestions below.

By the way, thank you for coming up with those sample playbooks, it's great!

2021-05-27 15:56 UTC, agarciamontoro commented on server/command/command.go
> +		r.postCommandResponse("Cant generate playbooks since the number of playbook generated must be at most five")
We can reword this to something more simple:

```suggestion
		r.postCommandResponse("Maximum number of playbooks is 5")
```

2021-05-27 15:56 UTC, agarciamontoro commented on server/command/command.go
> +			r.warnUserAndLogErrorf("There was an error while creating playbook. Err: " + err.Error())
You can use a formatted string here, as follows:
```suggestion
			r.warnUserAndLogErrorf("unable to create playbook: %v",  err)
```

2021-05-27 15:56 UTC, agarciamontoro commented on server/command/command.go
> +	r.postCommandResponse(fmt.Sprintf("Playbooks successfully created : '%s'", playbookIds))
This is good feedback, but we can make it even more helpful by directly linking to the playbooks. Something like the following (not tested, though):

```go
// We need this to construct the playbook URL
team, err := r.pluginAPI.Team.Get(r.args.TeamId)
if err != nil {
	r.warnUserAndLogErrorf("unable to retrieve team: %v", err)
	return
}

msg := "Playbooks successfully created"
for i, playbookID := range playbookIds {
	url := fmt.Sprintf("/%s/com.mattermost.plugin-incident-management/playbooks/%s", team.Name, playbookID)
	msg += fmt.Sprintf("\n- [%s](%s)", dummyListPlaybooks[i].Title, url)
}
```

2021-05-27 15:56 UTC, agarciamontoro commented on server/command/command.go
> +		Description: "This is example of empty playbook",
```suggestion
		Description: "This is an example of an empty playbook",
```

2021-05-27 15:56 UTC, agarciamontoro commented on server/command/command.go
> +		Description: "There is error when access message from deleted channel",
```suggestion
		Description: "There is ab error when accessing message from deleted channel",
```

2021-05-27 15:56 UTC, agarciamontoro commented on server/command/command.go
> +		Description: "### Describe the incident so that someone without prior knowledge can ramp up quickly. Two sentences is the ideal length.",
We can come up with something here
```suggestion
		Description: "Sample playbook",
```

2021-05-27 15:56 UTC, agarciamontoro commented on server/command/command.go
> +			r.warnUserAndLogErrorf("There was an error while creating playbook. Err: " + err.Error())
Same suggestion here:
```suggestion
			r.warnUserAndLogErrorf("unable to create playbook: %v",  err)
```

2021-05-27 15:56 UTC, agarciamontoro commented on server/command/command.go
> +		newPlayBookID, err := r.playbookService.Create(dummyPlaybook, r.args.UserId)
Nit: we usually write "book" in lowercase
```suggestion
		newPlaybookID, err := r.playbookService.Create(dummyPlaybook, r.args.UserId)
```

2021-05-27 15:56 UTC, agarciamontoro commented on server/command/command.go
> +		newPlayBook, err := r.playbookService.Get(newPlayBookID)
Same here
```suggestion
		newPlaybook, err := r.playbookService.Get(newPlaybookID)
```

2021-05-27 15:56 UTC, agarciamontoro commented on server/command/command.go
> +		playbooks = append(playbooks, newPlayBook)
You can simply do this here:
```suggestion
		playbooks = []playbook.Playbook{newPlaybook}
```

2021-05-31 11:07 UTC, arvinDarmawan commented
Hi @agarciamontoro , I already fix the revision

2021-06-01 09:22 UTC, agarciamontoro requested changes
Great job, @arvinDarmawan, thank you! Just a small change for the text displayed.

2021-06-01 09:22 UTC, agarciamontoro commented on server/command/command.go
> +	r.postCommandResponse(fmt.Sprintf("Playbooks successfully created : '%s'", msg))
We can just use `msg` here. Otherwise, the words "Playbooks successfully created" will be repeated:

```suggestion
	r.postCommandResponse(msg)
```

2021-06-01 13:25 UTC, agarciamontoro reviewed
Thanks! It looks like the lint check is failing. Could you take a look? https://app.circleci.com/pipelines/github/mattermost/mattermost-plugin-incident-collaboration/3284/workflows/9e06df12-8897-450a-856d-f45a8c385d83/jobs/18555 If you run `make check-style` locally, you'll get the error.

2021-06-01 15:38 UTC, arvinDarmawan commented
> Thanks! It looks like the lint check is failing. Could you take a look? https://app.circleci.com/pipelines/github/mattermost/mattermost-plugin-incident-collaboration/3284/workflows/9e06df12-8897-450a-856d-f45a8c385d83/jobs/18555 If you run `make check-style` locally, you'll get the error.

Done @agarciamontoro

2021-06-01 16:00 UTC, agarciamontoro approved these changes
Great, @arvinDarmawan, thank you! :tada: Time for QA review :)

2021-06-12 01:01 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2021-06-18 19:28 UTC, lieut-data commented
I've merged `origin/master` into this PR and tested it locally -- looks good! Will merge once build passes.

2021-06-18 19:50 UTC, merged

2021-06-18 19:50 UTC, lieut-data commented
Thanks again, @arvinDarmawan!