Add hot module loading.
mattermost/mattermost-plugin-incident-collaboration pull request #580
Opened 2021-06-03 21:56 UTC by crspeller

#### Summary
Adds the webpack dev server and hot module loading as an option for development. This allows near instant updates for client changes without a refresh. Perfect for tweaking CSS or fiddling with JSX. 

#### Usage
To use run `make dev` then visit http://localhost:9005 instead of the usual 8065. 

#### Known issues
- Works normally while looking at the main view, however in the backstage it requires you to click on your browser to show changes. Not sure why this is.

2021-06-04 13:38 UTC, cpoile requested changes
sweet! Just a question about the previous watch command we had

2021-06-04 13:38 UTC, cpoile commented on Makefile
> +	cd webapp && $(NPM) run dev-server
Will this conflict with the watch above? (line 129)
And what is different from `run debug:watch`? If this is better, then maybe just replace debug:watch (and remove it) with this `run dev-server`?

2021-06-04 15:36 UTC, crspeller commented on Makefile
> +	cd webapp && $(NPM) run dev-server
If you run them both at the same time? Probably. 
I was hoping we would try it out and see how we liked it. If it is exclusively better we would remove watch. 
Or maybe you are confused because the PHONY is wrong... fixed!

2021-06-04 15:58 UTC, lieut-data approved these changes
Neat!

2021-06-04 15:58 UTC, lieut-data commented on webapp/webpack.config.js
> +        devtool: 'eval-cheap-module-source-map',
I love this for speed, but it's annoying when I need more data. This also forces the `devtool` vs. letting it get defined above when we first set `devtool`. Should we at least move this up there, and perhaps later iterate on a way to "build fast" vs. "debug slow"?

2021-06-07 16:44 UTC, agarciamontoro approved these changes
I quickly tested it and it's much faster than `make watch`, I like it! I was also going to ask whether it would be nice to remove `watch`, but I agree we can test it for a few weeks before making a decision. Thanks, @crspeller!!

2021-06-07 17:21 UTC, iomodo approved these changes
wonderful!

2021-06-07 19:43 UTC, cpoile commented on Makefile
> +	cd webapp && $(NPM) run dev-server
Indeed. Thanks! :)

2021-06-07 19:43 UTC, cpoile approved these changes

2021-06-08 21:12 UTC, merged