MM-35695 - First pass at new playbook landing page
mattermost/mattermost-plugin-incident-collaboration pull request #581
Opened 2021-06-04 20:37 UTC by cpoile

#### Summary
- First pass. Backend is (should be) complete and correct. New stats, was able to turn all stats calls into single queries (thanks @lieut-data for the pointer to `sum(case`).
- For the frontend I duplicated the incident list component from `BackstageIncidentList` because there were enough changes that making it generic would be a pain, and I'm still not sure if we're making them both look exactly the same. If we do end up wanting that, I think I can make `BackstageIncidentList` use the new IncidentList component.
- I wanted to get this work under review, rather than waiting for everything to be perfect. So the frontend is not tweaked yet -- there are a few little things like navigation and the changes to IncidentList, but otherwise it close to the designs. 

Where we are:
- [x] Backend stats, rough frontend. <-- We are here
- [ ] UI tweaks to bring into 100% in line with designs
- [ ] licence checked and upgrade bannered

Looks like:
![image](https://user-images.githubusercontent.com/1490756/120859829-c818f100-c552-11eb-8e20-2ee0dae12be7.png)

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-35695

#### Checklist

- [ ] Telemetry updated
- [ ] Gated by experimental feature flag
- [x] Unit tests updated

2021-06-04 20:56 UTC, lieut-data commented
This is stunning, @cpoile! Looking forward to finishing this review :)

2021-06-07 16:54 UTC, lieut-data requested changes
A handful of comments around the API format and SQL queries, but looking good!

2021-06-07 16:54 UTC, lieut-data commented on server/sqlstore/stats.go
> +	if filters.TeamID != "" {
There's a subtle change here, in that an empty team id no longer constrains the query at all (so presumably "no results") -- just noting that explicitly in case it has unexpected access side effects.

2021-06-07 16:54 UTC, lieut-data commented on server/sqlstore/stats.go
> +// RunsFinishedBetweenDays are calculated from startDay to endDay (inclusive), where "days"
What's the implicit timezone in these calculations?

2021-06-07 16:54 UTC, lieut-data commented on server/sqlstore/stats.go
> +		Where(sq.And{sq.Expr("i.EndAt > ?", startInMS), sq.Expr("i.EndAt < ?", endInMS)})
nit: I usually expect to see at least one include range, i.e. `>` and `<=`, otherwise events can "go missing" in consecutive queries. Probably not an issue.

2021-06-07 16:54 UTC, lieut-data commented on server/sqlstore/stats.go
> +		selectStatements = append(selectStatements,
nit: instead of maintaining an array slice, is it possible to "start" the builder and just keep calling `q.Select(...)` to let that do its thing instead?

2021-06-07 16:54 UTC, lieut-data commented on server/sqlstore/stats.go
> +		// use the middle of the day to get the date, just in case
I guess this would be implicitly UTC+12, or Kamchatka time? I'd be inclined to stick with UTC.

2021-06-07 16:54 UTC, lieut-data commented on server/sqlstore/stats.go
> +			fmt.Sprintf("COUNT( DISTINCT (CASE "+
Instead of string concatenation, can we just start a raw literal that spans multiple lines?

2021-06-07 16:54 UTC, lieut-data commented on server/api/stats.go
> +	RunsStartedPerWeekLabels       []string `json:"runs_started_per_week_labels"`
I'm not a huge fan of building and returning the labels -- feels like a client-side concern IMO, and I guess it also requires pairing up the label with the value manually. Minimally, should we send down a `map[string]int` instead? Or maybe just a `map[int]int` and let the client render the date from the milliseconds as desired?

2021-06-07 19:38 UTC, cpoile commented on server/api/stats.go
> +	statsRouter.HandleFunc("/playbook", handler.playbookStats).Methods(http.MethodGet)
I thought about that-- i agree `/playbooks/id/stats` reads better. But the existing stats functions (some of which I reuse), the stats package itself, the stats service/store are all accessed from the `/stats` route handler, so I decided it would be more natural to put it there.

2021-06-07 19:38 UTC, cpoile commented on server/sqlstore/stats.go
> +	if filters.TeamID != "" {
I tried to think of a case where this would break, but I'm pretty sure it's okay. Any access to the stats that assume a `filters.TeamId` value goes through the `parseStatsFilters`, and will reject requests without a `teamId`. So I think we're okay here.

2021-06-07 19:39 UTC, cpoile commented on server/sqlstore/stats.go
> +// RunsFinishedBetweenDays are calculated from startDay to endDay (inclusive), where "days"
The server's local timezone. Maybe this was a bad assumption? Should we be sending the client's timezone with the request? Working with time is so annoying. :)

2021-06-07 19:39 UTC, cpoile commented on server/sqlstore/stats.go
> +		Where(sq.And{sq.Expr("i.EndAt > ?", startInMS), sq.Expr("i.EndAt < ?", endInMS)})
Yep, good point just to be safe. I changed it to be inclusive on one end of the range for all the selects (the end of the day).

2021-06-07 19:39 UTC, cpoile commented on server/sqlstore/stats.go
> +		selectStatements = append(selectStatements,
I tried, and afaict it looks like you can only call the select once. You can add where's and so forth as you like, but the select returns a SelectBuilder, which won't let you add more selects.

2021-06-07 19:40 UTC, cpoile commented on server/sqlstore/stats.go
> +		// use the middle of the day to get the date, just in case
Nope, server localtime. This +halfday was purely defensive on my part. I just didn't want to deal with wierdness, it's only to find the date itself.

2021-06-07 19:40 UTC, cpoile commented on server/sqlstore/stats.go
> +			fmt.Sprintf("COUNT( DISTINCT (CASE "+
👍 
I wasn't sure how to properly indent it (is there one "proper" way?), so I used the way intellij indents its SQL.

2021-06-07 19:41 UTC, cpoile commented on server/api/stats.go
> +	RunsStartedPerWeekLabels       []string `json:"runs_started_per_week_labels"`
@lieut-data I suppose we could return the millis for each date, and let the client convert it. But that might introduce some wierdness with the labelling -- the client may display a timestamp as the wrong day from what the server was actually measuring.. I'm not sure how to solve this perfectly, so I decided on having the server declare the truth, and send that to the client. 

Open to other approaches though. What do you think? If we send the client's timezone, then we could send back millis. That's one option.

2021-06-07 20:46 UTC, crspeller commented on server/api/stats.go
> +	statsRouter.HandleFunc("/playbook", handler.playbookStats).Methods(http.MethodGet)
The idea of separating it is that `/playbooks` and `/incidents` deal with specificly those, but `/stats` can be across the whole system.

2021-06-07 20:46 UTC, crspeller commented on server/sqlstore/stats.go
> +// RunsFinishedBetweenDays are calculated from startDay to endDay (inclusive), where "days"
The perils of writing our own stats :P

2021-06-07 20:50 UTC, crspeller commented on server/api/stats.go
> +	RunsStartedPerWeekLabels       []string `json:"runs_started_per_week_labels"`
I like the idea of including the TZ in the request. Not sure how to get the correct day boundaries from the client's perspective otherwise.

2021-06-07 20:50 UTC, crspeller approved these changes
Looking good!

2021-06-07 22:00 UTC, lieut-data commented on server/api/stats.go
> +	statsRouter.HandleFunc("/playbook", handler.playbookStats).Methods(http.MethodGet)
I think the plan is to remove `/stats`, at least as a landing page. When we re-introduce a home page, is it likely that we'd want a `/home`, or would it be better to compose widgets that query dedicated `/playbooks` and `/incidents` pages? Is there an example of a stat endpoint that /should/ return something for both playbooks and incidents at the same time?

Ultimately, it's immaterial to our main user experience, but I think it speaks to whether we want `stats` as a first class /API/ concept or not. Maybe we promote it later when we have a concrete use case (and demote it now?)

2021-06-07 22:01 UTC, lieut-data commented on server/sqlstore/stats.go
> +	if filters.TeamID != "" {
Do we test that querying with an empty `TeamId` at the SQL layer works "as expected"?

2021-06-07 22:02 UTC, lieut-data commented on server/sqlstore/stats.go
> +// RunsFinishedBetweenDays are calculated from startDay to endDay (inclusive), where "days"
I'd vote for forcing UTC for everyone.

2021-06-07 22:03 UTC, lieut-data commented on server/sqlstore/stats.go
> +		selectStatements = append(selectStatements,
What about https://pkg.go.dev/github.com/Masterminds/squirrel?utm_source=godoc#SelectBuilder.Column? Alternatively, I believe `Select` also accepts a spread directly.

2021-06-07 22:05 UTC, lieut-data commented on server/sqlstore/stats.go
> +			fmt.Sprintf("COUNT( DISTINCT (CASE "+
I'm a fan of indenting like this: https://github.com/mattermost/mattermost-server/blob/12e439a98ddc6062591cc36da3b845e72f599b30/store/sqlstore/post_store.go#L381-L405

Of course, I brought that style with me... :)

2021-06-07 22:05 UTC, lieut-data commented on server/sqlstore/stats.go
> +			fmt.Sprintf("COUNT( DISTINCT (CASE "+
(Basically, just start the tick, then indent like any other code.)

2021-06-07 22:06 UTC, lieut-data commented on server/api/stats.go
> +	RunsStartedPerWeekLabels       []string `json:"runs_started_per_week_labels"`
Propose deferring client-defined time. This has the added complexity of having different team members seem different graphs. UTC seems fine, IMO.

2021-06-08 13:26 UTC, cpoile commented on server/api/stats.go
> +	statsRouter.HandleFunc("/playbook", handler.playbookStats).Methods(http.MethodGet)
>  Is there an example of a stat endpoint that /should/ return something for both playbooks and incidents at the same time?

For the stats that I added, there's no reason you couldn't use them for all incidents in a team, we just happen to be adding a `where i.playbookid = id` to the select. That's kind of why I think I like have a separate stats endpoint and package--there's no reason the stats can't apply team-wide (or org wide, if you have no `where` clause).

2021-06-08 17:04 UTC, cpoile commented on server/sqlstore/stats.go
> +	if filters.TeamID != "" {
Yes, we do now. :)

2021-06-08 17:04 UTC, cpoile commented on server/sqlstore/stats.go
> +// RunsFinishedBetweenDays are calculated from startDay to endDay (inclusive), where "days"
Sounds good, done.

2021-06-08 17:04 UTC, cpoile commented on server/sqlstore/stats.go
> +		selectStatements = append(selectStatements,
Yep, `Column` did it. Thanks, didn't know about that!

2021-06-08 17:07 UTC, cpoile commented on server/sqlstore/stats.go
> +		// use the middle of the day to get the date, just in case
Yes UTC+12 -- since we're using the exact nanosecond of 12:00:00.000 am, I'm worried that we're basically asking for a weird edge case. Adding some time removes any possibility of an edge case. It could be an hour, or a minute, or whatever.

2021-06-08 17:08 UTC, cpoile commented on server/api/stats.go
> +	RunsStartedPerWeekLabels       []string `json:"runs_started_per_week_labels"`
Settled on UTC.  👍

2021-06-08 17:14 UTC, lieut-data approved these changes
Nice!

2021-06-08 17:14 UTC, lieut-data commented on server/sqlstore/stats.go
> +		Where(sq.And{sq.Expr("i.EndAt > ?", startInMS), sq.Expr("i.EndAt <= ?", endInMS)})
nit: I find it helpful to write this as:
```suggestion
		Where(sq.And{
		    sq.Expr("i.EndAt > ?", startInMS), 
		    sq.Expr("i.EndAt <= ?", endInMS),
		})
```

2021-06-09 18:02 UTC, merged