MM-36259 - Navigation between playbook backstage screens
mattermost/mattermost-plugin-incident-collaboration pull request #582
Opened 2021-06-08 18:05 UTC by cpoile

#### Summary
- playbook edit: new 'cancel' button
- playbook edit: clicking 'save' or 'cancel' will return to playbook landing page
- playbook edit: remove left-arrow, increase max-width for title in edit screen (we have extra space without the left-arrow)
- playbook list screen: edit action should go to playbook edit
- incident overview: left arrow will bring you to ~~playbook landing page~~ incident list

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-36259

#### Checklist

- [ ] ~~Telemetry updated~~
- [ ] ~~Gated by experimental feature flag~~
- [ ] ~~Unit tests updated~~

2021-06-09 16:19 UTC, agarciamontoro approved these changes
Looks great! 

One consideration: when clicking on the X to close the backstage, the playbook edit screen does not warn about losing the changes made. I think this has been always the case, but just in case.

2021-06-09 16:19 UTC, agarciamontoro commented on webapp/src/components/backstage/playbook_edit.tsx
> +                onConfirm={() => onClose()}
One of my classic nits (feel free to ignore, this is just me being super picky):
```suggestion
                onConfirm={onClose}
```

2021-06-09 16:35 UTC, abhijit-singh requested changes
The described functionality looks good @cpoile! 

Can we style the `Cancel` button as a secondary button and reverse the order? Thanks!
![image](https://user-images.githubusercontent.com/14369607/121394254-c7c39000-c96e-11eb-87b9-7006f3320ec4.png)

2021-06-09 17:15 UTC, cpoile commented
> when clicking on the X to close the backstage, the playbook edit screen does not warn about losing the changes made. I think this has been always the case, but just in case.

Good catch, I opened a tech debt ticket for that: https://mattermost.atlassian.net/browse/MM-36322

2021-06-09 17:16 UTC, cpoile commented on webapp/src/components/backstage/playbook_edit.tsx
> +                onConfirm={() => onClose()}
Almost, but that won't work here; `onConfirm` tries to pass in a `checked: boolean` which conflicts with the onClose signature. :)

2021-06-09 17:24 UTC, cpoile commented
@abhijit-singh Sure! Here you go:
![image](https://user-images.githubusercontent.com/1490756/121400775-fa956600-c925-11eb-98ff-6d819a33e989.png)

2021-06-09 17:26 UTC, abhijit-singh approved these changes
Awesome, thanks!

2021-06-09 17:28 UTC, agarciamontoro commented on webapp/src/components/backstage/playbook_edit.tsx
> +                onConfirm={() => onClose()}
Oh no :( I don't understand why it lets you pass a function with no arguments, then.  the type safety

2021-06-09 17:30 UTC, abhijit-singh commented
> when clicking on the X to close the backstage, the playbook edit screen does not warn about losing the changes made. I think this has been always the case, but just in case.

@agarciamontoro I do see that warning currently 
![2021-06-09 22 57 44](https://user-images.githubusercontent.com/14369607/121401506-699aab00-c976-11eb-902c-e1b5ad1e470b.gif)

2021-06-09 17:41 UTC, cpoile commented
@abhijit-singh Found the problem: master changed. I need to rebase and fix some merge conflicts. This will be solved.

2021-06-09 17:44 UTC, iomodo approved these changes
LGTM! Thanks @cpoile

2021-06-10 12:23 UTC, mattermod commented
Will try to auto merge this PR once all tests and checks are passing. This might take up to an hour.

2021-06-10 12:40 UTC, mattermod commented
Trying to auto merge this PR.

2021-06-10 12:40 UTC, merged

2021-06-10 12:40 UTC, mattermod commented
Pull Request successfully merged
SHA: b23301ee106a1772fef8fd7bbcc52661ca1973df