Add support of the post actions
mattermost/mattermost-plugin-incident-collaboration pull request #588
Opened 2021-06-10 15:06 UTC by iomodo

#### Summary
This is final in the keyword signals effort(except telemetry). It implements post action support.
1. Users can choose playbook to run 
2. Users can choose to ignore thread and in that particular thread no keywords will be triggered(for the particular user, other users will still receive suggestions)
3. When clicked on the keywords details user is transferred to the automation tab

https://user-images.githubusercontent.com/2340127/121549250-be91fc00-ca1e-11eb-800b-c50ad51acdff.mp4

https://user-images.githubusercontent.com/2340127/121549315-ce114500-ca1e-11eb-98d8-d2b62e5f61ae.mp4

#### Ticket Link
  Fixes: 
https://mattermost.atlassian.net/browse/MM-35826
https://mattermost.atlassian.net/browse/MM-35827

#### Checklist

- [ ] Telemetry updated
- [ ] Gated by experimental feature flag
- [x] Unit tests updated

2021-06-11 11:09 UTC, itao commented
@iomodo could you include screenshot of the playbook configuration screen as well? That'd help @justinegeffen and @abhijit-singh to understand the user flow and provide guidance on copy and UX, respectively.

2021-06-11 14:17 UTC, lieut-data commented
Super slick, @iomodo! Would it make sense to remove the action buttons after clicking so that the prompts disappear and "clean up" the channel for the enduser? I'm starting code review now.

2021-06-11 15:32 UTC, cpoile requested changes
Awesome work @iomodo, thanks!

2021-06-11 15:32 UTC, cpoile commented on server/playbook/service.go
> +	}
I feel like we could remove this loop by doing the work in the loop inside `filterPlaybooksByAccess` and return the two slices we care about. What do you think?

2021-06-11 15:32 UTC, cpoile commented on server/playbook/service.go
> +	}
Could we remove one of these loops by adding to the `res` after you check whether we've seen the item yet?

2021-06-11 15:41 UTC, lieut-data requested changes
Neat! A few comments below for discussion:

2021-06-14 13:25 UTC, iomodo commented on server/api/signal.go
> +func (h *SignalHandler) returnError(returnMessage string, err error, w http.ResponseWriter) {
It won't work. It's not just an api endpoint it's a post action endpoint. And needs to return `PostActionIntegrationResponse`. I'll make this explicit to avoid confusion

2021-06-14 13:32 UTC, iomodo commented on server/api/signal.go
> +		h.returnError(publicErrorMessage, err, w)
Strange. I have configured as 4 spaces. And vsCode visualises as 4 spaces. Not sure why here it is visualised as 8

2021-06-14 13:37 UTC, iomodo commented on server/incident/service.go
> +	if len(options) == 1 {
Preselecting the "incorrect" playbook seems wrong to me. I'll defer this to @itao and @abhijit-singh

2021-06-14 13:38 UTC, iomodo commented on server/playbook/service.go
> +	resultedTriggers := []string{}
We do not know the size of the `resultedTriggers`. It may well be that all playbooks are triggered by one word. Or It may be that one playbook is triggered by multiple words.

2021-06-14 13:42 UTC, iomodo commented on server/playbook/service.go
> +	return resultedPlaybooks, removeDuplicates(resultedTriggers)
It's not possible for these arrays to have same lengths. One possibility is that `resultedTriggers` could be the `[][]string` with the same length as `resultedPlaybooks`. To keep info which playbooks where triggered by which keywords. Since we don't really need that data I just appended everything and removed duplicates.

2021-06-14 13:50 UTC, iomodo commented on server/playbook/service.go
>  	playbookIDs, err := s.store.GetPlaybookIDsForUser(userID, teamID)
If I understood correctly it will be pretty much the same code just in the `store`(since, we won't introduce playbookIDs in the select). So having more general `GetPlaybookIDsForUser`  in the `store` makes bit more sense to me.

2021-06-14 13:52 UTC, iomodo commented on server/playbook/service.go
>  		if strings.Contains(message, keyword) {
I'd defer this to @itao and @abhijit-singh as well.
Users always can have ` sev ` as a keyword and this message will not be triggered. I'm 0/5 on this.

2021-06-14 13:57 UTC, iomodo commented on server/playbook/keywords_ignore.go
> +		ignoredThreads: map[string]map[string]bool{},
Correct it is not persistent and it's not compatible with HA. That's intentional. I thought since it's an additional thing to the main feature it's OK to be fuzzy. Implementing DB logic for this seems an overkill to me. You will have to check a DB on every message to know whether this thread is ignored or not. cc @cpoile 

Regarding the over-promising I'll remove the message altogether.

2021-06-14 17:43 UTC, iomodo commented on server/playbook/service.go
> +	}
It will be cleaner to read, but complexity would be `O(n^2)` vs `O(n)`(Since checking is `O(n)`). Number of triggers will not be big, but I'd rather stick to the lower complexity solution.

2021-06-14 18:07 UTC, iomodo commented
> Would it make sense to remove the action buttons after clicking so that the prompts disappear and "clean up" the channel for the enduser?

@lieut-data What would qualify as "clean up"? Is there a way to edit the ephemeral post, from the post action update? I think no?

2021-06-17 09:15 UTC, abhijit-singh commented
Looks good @iomodo. Could you add a screenshot of the configuration screen as well? 

Also, how does the trigger work once the user runs a playbook from a thread? Are we ignoring all future messages in that thread for all users?

2021-06-17 12:55 UTC, lieut-data approved these changes
Looking forward to seeing this live, @iomodo!

2021-06-17 12:57 UTC, lieut-data commented
@cpoile / @abhijit-singh, if possible, I'd love to get this merged today so we can deploy it as part of v1.13.0 and test in community.

2021-06-17 13:14 UTC, cpoile commented on server/playbook/service.go
> +	}
Sorry, maybe I'm miscommunicating? This is all I mean:
```
func removeDuplicates(a []string) []string {
	items := make(map[string]bool)
	var res []string
	for _, item := range a {
		if !items[item] {
			items[item] = true
			res = append(res, item)
		}
	}
	return res
}
```

2021-06-17 13:21 UTC, cpoile approved these changes
Awesome, thanks again @iomodo! I left some code in a previous comment thread, but up to you if you want to use it.

2021-06-17 13:21 UTC, cpoile commented on server/playbook/keywords_ignore.go
> +		ignoredThreads: map[string]map[string]bool{},
I agree we should leave it for another PR. :) 

But, just to add this: I think in HA this PR won't really do what we want it to, and users will probably think it's broken. 

There would be a way to do this that would hit the DB only when you ignore a new thread -- you keep each node up to date with the current ignore map (the same way we do the `JobOnceScheduler` in the `plugin-api`).

2021-06-17 14:39 UTC, iomodo commented
Merging this to create a PR to master

2021-06-17 14:39 UTC, merged