MM-36540 - Improve graph searching & polish
mattermost/mattermost-plugin-incident-collaboration pull request #620
Opened 2021-06-29 19:52 UTC by cpoile

#### Summary
- Can review based on commit
- When clicking on the graph, add a pill to indicate that the runs list is being filtered
- Cursor changed to pointer (only on graphs that are clickable)
- Weeks start on Sunday for stats, and end a millisecond before midnight on the last day of the range. Hopefully this will fix the wonky graphs on community.
- Only show whole numbers on the y axis for the line graphs
- Designs: (see the topleftmost design) https://www.figma.com/file/vhVlHvJVNTxW6g9PLLnzI0/Playbook-Details?node-id=2%3A3949

E.g., after clicking on the `Total Runs` graph:
![image](https://user-images.githubusercontent.com/1490756/123858403-7a916900-d8f1-11eb-94a9-268e67100572.png)

E.g., after clicking on the `Active Runs` graph:
![image](https://user-images.githubusercontent.com/1490756/123858520-9e54af00-d8f1-11eb-9ccf-ae973a9c1f1b.png)

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-36540

#### Checklist
- [ ] ~~Telemetry updated~~
- [x] Gated by experimental feature flag
- [ ] ~~Unit tests updated~~

2021-06-29 19:54 UTC, cpoile commented on webapp/src/components/assets/icons/clear_icon.tsx
> +export default styled.i.attrs(() => ({className: 'icon icon-close-circle'}))`
I think we need to change our compass icon elements into something like this, or else we can't attach onClick handlers (and many others, I assume).

2021-06-29 20:03 UTC, lieut-data approved these changes
Looks good! Just a handful of thoughts.

2021-06-29 20:03 UTC, lieut-data commented on webapp/src/components/backstage/playbooks/stats_view.tsx
> +            props.setFilterPill(pill(text));
nit: It feels weird to be passing around a JSX component like this, especially persisted in state and passed up to the parent, though it does have the advantage of coupling the text with the onClick handler without having the intermediates "know" about it. No immediate suggestion for improvement, though.

I wonder

2021-06-29 20:18 UTC, cpoile commented on webapp/src/components/assets/icons/clear_icon.tsx
> +export default styled.i.attrs(() => ({className: 'icon icon-close-circle'}))`
Yep, we could do that too! I kind of wanted to keep it as close to the original `i` element as possible, to let the caller wrap it in a `span` or whatever if they wanted to. But i'm 0/5 on which approach. Or maybe 1/5 to keep it close to `i`. :)

2021-06-29 20:23 UTC, cpoile commented on webapp/src/components/backstage/playbooks/stats_view.tsx
> +            props.setFilterPill(pill(text));
I see what you mean. We could pass around the text and have the parent, or the sibling create the pill when there's text available. On the other hand, this way the parent and sibling don't care, they just pass around and display an element (even if it's null). All logic and pill creation is isolated in the stats component. 
But yah, it's not the cleanest.

2021-06-29 22:03 UTC, lieut-data commented on webapp/src/components/backstage/playbooks/stats_view.tsx
> +            props.setFilterPill(pill(text));
I imagine the "right" thing to do is actually to use shared state here, ala Redux. Not necessary now!

2021-06-30 15:49 UTC, agarciamontoro requested changes
Really nice feature, and I did not find anything remarkable in the code :tada:

I have found a bug while trying it out, though: after you click on any of the graphs to filter the run list, if you click on the Owner filter, it crashes. The console shows this:

![image](https://user-images.githubusercontent.com/3924815/123991871-602bbe00-d9cb-11eb-9a5b-41d01282d602.png)
![image](https://user-images.githubusercontent.com/3924815/123991909-691c8f80-d9cb-11eb-9968-a323e01968ab.png)

2021-06-30 17:13 UTC, agarciamontoro approved these changes
A `make clean && make deploy` (after updating nvm to 16.4) fixed that error only I could reproduce :man_shrugging: Sorry for the noise!

2021-06-30 17:14 UTC, merged